package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.model.enums.ddv4

import uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.models.enums.ProbationServiceRegion

enum class ProbationDeliveryUnits(val value: String) {
  BARKING_AND_DAGENHAM_AND_HAVERING("Barking and Dagenham and Havering"),
  BARNSLEY_AND_ROTHERHAM("Barnsley and Rotherham"),
  BATH_AND_NORTH_SOMERSET("Bath and North Somerset"),
  BEDFORDSHIRE("Bedfordshire"),
  BIRMINGHAM_CENTRAL_AND_SOUTH("Birmingham Central and South"),
  BIRMINGHAM_COURTS_AND_DENTRALISED_FUNCTIONS("Birmingham Courts and Centralised Functions"),
  BIRMINGHAM_NORTH_EAST_AND_SOLIHULL("Birmingham North, East and Solihull"),
  BLACKBURN("Blackburn"),
  BOLTON("Bolton"),
  BRADFORD_AND_CALDERDALE("Bradford and Calderdale"),
  BRENT("Brent"),
  BRISTOL_AND_SOUTH_GLOUCESTERSHIRE("Bristol and South Gloucestershire"),
  BUCKINGHAM_AND_MILTON_KEYNES("Buckinghamshire and Milton Keynes"),
  BURY_AND_ROCHDALE("Bury and Rochdale"),
  CAMBRIDGESHIRE("Cambridgeshire"),
  CAMDEN_AND_ISLINGTON("Camden and Islington"),
  CARDIFF_AND_THE_VALE("Cardiff and the Vale"),
  CENTRAL_LANCASHIRE("Central Lancashire"),
  CHESHIRE_EAST("Cheshire East"),
  CHESHIRE_WEST("Cheshire West"),
  CORNWALL_AND_ISLES_OF_SCILLY("Cornwall and Isles of Scilly"),
  COUNTY_DURHAM_AND_DARLINGTON("County Durham and Darlington"),
  COVENTRY("Coventry"),
  CROYDON("Croydon"),
  CUMBRIA("Cumbria"),
  CWM_TAF_MORGANNWG("Cwm Taf Morgannwg"),
  DERBY_CITY("Derby City"),
  DERBYSHIRE("Derbyshire"),
  DEVON_AND_TORBAY("Devon and Torbay"),
  DONCASTER("Doncaster"),
  DORSET("Dorset"),
  DUDLEY_AND_SANDWELL("Dudley and Sandwell"),
  DYFED_POWYS("Dyfed Powys"),
  EALING_AND_HILLINGDOM("Ealing and Hillingdom"),
  EAST_AND_WEST_LINCOLNSHIRE("East and West Lincolnshire"),
  EAST_BERKSHIRE("East Berkshire"),
  EAST_KENT("East Kent"),
  EAST_LANCASHIRE("East Lancashire"),
  EAST_SUSSEX("East Sussex"),
  ENFIELD_AND_HARINGEY("Enfield and Haringey"),
  ESSEX_NORTH("Essex North"),
  ESSEX_SOUTH("Essex South"),
  GATESHEAD_AND_SOUTH_TYNESIDE("Gateshead and South Tyneside"),
  GLOUCESTERSHIRE("Gloucestershire"),
  GREENWICH_AND_BEXLEY("Greenwich and Bexley"),
  GWENT("Gwent"),
  HACKNEY_AND_CITY("Hackney and City"),
  HAMMERSMITH_FULHAM_KENSINGTON_CHELSEA_AND_WESTMINSTER("Hammersmith, Fulham, Kensington, Chelsea and Westminster"),
  HAMPSHIRE_NORTH_AND_EAST("Hampshire North and East"),
  HAMPSHIRE_SOUTH_AND_ISLE_OF_WHITE("Hampshire South and Isle of White"),
  HAMPSHIRE_SOUTH_WEST("Hampshire South West"),
  HARROW_AND_BARNET("Harrow and Barnet"),
  HEREFORD_SHROPSHIRE_AND_TELFORD("Hereford, Shropshire and Telford"),
  HERTFORDSHIRE("Hertfordshire"),
  HULL_AND_EAST_RIDING("Hull and East Riding"),
  KINGSTON_RICHMOND_AND_HOUNSLOW("Kingston, Richmond and Hounslow"),
  KIRKLEES("Kirklees"),
  KNOWSLEY_AND_ST_HELENS("Knowsley and St Helens"),
  LAMBETH("Lambeth"),
  LEEDS("Leeds"),
  LEICESTER_LEICESTERSHIRE_AND_RUTLAND("Leicester, Leicestershire and Rutland"),
  LEWISHAM_AND_BROMLEY("Lewisham and Bromley"),
  LIVERPOOL_NORTH("Liverpool North"),
  LIVERPOOL_SOUTH("Liverpool South"),
  MANCHESTER_NORTH("Manchester North"),
  MANCHESTER_SOUTH("Manchester South"),
  NEWCASTLE_UPON_TYNE("Newcastle Upon Tyne"),
  NEWHAM("Newham"),
  NORFOLK("Norfolk"),
  NORTH_AND_NORTH_EAST_LINCS("North and North East Lincs"),
  NORTH_KENT_AND_MEDWAY("North Kent and Medway"),
  NORTH_TYNESIDE_AND_NORTHUMBERLAND("North Tyneside and Northumberland"),
  NORTH_WALES("North Wales"),
  NORTH_WEST_LANCASHIRE("North West Lancashire"),
  NORTH_YORKSHIRE("North Yorkshire"),
  NORTHAMPTONSHIRE("Northamptonshire"),
  NOTTINGHAM_CITY("Nottingham City"),
  NOTTINGHAMSHIRE("Nottinghamshire"),
  OLDHAM("Oldham"),
  OXFORDSHIRE("Oxfordshire"),
  PLYMOUTH("Plymouth"),
  REDBRIDGE_AND_WALTHAM_FOREST("Redbridge and Waltham Forest"),
  REDCAR_CLEVELAND_AND_MIDDLESBROUGH("Redcar, Cleveland and Middlesbrough"),
  SALFORD("Salford"),
  SEFTON_AND_MERSEYSIDE_WOMENS("Sefton and Merseyside Womens"),
  SHEFFIELD("Sheffield"),
  SOMERSET("Somerset"),
  SOUTHWARK("Southwark"),
  STAFFORDSHIRE_AND_STOKE("Staffordshire and Stoke"),
  STOCKPORT_AND_TRAFFORD("Stockport and Trafford"),
  STOCKTON_AND_HARTLEPOOL("Stockton and Hartlepool"),
  SUFFOLK("Suffolk"),
  SUNDERLAND("Sunderland"),
  SURREY("Surrey"),
  SWANSEA_NEATH_PORT_TALBOT("Swansea, Neath and Port-Talbot"),
  SWINDON_AND_WILTSHIRE("Swindon and Wiltshire"),
  TAMESIDE("Tameside"),
  TOWER_HAMLETS("Tower Hamlets"),
  WAKEFIELD("Wakefield"),
  WALSALL_AND_WOLVERHAMPTON("Walsall and Wolverhampton"),
  WANDSWORTH_MERTON_AND_SUTTON("Wandsworth, Merton and Sutton"),
  WARRINGTON_AND_HALTON("Warrington and Halton"),
  WARWICKSHIRE("Warwickshire"),
  WEST_BERKSHIRE("West Berkshire"),
  WEST_KENT("West Kent"),
  WEST_SUSSEX("West Sussex"),
  WIGAN("Wigan"),
  WIRRAL_AND_ISC_TEAM("Wirral and ISC Team"),
  WORCESTERSHIRE("Worcestershire"),
  YORK("York"),
  ;

  companion object {
    fun from(value: String?): ProbationDeliveryUnits? = entries.firstOrNull {
      it.name == value
    }

    val PROBATION_REGION_DELIVERY_UNIT = mapOf(
      // EAST_MIDLANDS
      ProbationServiceRegion.EAST_MIDLANDS.name to listOf(
        DERBY_CITY,
        DERBYSHIRE,
        EAST_AND_WEST_LINCOLNSHIRE,
        LEICESTER_LEICESTERSHIRE_AND_RUTLAND,
        NOTTINGHAM_CITY,
        NOTTINGHAMSHIRE,
      ),

      // EAST_OF_ENGLAND
      ProbationServiceRegion.EAST_OF_ENGLAND.name to listOf(
        BEDFORDSHIRE,
        CAMBRIDGESHIRE,
        ESSEX_NORTH,
        ESSEX_SOUTH,
        HERTFORDSHIRE,
        NORFOLK,
        NORTHAMPTONSHIRE,
        SUFFOLK,
      ),

      // GREATER_MANCHESTER
      ProbationServiceRegion.GREATER_MANCHESTER.name to listOf(
        BOLTON,
        BURY_AND_ROCHDALE,
        MANCHESTER_NORTH,
        MANCHESTER_SOUTH,
        OLDHAM,
        SALFORD,
        STOCKPORT_AND_TRAFFORD,
        TAMESIDE,
        WIGAN,
      ),

      // KENT_SURREY_SUSSEX
      ProbationServiceRegion.KENT_SURREY_SUSSEX.name to listOf(
        EAST_KENT,
        EAST_SUSSEX,
        SURREY,
        WEST_KENT,
        WEST_SUSSEX,
        NORTH_KENT_AND_MEDWAY,
      ),

      // LONDON
      ProbationServiceRegion.LONDON.name to listOf(
        BARKING_AND_DAGENHAM_AND_HAVERING,
        BRENT,
        CAMDEN_AND_ISLINGTON,
        CROYDON,
        EALING_AND_HILLINGDOM,
        ENFIELD_AND_HARINGEY,
        GREENWICH_AND_BEXLEY,
        HACKNEY_AND_CITY,
        HAMMERSMITH_FULHAM_KENSINGTON_CHELSEA_AND_WESTMINSTER,
        HARROW_AND_BARNET,
        KINGSTON_RICHMOND_AND_HOUNSLOW,
        LAMBETH,
        LEWISHAM_AND_BROMLEY,
        NEWHAM,
        REDBRIDGE_AND_WALTHAM_FOREST,
        SOUTHWARK,
        TOWER_HAMLETS,
        WANDSWORTH_MERTON_AND_SUTTON,
      ),

      // NORTH_EAST
      ProbationServiceRegion.NORTH_EAST.name to listOf(
        COUNTY_DURHAM_AND_DARLINGTON,
        GATESHEAD_AND_SOUTH_TYNESIDE,
        NEWCASTLE_UPON_TYNE,
        NORTH_TYNESIDE_AND_NORTHUMBERLAND,
        REDCAR_CLEVELAND_AND_MIDDLESBROUGH,
        STOCKTON_AND_HARTLEPOOL,
        SUNDERLAND,
      ),

      // NORTH_WEST
      ProbationServiceRegion.NORTH_WEST.name to listOf(
        BLACKBURN,
        CENTRAL_LANCASHIRE,
        CHESHIRE_EAST,
        CHESHIRE_WEST,
        CUMBRIA,
        EAST_LANCASHIRE,
        KNOWSLEY_AND_ST_HELENS,
        LIVERPOOL_NORTH,
        LIVERPOOL_SOUTH,
        NORTH_WEST_LANCASHIRE,
        SEFTON_AND_MERSEYSIDE_WOMENS,
        WARRINGTON_AND_HALTON,
        WIRRAL_AND_ISC_TEAM,
      ),

      // SOUTH_CENTRAL
      ProbationServiceRegion.SOUTH_CENTRAL.name to listOf(
        BUCKINGHAM_AND_MILTON_KEYNES,
        EAST_BERKSHIRE,
        HAMPSHIRE_NORTH_AND_EAST,
        HAMPSHIRE_SOUTH_AND_ISLE_OF_WHITE,
        HAMPSHIRE_SOUTH_WEST,
        OXFORDSHIRE,
        WEST_BERKSHIRE,
      ),

      // SOUTH_WEST
      ProbationServiceRegion.SOUTH_WEST.name to listOf(
        BATH_AND_NORTH_SOMERSET,
        BRISTOL_AND_SOUTH_GLOUCESTERSHIRE,
        CORNWALL_AND_ISLES_OF_SCILLY,
        DEVON_AND_TORBAY,
        DORSET,
        GLOUCESTERSHIRE,
        PLYMOUTH,
        SOMERSET,
        SWINDON_AND_WILTSHIRE,
      ),

      // WALES
      ProbationServiceRegion.WALES.name to listOf(
        CARDIFF_AND_THE_VALE,
        CWM_TAF_MORGANNWG,
        DYFED_POWYS,
        GWENT,
        NORTH_WALES,
        SWANSEA_NEATH_PORT_TALBOT,

      ),

      // WEST_MIDLANDS
      ProbationServiceRegion.WEST_MIDLANDS.name to listOf(
        BIRMINGHAM_CENTRAL_AND_SOUTH,
        BIRMINGHAM_COURTS_AND_DENTRALISED_FUNCTIONS,
        BIRMINGHAM_NORTH_EAST_AND_SOLIHULL,
        COVENTRY,
        DUDLEY_AND_SANDWELL,
        HEREFORD_SHROPSHIRE_AND_TELFORD,
        STAFFORDSHIRE_AND_STOKE,
        WALSALL_AND_WOLVERHAMPTON,
        WARWICKSHIRE,
        WORCESTERSHIRE,
      ),

      // YORKSHIRE_AND_THE_HUMBER
      ProbationServiceRegion.YORKSHIRE_AND_THE_HUMBER.name to listOf(
        BARNSLEY_AND_ROTHERHAM,
        BRADFORD_AND_CALDERDALE,
        DONCASTER,
        HULL_AND_EAST_RIDING,
        KIRKLEES,
        LEEDS,
        NORTH_AND_NORTH_EAST_LINCS,
        NORTH_YORKSHIRE,
        SHEFFIELD,
        WAKEFIELD,
        YORK,
      ),

    )
  }
}
