package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.models.enums

enum class CivilCountyCourtDDv5(val value: String) {
  ABERYSTWYTH_COUNTY_AND_CIVIL_COURT("Aberystwyth County and Civil Court"),
  ALDERSHOT_COUNTY_AND_CIVIL_COURT("Aldershot County and Civil Court"),
  BARNET_COUNTY_AND_CIVIL_COURT("Barnet County and Civil Court"),
  BARNSLEY_COUNTY_AND_CIVIL_COURT("Barnsley County and Civil Court"),
  BARNSTABLE_COUNTY_AND_CIVIL_COURT("Barnstable County and Civil Court"),
  BARROW_COUNTY_AND_CIVIL_COURT("Barrow County and Civil Court"),
  BASILDON_COUNTY_AND_CIVIL_COURT("Basildon County and Civil Court"),
  BASINGSTOKE_COUNTY_AND_CIVIL_COURT("Basingstoke County and Civil Court"),
  BATH_COUNTY_AND_CIVIL_COURT("Bath County and Civil Court"),
  BEDFORD_COUNTY_AND_CIVIL_COURT("Bedford County and Civil Court"),
  BIRKENHEAD_COUNTY_AND_CIVIL_COURT("Birkenhead County and Civil Court"),
  BIRMINGHAM_COUNTY_AND_CIVIL_COURT("Birmingham County and Civil Court"),
  BLACKBURN_COUNTY_AND_CIVIL_COURT("Blackburn County and Civil Court"),
  BLACKPOOL_COUNTY_AND_CIVIL_COURT("Blackpool County and Civil Court"),
  BLACKWOOD_COUNTY_AND_CIVIL_COURT("Blackwood County and Civil Court"),
  BODMIN_COUNTY_AND_CIVIL_COURT("Bodmin County and Civil Court"),
  BOSTON_COUNTY_AND_CIVIL_COURT("Boston County and Civil Court"),
  BOURNEMOUTH_COUNTY_AND_CIVIL_COURT("Bournemouth County and Civil Court"),
  BRADFORD_COUNTY_AND_CIVIL_COURT("Bradford County and Civil Court"),
  BRENTFORD_COUNTY_AND_CIVIL_COURT("Brentford County and Civil Court"),
  BRIGHTON_COUNTY_AND_CIVIL_COURT("Brighton County and Civil Court"),
  BRISTOL_COUNTY_AND_CIVIL_COURT("Bristol County and Civil Court"),
  BROMLEY_COUNTY_AND_CIVIL_COURT("Bromley County and Civil Court"),
  BURNLEY_COUNTY_AND_CIVIL_COURT("Burnley County and Civil Court"),
  BURY_ST_EDMONDS_COUNTY_AND_CIVIL_COURT("Bury St Edmonds County and Civil Court"),
  CAERNARFON_COUNTY_AND_CIVIL_COURT("Caernarfon County and Civil Court"),
  CAMBRIDGE_COUNTY_AND_CIVIL_COURT("Cambridge County and Civil Court"),
  CANTERBURY_COUNTY_AND_CIVIL_COURT("Canterbury County and Civil Court"),
  CARDIFF_COUNTY_AND_CIVIL_COURT("Cardiff County and Civil Court"),
  CARLISLE_COUNTY_AND_CIVIL_COURT("Carlisle County and Civil Court"),
  CARMARTHEN_COUNTY_AND_CIVIL_COURT("Carmarthen (hearings only) County and Civil Court"),
  CENTRAL_LONDON_COUNTY_AND_CIVIL_COURT("Central London County and Civil Court"),
  CHELMSFORD_COUNTY_AND_CIVIL_COURT("Chelmsford County and Civil Court"),
  CHESTER_COUNTY_AND_CIVIL_COURT("Chester County and Civil Court"),
  CHESTERFIELD_COUNTY_AND_CIVIL_COURT("Chesterfield County and Civil Court"),
  CLERKENWELL_AND_SHOREDITCH_COUNTY_AND_CIVIL_COURT("Clerkenwell & Shoreditch County and Civil Court"),
  COURT_OF_PROTECTION_COURT_COUNTY_AND_CIVIL_COURT("Court of Protection Court County and Civil Court"),
  COVENTRY_COUNTY_AND_CIVIL_COURT("Coventry County and Civil Court"),
  CREWE_COUNTY_AND_CIVIL_COURT("Crewe County and Civil Court"),
  CROYDON_COUNTY_AND_CIVIL_COURT("Croydon County and Civil Court"),
  DARLINGTON_COUNTY_AND_CIVIL_COURT("Darlington County and Civil Court"),
  DARTFORD_COUNTY_AND_CIVIL_COURT("Dartford County and Civil Court"),
  DERBY_COUNTY_AND_CIVIL_COURT("Derby County and Civil Court"),
  DONCASTER_COUNTY_AND_CIVIL_COURT("Doncaster County and Civil Court"),
  DUDLEY_COUNTY_AND_CIVIL_COURT("Dudley County and Civil Court"),
  DURHAM_COUNTY_AND_CIVIL_COURT("Durham County and Civil Court"),
  EDMONTON_COUNTY_AND_CIVIL_COURT("Edmonton County and Civil Court"),
  EXETER_COUNTY_AND_CIVIL_COURT("Exeter County and Civil Court"),
  GATESHEAD_COUNTY_AND_CIVIL_COURT("Gateshead County and Civil Court"),
  GLOUCESTER_COUNTY_AND_CIVIL_COURT("Gloucester County and Civil Court"),
  GRIMSBY_COUNTY_AND_CIVIL_COURT("Grimsby County and Civil Court"),
  GUILDFORD_COUNTY_AND_CIVIL_COURT("Guildford County and Civil Court"),
  HARROGATE_COUNTY_AND_CIVIL_COURT("Harrogate County and Civil Court"),
  HASTINGS_COUNTY_AND_CIVIL_COURT("Hastings County and Civil Court"),
  HAVERFORDWEST_COUNTY_AND_CIVIL_COURT("Haverfordwest County and Civil Court"),
  HEREFORD_COUNTY_AND_CIVIL_COURT("Hereford County and Civil Court"),
  HERTFORD_COUNTY_AND_CIVIL_COURT("Hertford County and Civil Court"),
  HIGH_WYCOMBE_COUNTY_AND_CIVIL_COURT("High Wycombe County and Civil Court"),
  HORSHAM_COUNTY_AND_CIVIL_COURT("Horsham County and Civil Court"),
  HUDDERSFIELD_COUNTY_AND_CIVIL_COURT("Huddersfield County and Civil Court"),
  IPSWICH_COUNTY_AND_CIVIL_COURT("Ipswich County and Civil Court"),
  KINGSTON_UPON_HULL_COUNTY_AND_CIVIL_COURT("Kingston Upon Hull County and Civil Court"),
  KINGSTON_UPON_THAMES_COUNTY_AND_CIVIL_COURT("Kingston upon Thames County and Civil Court"),
  LANCASTER_COUNTY_AND_CIVIL_COURT("Lancaster County and Civil Court"),
  LEEDS_COUNTY_AND_CIVIL_COURT("Leeds County and Civil Court"),
  LEICESTER_COUNTY_AND_CIVIL_COURT("Leicester County and Civil Court"),
  LEWES_COUNTY_AND_CIVIL_COURT("Lewes County and Civil Court"),
  LINCOLN_COUNTY_AND_CIVIL_COURT("Lincoln County and Civil Court"),
  LIVERPOOL_COUNTY_AND_CIVIL_COURT("Liverpool County and Civil Court"),
  LLANDRINDOD_WELLS__COUNTY_AND_CIVIL_COURT("Llandrindod Wells (hearings only) County and Civil Court"),
  LLANELLI_COUNTY_AND_CIVIL_COURT("Llanelli County and Civil Court"),
  LUTON_COUNTY_AND_CIVIL_COURT("Luton County and Civil Court"),
  MAIDSTONE_COUNTY_AND_CIVIL_COURT("Maidstone County and Civil Court"),
  MANCHESTER_COUNTY_AND_CIVIL_COURT("Manchester County and Civil Court"),
  MANSFIELD__COUNTY_AND_CIVIL_COURT("Mansfield  County and Civil Court"),
  MAYORS_AND_CITY_OF_LONDON_COUNTY_AND_CIVIL_COURT("Mayors & City of London County and Civil Court"),
  MEDWAY_COUNTY_AND_CIVIL_COURT("Medway County and Civil Court"),
  MERTHYR_COUNTY_AND_CIVIL_COURT("Merthyr County and Civil Court"),
  MILTON_KEYNES_COUNTY_AND_CIVIL_COURT("Milton Keynes County and Civil Court"),
  MOLD_COUNTY_AND_CIVIL_COURT("Mold (hearings only)  County and Civil Court"),
  NEWCASTLE_COUNTY_AND_CIVIL_COURT("Newcastle County and Civil Court"),
  NEWPORT_IOW_COUNTY_AND_CIVIL_COURT("Newport (IOW) County and Civil Court"),
  NEWPORT_SOUTH_WALES_COUNTY_AND_CIVIL_COURT("Newport (South Wales)  County and Civil Court"),
  NORTH_SHIELDS_COUNTY_AND_CIVIL_COURT("North Shields County and Civil Court"),
  NORTHAMPTON_COUNTY_AND_CIVIL_COURT("Northampton County and Civil Court"),
  NORWICH_COUNTY_AND_CIVIL_COURT("Norwich County and Civil Court"),
  NOTTINGHAM_COUNTY_AND_CIVIL_COURT("Nottingham County and Civil Court"),
  NUNEATON_COUNTY_AND_CIVIL_COURT("Nuneaton County and Civil Court"),
  OXFORD_COUNTY_AND_CIVIL_COURT("Oxford County and Civil Court"),
  PETERBOROUGH_COUNTY_AND_CIVIL_COURT("Peterborough County and Civil Court"),
  PLYMOUTH_COUNTY_AND_CIVIL_COURT("Plymouth County and Civil Court"),
  PONTYPRIDD_COUNTY_AND_CIVIL_COURT("Pontypridd County and Civil Court"),
  PORT_TALBOT_COUNTY_AND_CIVIL_COURT("Port Talbot County and Civil Court"),
  PORTSMOUTH_COUNTY_AND_CIVIL_COURT("Portsmouth County and Civil Court"),
  PRESTATYN_COUNTY_AND_CIVIL_COURT("Prestatyn County and Civil Court"),
  PRESTON_COUNTY_AND_CIVIL_COURT("Preston County and Civil Court"),
  READING_COUNTY_AND_CIVIL_COURT("Reading County and Civil Court"),
  ROMFORD_COUNTY_AND_CIVIL_COURT("Romford County and Civil Court"),
  SALISBURY_COUNTY_AND_CIVIL_COURT("Salisbury County and Civil Court"),
  SCARBOROUGH_COUNTY_AND_CIVIL_COURT("Scarborough County and Civil Court"),
  SHEFFIELD_COUNTY_AND_CIVIL_COURT("Sheffield County and Civil Court"),
  SKIPTON_COUNTY_AND_CIVIL_COURT("Skipton County and Civil Court"),
  SLOUGH_COUNTY_AND_CIVIL_COURT("Slough County and Civil Court"),
  SOUTH_SHIELDS_COUNTY_AND_CIVIL_COURT("South Shields County and Civil Court"),
  SOUTHAMPTON_COUNTY_AND_CIVIL_COURT("Southampton County and Civil Court"),
  SOUTHEND_COUNTY_AND_CIVIL_COURT("Southend County and Civil Court"),
  ST_HELENS_COUNTY_AND_CIVIL_COURT("St Helens County and Civil Court"),
  STAINES_COUNTY_AND_CIVIL_COURT("Staines County and Civil Court"),
  STOCKPORT_COUNTY_AND_CIVIL_COURT("Stockport County and Civil Court"),
  STOKE_ON_TRENT_COUNTY_AND_CIVIL_COURT("Stoke on Trent County and Civil Court"),
  SUNDERLAND_COUNTY_AND_CIVIL_COURT("Sunderland County and Civil Court"),
  SWANSEA_COUNTY_AND_CIVIL_COURT("Swansea County and Civil Court"),
  SWINDON_COUNTY_AND_CIVIL_COURT("Swindon County and Civil Court"),
  TAUNTON_COUNTY_AND_CIVIL_COURT("Taunton County and Civil Court"),
  TEESIDE_COUNTY_AND_CIVIL_COURT("Teeside County and Civil Court"),
  TELFORD_COUNTY_AND_CIVIL_COURT("Telford County and Civil Court"),
  THANET_COUNTY_AND_CIVIL_COURT("Thanet County and Civil Court"),
  TORQUAY_AND_NEWTON_ABBOTT_COUNTY_AND_CIVIL_COURT("Torquay & Newton Abbott County and Civil Court"),
  TRURO_COUNTY_AND_CIVIL_COURT("Truro County and Civil Court"),
  UXBRIDGE_COUNTY_AND_CIVIL_COURT("Uxbridge County and Civil Court"),
  WAKEFIELD_COUNTY_AND_CIVIL_COURT("Wakefield County and Civil Court"),
  WALSALL_COUNTY_AND_CIVIL_COURT("Walsall County and Civil Court"),
  WANDSWORTH_COUNTY_AND_CIVIL_COURT("Wandsworth County and Civil Court"),
  WARWICK_COUNTY_AND_CIVIL_COURT("Warwick County and Civil Court"),
  WATFORD_COUNTY_AND_CIVIL_COURT("Watford County and Civil Court"),
  WELSHPOOL_COUNTY_AND_CIVIL_COURT("Welshpool (hearings only) County and Civil Court"),
  WEST_CUMBRIA_COUNTY_AND_CIVIL_COURT("West Cumbria (aka Workington) County and Civil Court"),
  WESTON_SUPER_MARE_COUNTY_AND_CIVIL_COURT("Weston Super Mare County and Civil Court"),
  WEYMOUTH_COUNTY_AND_CIVIL_COURT("Weymouth County and Civil Court"),
  WIGAN_COUNTY_AND_CIVIL_COURT("Wigan County and Civil Court"),
  WILLESDEN_COUNTY_AND_CIVIL_COURT("Willesden County and Civil Court"),
  WINCHESTER_COUNTY_AND_CIVIL_COURT("Winchester County and Civil Court"),
  WOLVERHAMPTON_COUNTY_AND_CIVIL_COURT("Wolverhampton County and Civil Court"),
  WORCESTER_COUNTY_AND_CIVIL_COURT("Worcester County and Civil Court"),
  WORTHING_COUNTY_AND_CIVIL_COURT("Worthing County and Civil Court"),
  WREXHAM_COUNTY_AND_CIVIL_COURT("Wrexham County and Civil Court"),
  YEOVIL_COUNTY_AND_CIVIL_COURT("Yeovil County and Civil Court"),
  YORK_COUNTY_AND_CIVIL_COURT("York County and Civil Court"),
  ;

  companion object {
    fun from(value: String?): CivilCountyCourtDDv5? = CivilCountyCourtDDv5.entries.firstOrNull {
      it.name == value
    }
  }
}
