package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.models.enums

enum class FamilyCourtDDv5(val value: String) {
  KENT_SURREY_SUSSEX("Kent, Surrey & Sussex"),
  ABERYSTWYTH_FAMILY_COURT("Aberystwyth Family Court"),
  ALDERSHOT_FAMILY_COURT("Aldershot Family Court"),
  BARNET_FAMILY_COURT("Barnet Family Court"),
  BARNSLEY_FAMILY_COURT("Barnsley Family Court"),
  BARNSTABLE_FAMILY_COURT("Barnstable Family Court"),
  BARROW_FAMILY_COURT("Barrow Family Court"),
  BASILDON_FAMILY_COURT("Basildon Family Court"),
  BASINGSTOKE_FAMILY_COURT("Basingstoke Family Court"),
  BATH_FAMILY_COURT("Bath Family Court"),
  BEDFORD_FAMILY_COURT("Bedford Family Court"),
  BIRKENHEAD_FAMILY_COURT("Birkenhead Family Court"),
  BIRMINGHAM_FAMILY_COURT("Birmingham Family Court"),
  BLACKBURN_FAMILY_COURT("Blackburn Family Court"),
  BLACKPOOL_FAMILY_COURT("Blackpool Family Court"),
  BLACKWOOD_FAMILY_COURT("Blackwood Family Court"),
  BODMIN_FAMILY_COURT("Bodmin Family Court"),
  BOSTON_FAMILY_COURT("Boston Family Court"),
  BOURNEMOUTH_FAMILY_COURT("Bournemouth Family Court"),
  BRADFORD_FAMILY_COURT("Bradford Family Court"),
  BRENTFORD_FAMILY_COURT("Brentford Family Court"),
  BRIGHTON_FAMILY_COURT("Brighton Family Court"),
  BRISTOL_FAMILY_COURT("Bristol Family Court"),
  BROMLEY_FAMILY_COURT("Bromley Family Court"),
  BURNLEY_FAMILY_COURT("Burnley Family Court"),
  BURY_ST_EDMONDS_FAMILY_COURT("Bury St Edmonds Family Court"),
  CAERNARFON_FAMILY_COURT("Caernarfon Family Court"),
  CAMBRIDGE_FAMILY_COURT("Cambridge Family Court"),
  CANTERBURY_FAMILY_COURT("Canterbury Family Court"),
  CARDIFF_FAMILY_COURT("Cardiff Family Court"),
  CARLISLE_FAMILY_COURT("Carlisle Family Court"),
  CARMARTHEN_HEARINGS_ONLY_FAMILY_COURT("Carmarthen (hearings only) Family Court"),
  CENTRAL_FAMILY_COURT("Central Family Court"),
  CENTRAL_LONDON_FAMILY_COURT("Central London Family Court"),
  CHELMSFORD_FAMILY_COURT("Chelmsford Family Court"),
  CHESTER_FAMILY_COURT("Chester Family Court"),
  CHESTERFIELD_FAMILY_COURT("Chesterfield Family Court"),
  CLERKENWELL_AND_SHOREDITCH_FAMILY_COURT("Clerkenwell & Shoreditch Family Court"),
  COURT_OF_PROTECTION_COURT_FAMILY_COURT("Court of Protection Court Family Court"),
  COVENTRY_FAMILY_COURT("Coventry Family Court"),
  CREWE_FAMILY_COURT("Crewe Family Court"),
  CROYDON_FAMILY_COURT("Croydon Family Court"),
  DARLINGTON_FAMILY_COURT("Darlington Family Court"),
  DARTFORD_FAMILY_COURT("Dartford Family Court"),
  DERBY_FAMILY_COURT("Derby Family Court"),
  DONCASTER_FAMILY_COURT("Doncaster Family Court"),
  DUDLEY_FAMILY_COURT("Dudley Family Court"),
  DURHAM_FAMILY_COURT("Durham Family Court"),
  EAST_LONDON_FAMILY_COURT("East London Family Court"),
  EDMONTON_FAMILY_COURT("Edmonton Family Court"),
  EXETER_FAMILY_COURT("Exeter Family Court"),
  GATESHEAD_FAMILY_COURT("Gateshead Family Court"),
  GLOUCESTER_FAMILY_COURT("Gloucester Family Court"),
  GRIMSBY_FAMILY_COURT("Grimsby Family Court"),
  GUILDFORD_FAMILY_COURT("Guildford Family Court"),
  HARROGATE_FAMILY_COURT("Harrogate Family Court"),
  HASTINGS_FAMILY_COURT("Hastings Family Court"),
  HAVERFORDWEST_FAMILY_COURT("Haverfordwest Family Court"),
  HEREFORD_FAMILY_COURT("Hereford Family Court"),
  HERTFORD_FAMILY_COURT("Hertford Family Court"),
  HIGH_WYCOMBE_FAMILY_COURT("High Wycombe Family Court"),
  HORSHAM_FAMILY_COURT("Horsham Family Court"),
  HUDDERSFIELD_FAMILY_COURT("Huddersfield Family Court"),
  IPSWICH_FAMILY_COURT("Ipswich Family Court"),
  KINGSTON_UPON_HULL_FAMILY_COURT("Kingston Upon Hull Family Court"),
  KINGSTON_UPON_THAMES_FAMILY_COURT("Kingston upon Thames Family Court"),
  LANCASTER_FAMILY_COURT("Lancaster Family Court"),
  LEEDS_FAMILY_COURT("Leeds Family Court"),
  LEICESTER_FAMILY_COURT("Leicester Family Court"),
  LEWES_FAMILY_COURT("Lewes Family Court"),
  LINCOLN_FAMILY_COURT("Lincoln Family Court"),
  LIVERPOOL_FAMILY_COURT("Liverpool Family Court"),
  LLANDRINDOD_WELLS_HEARINGS_ONLY_FAMILY_COURT("Llandrindod Wells (hearings only) Family Court"),
  LLANELLI_FAMILY_COURT("Llanelli Family Court"),
  LUTON_FAMILY_COURT("Luton Family Court"),
  MAIDSTONE_FAMILY_COURT("Maidstone Family Court"),
  MANCHESTER_FAMILY_COURT("Manchester Family Court"),
  MANSFIELD__FAMILY_COURT("Mansfield  Family Court"),
  MAYORS_AND_CITY_OF_LONDON_FAMILY_COURT("Mayors & City of London Family Court"),
  MEDWAY_FAMILY_COURT("Medway Family Court"),
  MERTHYR_FAMILY_COURT("Merthyr Family Court"),
  MILTON_KEYNES_FAMILY_COURT("Milton Keynes Family Court"),
  MOLD_HEARINGS_ONLY__FAMILY_COURT("Mold (hearings only)  Family Court"),
  NEWCASTLE_FAMILY_COURT("Newcastle Family Court"),
  NEWPORT_IOW_FAMILY_COURT("Newport (IOW) Family Court"),
  NEWPORT_SOUTH_WALES__FAMILY_COURT("Newport (South Wales)  Family Court"),
  NORTH_SHIELDS_FAMILY_COURT("North Shields Family Court"),
  NORTHAMPTON_FAMILY_COURT("Northampton Family Court"),
  NORWICH_FAMILY_COURT("Norwich Family Court"),
  NOTTINGHAM_FAMILY_COURT("Nottingham Family Court"),
  NUNEATON_FAMILY_COURT("Nuneaton Family Court"),
  OXFORD_FAMILY_COURT("Oxford Family Court"),
  PETERBOROUGH_FAMILY_COURT("Peterborough Family Court"),
  PLYMOUTH_FAMILY_COURT("Plymouth Family Court"),
  PONTYPRIDD_FAMILY_COURT("Pontypridd Family Court"),
  PORT_TALBOT_FAMILY_COURT("Port Talbot Family Court"),
  PORTSMOUTH_FAMILY_COURT("Portsmouth Family Court"),
  PRESTATYN_FAMILY_COURT("Prestatyn Family Court"),
  PRESTON_FAMILY_COURT("Preston Family Court"),
  READING_FAMILY_COURT("Reading Family Court"),
  ROMFORD_FAMILY_COURT("Romford Family Court"),
  SALISBURY_FAMILY_COURT("Salisbury Family Court"),
  SCARBOROUGH_FAMILY_COURT("Scarborough Family Court"),
  SHEFFIELD_FAMILY_COURT("Sheffield Family Court"),
  SKIPTON_FAMILY_COURT("Skipton Family Court"),
  SLOUGH_FAMILY_COURT("Slough Family Court"),
  SOUTH_SHIELDS_FAMILY_COURT("South Shields Family Court"),
  SOUTHAMPTON_FAMILY_COURT("Southampton Family Court"),
  SOUTHEND_FAMILY_COURT("Southend Family Court"),
  ST_HELENS_FAMILY_COURT("St Helens Family Court"),
  STAINES_FAMILY_COURT("Staines Family Court"),
  STOCKPORT_FAMILY_COURT("Stockport Family Court"),
  STOKE_ON_TRENT_FAMILY_COURT("Stoke on Trent Family Court"),
  SUNDERLAND_FAMILY_COURT("Sunderland Family Court"),
  SWANSEA_FAMILY_COURT("Swansea Family Court"),
  SWINDON_FAMILY_COURT("Swindon Family Court"),
  TAUNTON_FAMILY_COURT("Taunton Family Court"),
  TEESIDE_FAMILY_COURT("Teeside Family Court"),
  TELFORD_FAMILY_COURT("Telford Family Court"),
  THANET_FAMILY_COURT("Thanet Family Court"),
  TORQUAY_AND_NEWTON_ABBOTT_FAMILY_COURT("Torquay & Newton Abbott Family Court"),
  TRURO_FAMILY_COURT("Truro Family Court"),
  UXBRIDGE_FAMILY_COURT("Uxbridge Family Court"),
  WAKEFIELD_FAMILY_COURT("Wakefield Family Court"),
  WALSALL_FAMILY_COURT("Walsall Family Court"),
  WANDSWORTH_FAMILY_COURT("Wandsworth Family Court"),
  WARWICK_FAMILY_COURT("Warwick Family Court"),
  WATFORD_FAMILY_COURT("Watford Family Court"),
  WELSHPOOL_HEARINGS_ONLY_FAMILY_COURT("Welshpool (hearings only) Family Court"),
  WEST_CUMBRIA_AKA_WORKINGTON_FAMILY_COURT("West Cumbria (aka Workington) Family Court"),
  WEST_LONDON_FAMILY_COURT("West London Family Court"),
  WESTON_SUPER_MARE_FAMILY_COURT("Weston Super Mare Family Court"),
  WEYMOUTH_FAMILY_COURT("Weymouth Family Court"),
  WIGAN_FAMILY_COURT("Wigan Family Court"),
  WILLESDEN_FAMILY_COURT("Willesden Family Court"),
  WINCHESTER_FAMILY_COURT("Winchester Family Court"),
  WOLVERHAMPTON_FAMILY_COURT("Wolverhampton Family Court"),
  WORCESTER_FAMILY_COURT("Worcester Family Court"),
  WORTHING_FAMILY_COURT("Worthing Family Court"),
  WREXHAM_FAMILY_COURT("Wrexham Family Court"),
  YEOVIL_FAMILY_COURT("Yeovil Family Court"),
  YORK_FAMILY_COURT("York Family Court"),
  ;

  companion object {
    fun from(value: String?): FamilyCourtDDv5? = FamilyCourtDDv5.entries.firstOrNull {
      it.name == value
    }
  }
}
