package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.models.enums

enum class PrisonDDv5(val ids: List<String>, val value: String) {

  ALTCOURSE_PRISON(listOf("ACI"), "Altcourse Prison"),
  ASHFIELD_PRISON(listOf("ASI"), "Ashfield Prison"),
  ASKHAM_GRANGE_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(
    listOf("AGI"),
    "Askham Grange Prison and Young Offender Institution",
  ),
  AYLESBURY_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(listOf("AYI"), "Aylesbury Prison and Young Offender Institution"),
  BEDFORD_PRISON(listOf("BFI"), "Bedford Prison"),
  BELMARSH_PRISON(listOf("BAI"), "Belmarsh Prison"),
  BERWYN_PRISON(listOf("BWI"), "Berwyn Prison"),
  BIRMINGHAM_PRISON(listOf("BMI"), "Birmingham Prison"),
  BRINSFORD_PRISON(listOf("BSI"), "Brinsford Prison"),
  BRISTOL_PRISON(listOf("BLI"), "Bristol Prison"),
  BRIXTON_PRISON(listOf("BXI"), "Brixton Prison"),
  BRONZEFIELD_PRISON(listOf("BZI"), "Bronzefield Prison"),
  BUCKLEY_HALL_PRISON(listOf("BCI"), "Buckley Hall Prison"),
  BULLINGDON_PRISON(listOf("BNI"), "Bullingdon Prison"),
  BURE_PRISON(listOf("BRI"), "Bure Prison"),
  CARDIFF_PRISON(listOf("CFI"), "Cardiff Prison"),
  CHANNINGS_WOOD_PRISON(listOf("CWI"), "Channings Wood Prison"),
  CHELMSFORD_PRISON(listOf("CDI"), "Chelmsford Prison"),
  COLDINGLEY_PRISON(listOf("CLI"), "Coldingley Prison"),
  COOKHAM_WOOD_YOUNG_OFFENDER_INSTITUTION(listOf("CKI"), "Cookham Wood Young Offender Institution"),
  COOKHAM_WOOD_PRISON(listOf("CKI"), "Cookham Wood Prison"),
  DARTMOOR_PRISON(listOf("DAI"), "Dartmoor Prison"),
  DEERBOLT_PRISON(listOf("DTI"), "Deerbolt Prison"),
  DONCASTER_PRISON(listOf("DNI"), "Doncaster Prison"),
  DOVEGATE_PRISON(listOf("DGI"), "Dovegate Prison"),
  DOWNVIEW_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(listOf("DWI"), "Downview Prison and Young Offender Institution"),
  DRAKE_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(listOf("DHI"), "Drake Hall Prison and Young Offender Institution"),
  DURHAM_PRISON(listOf("DMI"), "Durham Prison"),
  EAST_SUTTON_PARK_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(
    listOf("ESI"),
    "East Sutton Park Prison and Young Offender Institution",
  ),
  EASTWOOD_PARK_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(
    listOf("EWI"),
    "Eastwood Park Prison and Young Offender Institution",
  ),
  ELMLEY_PRISON(listOf("EYI"), "Elmley Prison"),
  ERLESTOKE_PRISON(listOf("EEI"), "Erlestoke Prison"),
  EXETER_PRISON(listOf("EXI"), "Exeter Prison"),
  FEATHERSTONE_PRISON(listOf("FSI"), "Featherstone Prison"),
  FELTHAM_YOUNG_OFFENDER_INSTITUTION(listOf("FYI"), "Feltham Young Offender Institution"),
  FELTHAM_PRISON(listOf("FMI"), "Feltham Prison"),
  FIVE_WELLS_PRISON(listOf("FWI"), "Five Wells Prison"),
  FORD_PRISON(listOf("FDI"), "Ford Prison"),
  FOSSE_WAY_PRISON(listOf("FEI"), "Fosse Way Prison"),
  FOREST_BANK_PRISON(listOf("FBI"), "Forest Bank Prison"),
  FOSTON_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(listOf("FHI"), "Foston Hall Prison and Young Offender Institution"),
  FRANKLAND_PRISON(listOf("FKI"), "Frankland Prison"),
  FULL_SUTTON_PRISON(listOf("FNI"), "Full Sutton Prison"),
  GARTH_PRISON(listOf("GHI"), "Garth Prison"),
  GARTREE_PRISON(listOf("GTI"), "Gartree Prison"),
  GRENDON_PRISON(listOf("GNI"), "Grendon Prison"),
  GUYS_MARSH_PRISON(listOf("GMI"), "Guys Marsh Prison"),
  HATFIELD_PRISON(listOf("HDI"), "Hatfield Prison"),
  HAVERIGG_PRISON(listOf("HVI"), "Haverigg Prison"),
  HEWELL_PRISON(listOf("HEI"), "Hewell Prison"),
  HIGH_DOWN_PRISON(listOf("HOI"), "High Down Prison"),
  HIGHPOINT_PRISON(listOf("HPI"), "Highpoint Prison"),
  HINDLEY_PRISON(listOf("HII"), "Hindley Prison"),
  HOLLESLEY_BAY_PRISON(listOf("HBI"), "Hollesley Bay Prison"),
  HOLME_HOUSE_PRISON(listOf("HHI"), "Holme House Prison"),
  HULL_PRISON(listOf("HLI"), "Hull Prison"),
  HUMBER_PRISON(listOf("HMI"), "Humber Prison"),
  HUNTERCOMBE_PRISON(listOf("HCI"), "Huntercombe Prison"),
  ISIS_PRISON(listOf("ISI"), "Isis Prison"),
  ISLE_OF_WIGHT_PRISON(listOf("IWI"), "Isle of Wight Prison"),
  KIRKHAM_PRISON(listOf("KMI"), "Kirkham Prison"),
  KIRKLEVINGTON_GRANGE_PRISON(listOf("KVI"), "Kirklevington Grange Prison"),
  LANCASTER_FARMS_PRISON(listOf("LFI"), "Lancaster Farms Prison"),
  LEEDS_PRISON(listOf("LEI"), "Leeds Prison"),
  LEICESTER_PRISON(listOf("LCI"), "Leicester Prison"),
  LEWES_PRISON(listOf("LWI"), "Lewes Prison"),
  LEYHILL_PRISON(listOf("LYI"), "Leyhill Prison"),
  LINCOLN_PRISON(listOf("LII"), "Lincoln Prison"),
  LINDHOLME_PRISON(listOf("LHI"), "Lindholme Prison"),
  LITTLEHEY_PRISON(listOf("LTI"), "Littlehey Prison"),
  LIVERPOOL_PRISON(listOf("LPI"), "Liverpool Prison"),
  LONG_LARTIN_PRISON(listOf("LLI"), "Long Lartin Prison"),
  LOW_NEWTON_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(listOf("LNI"), "Low Newton Prison and Young Offender Institution"),
  LOWDHAM_GRANGE_PRISON(listOf("LGI"), "Lowdham Grange Prison"),
  MAIDSTONE_PRISON(listOf("MSI"), "Maidstone Prison"),
  MANCHESTER_PRISON(listOf("MRI"), "Manchester Prison"),
  MILLSIKE_PRISON(listOf("MKI"), "Millsike Prison"),
  MOORLAND_PRISON(listOf("MDI"), "Moorland Prison"),
  MORTON_HALL_PRISON(listOf("MHI"), "Morton Hall Prison"),
  NEW_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(listOf("NHI"), "New Hall Prison and Young Offender Institution"),
  NORTH_SEA_CAMP_PRISON(listOf("NSI"), "North Sea Camp Prison"),
  NORTHUMBERLAND_PRISON(listOf("NLI"), "Northumberland Prison"),
  NORWICH_PRISON(listOf("NWI"), "Norwich Prison"),
  NOTTINGHAM_PRISON(listOf("NMI"), "Nottingham Prison"),
  OAKWOOD_PRISON(listOf("OWI"), "Oakwood Prison"),
  ONLEY_PRISON(listOf("ONI"), "Onley Prison"),
  PARC_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(listOf("PRI", "PYI"), "Parc Prison and Young Offender Institute"),
  PENTONVILLE_PRISON(listOf("PVI"), "Pentonville Prison"),
  PETERBOROUGH_PRISON(listOf("PBI", "PFI"), "Peterborough Prison"),
  PORTLAND_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(listOf("PDI"), "Portland Prison and Young Offender Institution"),
  PRESCOED_PRISON(listOf("UPI"), "Prescoed Prison"),
  PRESTON_PRISON(listOf("PNI"), "Preston Prison"),
  RANBY_PRISON(listOf("RNI"), "Ranby Prison"),
  RISLEY_PRISON(listOf("RSI"), "Risley Prison"),
  ROCHESTER_PRISON(listOf("RCI"), "Rochester Prison"),
  RYE_HILL_PRISON(listOf("RHI"), "Rye Hill Prison"),
  SEND_PRISON(listOf("SDI"), "Send Prison"),
  SPRING_HILL_PRISON(listOf("SPI"), "Spring Hill Prison"),
  STAFFORD_PRISON(listOf("SFI"), "Stafford Prison"),
  STANDFORD_HILL_PRISON(listOf("EHI"), "Standford Hill Prison"),
  STOCKEN_PRISON(listOf("SKI"), "Stocken Prison"),
  STOKE_HEATH_PRISON(listOf("SHI"), "Stoke Heath Prison"),
  STYAL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(listOf("STI"), "Styal Prison and Young Offender Institution"),
  SUDBURY_PRISON(listOf("SUI"), "Sudbury Prison"),
  SWALESIDE_PRISON(listOf("SLI"), "Swaleside Prison"),
  SWANSEA_PRISON(listOf("SWI"), "Swansea Prison"),
  SWINFEN_HALL_PRISON(listOf("SNI"), "Swinfen Hall Prison"),
  THAMESIDE_PRISON(listOf("TSI"), "Thameside Prison"),
  THE_MOUNT_PRISON(listOf("MTI"), "The Mount Prison"),
  THE_VERNE_PRISON(listOf("VEI"), "The Verne Prison"),
  THORN_CROSS_PRISON(listOf("TCI"), "Thorn Cross Prison"),
  USK_PRISON(listOf("UKI"), "Usk Prison"),
  WAKEFIELD_PRISON(listOf("WDI"), "Wakefield Prison"),
  WANDSWORTH_PRISON(listOf("WWI"), "Wandsworth Prison"),
  WARREN_HILL_PRISON(listOf("WII"), "Warren Hill Prison"),
  WAYLAND_PRISON(listOf("WLI"), "Wayland Prison"),
  WEALSTUN_PRISON(listOf("WEI"), "Wealstun Prison"),
  WERRINGTON_YOUNG_OFFENDER_INSTITUTION(listOf("WNI"), "Werrington Young Offender Institution"),
  WETHERBY_YOUNG_OFFENDER_INSTITUTION(listOf("WYI"), "Wetherby Young Offender Institution"),
  WHATTON_PRISON(listOf("WTI"), "Whatton Prison"),
  WHITEMOOR_PRISON(listOf("WRI"), "Whitemoor Prison"),
  WINCHESTER_PRISON(listOf("WCI"), "Winchester Prison"),
  WOODHILL_PRISON(listOf("WHI"), "Woodhill Prison"),
  WORMWOOD_SCRUBS_PRISON(listOf("WSI"), "Wormwood Scrubs Prison"),
  WYMOTT_PRISON(listOf("WMI"), "Wymott Prison"),
  ;

  companion object {
    val PRISONS_IN_PILOT = listOf(
      CARDIFF_PRISON,
      FOSSE_WAY_PRISON,
      PETERBOROUGH_PRISON,
      RANBY_PRISON,
      SUDBURY_PRISON,
      SWANSEA_PRISON,
    )

    val YOI_PRISONS = listOf(
      ASKHAM_GRANGE_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      AYLESBURY_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      COOKHAM_WOOD_YOUNG_OFFENDER_INSTITUTION,
      DOWNVIEW_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      DRAKE_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      EAST_SUTTON_PARK_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      EASTWOOD_PARK_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      FELTHAM_YOUNG_OFFENDER_INSTITUTION,
      FOSTON_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      LOW_NEWTON_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      NEW_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      PARC_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      PORTLAND_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      STYAL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION,
      WERRINGTON_YOUNG_OFFENDER_INSTITUTION,
      WETHERBY_YOUNG_OFFENDER_INSTITUTION,
    )

    fun from(value: String?): PrisonDDv5? = entries.firstOrNull {
      it.name == value
    }

    fun fromId(id: String?): List<PrisonDDv5> = entries.filter { it.ids.contains(id?.uppercase()) }

    fun isPrisonYOI(name: PrisonDDv5?): Boolean = YOI_PRISONS.contains(name)
  }
}
