package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.models.enums

enum class YouthCourtDDv5(val value: String) {
  ABERYSTWYTH_YOUTH_COURT("Aberystwyth Youth Court"),
  ACCRINGTON_YOUTH_COURT("Accrington Youth Court"),
  ACTON_YOUTH_COURT("Acton Youth Court"),
  ALDRIDGE_YOUTH_COURT("Aldridge Youth Court"),
  ALNWICK_YOUTH_COURT("Alnwick Youth Court"),
  ALTON_YOUTH_COURT("Alton Youth Court"),
  AMERSHAM_YOUTH_COURT("Amersham Youth Court"),
  AMMANFORD_YOUTH_COURT("Ammanford Youth Court"),
  ANDOVER_YOUTH_COURT("Andover Youth Court"),
  AYLESBURY_YOUTH_COURT("Aylesbury Youth Court"),
  BARKING_YOUTH_COURT("Barking Youth Court"),
  BARNET_YOUTH_COURT("Barnet Youth Court"),
  BARNSLEY_YOUTH_COURT("Barnsley Youth Court"),
  BARNSTAPLE_YOUTH_COURT("Barnstaple Youth Court"),
  BARROW_IN_FURNESS_YOUTH_COURT("Barrow in Furness Youth Court"),
  BARRY_YOUTH_COURT("Barry Youth Court"),
  BASILDON_YOUTH_COURT("Basildon Youth Court"),
  BASINGSTOKE_YOUTH_COURT("Basingstoke Youth Court"),
  BATH_YOUTH_COURT("Bath Youth Court"),
  BATLEY_AND_DEWSBURY_YOUTH_COURT("Batley and Dewsbury Youth Court"),
  BEDFORD_YOUTH_COURT("Bedford Youth Court"),
  BERWICK_UPON_TWEED_YOUTH_COURT("Berwick upon Tweed Youth Court"),
  BEVERLEY_YOUTH_COURT("Beverley Youth Court"),
  BEXLEY_YOUTH_COURT("Bexley Youth Court"),
  BICESTER_YOUTH_COURT("Bicester Youth Court"),
  BIRMINGHAM_YOUTH_COURT("Birmingham Youth Court"),
  BISHOP_AUCKLAND_YOUTH_COURT("Bishop Auckland Youth Court"),
  BLACKBURN_YOUTH_COURT("Blackburn Youth Court"),
  BLACKPOOL_YOUTH_COURT("Blackpool Youth Court"),
  BLACKWOOD_YOUTH_COURT("Blackwood Youth Court"),
  BLANDFORD_FORUM_YOUTH_COURT("Blandford Forum Youth Court"),
  BLAYDON_YOUTH_COURT("Blaydon Youth Court"),
  BODMIN_YOUTH_COURT("Bodmin Youth Court"),
  BOLTON_YOUTH_COURT("Bolton Youth Court"),
  BOSTON_YOUTH_COURT("Boston Youth Court"),
  BOURNE_YOUTH_COURT("Bourne Youth Court"),
  BRADFORD_YOUTH_COURT("Bradford Youth Court"),
  BRENT_YOUTH_COURT("Brent Youth Court"),
  BRENTFORD_YOUTH_COURT("Brentford Youth Court"),
  BRIDGEND_YOUTH_COURT("Bridgend Youth Court"),
  BRIDGWATER_YOUTH_COURT("Bridgwater Youth Court"),
  BRIDLINGTON_YOUTH_COURT("Bridlington Youth Court"),
  BRIGHTON_YOUTH_COURT_JOHN_STREET("Brighton Youth Court (John Street)"),
  BRISTOL_YOUTH_COURT("Bristol Youth Court"),
  BROMLEY_YOUTH_COURT("Bromley Youth Court"),
  BROMSGROVE_AND_REDDITCH_YOUTH_COURT("Bromsgrove and Redditch Youth Court"),
  BURNLEY_YOUTH_COURT("Burnley Youth Court"),
  BURTON_UPON_TRENT_YOUTH_COURT("Burton upon Trent Youth Court"),
  BURY_ST_EDMUNDS_YOUTH_COURT("Bury St Edmunds Youth Court"),
  BURY_YOUTH_COURT("Bury Youth Court"),
  BUXTON_YOUTH_COURT("Buxton Youth Court"),
  CAERNARFON_YOUTH_COURT("Caernarfon Youth Court"),
  CALDERDALE_YOUTH_COURT("Calderdale Youth Court"),
  CAMBORNE_YOUTH_COURT("Camborne Youth Court"),
  CAMBRIDGE_YOUTH_COURT("Cambridge Youth Court"),
  CANNOCK_YOUTH_COURT("Cannock Youth Court"),
  CANTERBURY_YOUTH_COURT("Canterbury Youth Court"),
  CARDIFF_YOUTH_COURT("Cardiff Youth Court"),
  CARDIGAN_YOUTH_COURT("Cardigan Youth Court"),
  CARLISLE_YOUTH_COURT("Carlisle Youth Court"),
  CARMARTHEN_YOUTH_COURT("Carmarthen Youth Court"),
  CENTRAL_NORFOLK_YOUTH_COURT("Central Norfolk Youth Court"),
  CHATHAM_YOUTH_COURT("Chatham Youth Court"),
  CHELTENHAM_YOUTH_COURT("Cheltenham Youth Court"),
  CHESHUNT_YOUTH_COURT("Cheshunt Youth Court"),
  CHESTER_YOUTH_COURT("Chester Youth Court"),
  CHESTERFIELD_YOUTH_COURT_TAPTON_LANE("Chesterfield Youth Court (Tapton Lane)"),
  CHICHESTER_YOUTH_COURT("Chichester Youth Court"),
  CHIPPENHAM_YOUTH_COURT("Chippenham Youth Court"),
  CHORLEY_YOUTH_COURT("Chorley Youth Court"),
  CITY_OF_SALFORD_YOUTH_COURT("City of Salford Youth Court"),
  COALVILLE_YOUTH_COURT("Coalville Youth Court"),
  CONSETT_YOUTH_COURT("Consett Youth Court"),
  COVENTRY_YOUTH_COURT("Coventry Youth Court"),
  CRAWLEY_YOUTH_COURT("Crawley Youth Court"),
  CREWE_YOUTH_COURT("Crewe Youth Court"),
  CROYDON_YOUTH_COURT("Croydon Youth Court"),
  CWMBRAN_YOUTH_COURT("Cwmbran Youth Court"),
  DARLINGTON_YOUTH_COURT("Darlington Youth Court"),
  DARTFORD_YOUTH_COURT("Dartford Youth Court"),
  DENBIGH_YOUTH_COURT("Denbigh Youth Court"),
  DERBY_YOUTH_COURT_ST_MARYS_GATE("Derby Youth Court (St Mary's Gate)"),
  DIDCOT_YOUTH_COURT("Didcot Youth Court"),
  DONCASTER_YOUTH_COURT("Doncaster Youth Court"),
  DUDLEY_YOUTH_COURT("Dudley Youth Court"),
  DURHAM_YOUTH_COURT("Durham Youth Court"),
  EASTBOURNE_YOUTH_COURT("Eastbourne Youth Court"),
  ELY_YOUTH_COURT("Ely Youth Court"),
  EXETER_YOUTH_COURT("Exeter Youth Court"),
  FAREHAM_YOUTH_COURT("Fareham Youth Court"),
  FLEETWOOD_YOUTH_COURT("Fleetwood Youth Court"),
  FOLKESTONE_YOUTH_COURT("Folkestone Youth Court"),
  FROME_YOUTH_COURT("Frome Youth Court"),
  GAINSBOROUGH_YOUTH_COURT("Gainsborough Youth Court"),
  GLOSSOP_YOUTH_COURT("Glossop Youth Court"),
  GLOUCESTER_YOUTH_COURT("Gloucester Youth Court"),
  GOOLE_YOUTH_COURT("Goole Youth Court"),
  GOSFORTH_YOUTH_COURT("Gosforth Youth Court"),
  GRANTHAM_YOUTH_COURT("Grantham Youth Court"),
  GRAYS_YOUTH_COURT("Grays Youth Court"),
  GREAT_YARMOUTH_YOUTH_COURT("Great Yarmouth Youth Court"),
  GRIMSBY_YOUTH_COURT("Grimsby Youth Court"),
  HALESOWEN_YOUTH_COURT("Halesowen Youth Court"),
  HARLOW_YOUTH_COURT("Harlow Youth Court"),
  HARROGATE_YOUTH_COURT("Harrogate Youth Court"),
  HARROW_YOUTH_COURT("Harrow Youth Court"),
  HARTLEPOOL_YOUTH_COURT("Hartlepool Youth Court"),
  HARWICH_YOUTH_COURT("Harwich Youth Court"),
  HASTINGS_YOUTH_COURT("Hastings Youth Court"),
  HAVERFORDWEST_YOUTH_COURT("Haverfordwest Youth Court"),
  HAVERING_YOUTH_COURT("Havering Youth Court"),
  HEMEL_HEMPSTEAD_YOUTH_COURT("Hemel Hempstead Youth Court"),
  HENDON_YOUTH_COURT("Hendon Youth Court"),
  HEREFORD_YOUTH_COURT_BATH_STREET("Hereford Youth Court (Bath Street)"),
  HIGHGATE_YOUTH_COURT("Highgate Youth Court"),
  HINCKLEY_YOUTH_COURT("Hinckley Youth Court"),
  HOLYHEAD_YOUTH_COURT("Holyhead Youth Court"),
  HORSHAM_YOUTH_COURT("Horsham Youth Court"),
  HOUGHTON_LE_SPRING_YOUTH_COURT("Houghton le Spring Youth Court"),
  HUDDERSFIELD_YOUTH_COURT("Huddersfield Youth Court"),
  HULL_YOUTH_COURT("Hull Youth Court"),
  HUNTINGDON_YOUTH_COURT("Huntingdon Youth Court"),
  HUYTON_YOUTH_COURT("Huyton Youth Court"),
  ILKESTON_YOUTH_COURT("Ilkeston Youth Court"),
  INNER_LONDON_YOUTH_COURTS_CENTRE_1("Inner London Youth Courts Centre 1"),
  INNER_LONDON_YOUTH_COURTS_CENTRE_2("Inner London Youth Courts Centre 2"),
  INNER_LONDON_YOUTH_COURTS_CENTRE_3("Inner London Youth Courts Centre 3"),
  INNER_LONDON_YOUTH_COURTS_CENTRE_4("Inner London Youth Courts Centre 4"),
  IPSWICH_YOUTH_COURT("Ipswich Youth Court"),
  ISLE_OF_WIGHT_YOUTH_COURT("Isle of Wight Youth Court"),
  KEIGHLEY_YOUTH_COURT("Keighley Youth Court"),
  KENDAL_YOUTH_COURT("Kendal Youth Court"),
  KETTERING_YOUTH_COURT("Kettering Youth Court"),
  KIDDERMINSTER_YOUTH_COURT_COMBERTON_PLACE("Kidderminster Youth Court (Comberton Place)"),
  KINGSTON_UPON_THAMES_YOUTH_COURT("Kingston upon Thames Youth Court"),
  LANBAURGH_EAST_YOUTH_COURT_GUISBOROUGH("Lanbaurgh East Youth Court (Guisborough)"),
  LANCASTER_YOUTH_COURT("Lancaster Youth Court"),
  LEAMINGTON_SPA_YOUTH_COURT("Leamington Spa Youth Court"),
  LEEDS_YOUTH_COURT("Leeds Youth Court"),
  LEICESTER_YOUTH_COURT("Leicester Youth Court"),
  LEWES_YOUTH_COURT("Lewes Youth Court"),
  LEYLAND_YOUTH_COURT("Leyland Youth Court"),
  LINCOLN_YOUTH_COURT("Lincoln Youth Court"),
  LIVERPOOL_YOUTH_CODE_HATTON_GARDEN("Liverpool Youth Code (Hatton Garden)"),
  LLANDRINDOD_WELLS_YOUTH_COURT("Llandrindod Wells Youth Court"),
  LLANDUDNO_YOUTH_COURT("Llandudno Youth Court"),
  LLANELLI_YOUTH_COURT("Llanelli Youth Court"),
  LLANGEFNI_YOUTH_COURT("Llangefni Youth Court"),
  LLWYNYPIA_YOUTH_COURT("Llwynypia Youth Court"),
  LOUGHBOROUGH_YOUTH_COURT("Loughborough Youth Court"),
  LOUTH_YOUTH_COURT("Louth Youth Court"),
  LOWESTOFT_YOUTH_COURT("Lowestoft Youth Court"),
  LUTON_YOUTH_COURT("Luton Youth Court"),
  MACCLESFIELD_YOUTH_COURT_HIBEL_RD("Macclesfield Youth Court (Hibel Rd)"),
  MAIDENHEAD_YOUTH_COURT("Maidenhead Youth Court"),
  MAIDSTONE_YOUTH_COURT("Maidstone Youth Court"),
  MANCHESTER_CITY_YOUTH_COURT("Manchester City Youth Court"),
  MANSFIELD_YOUTH_COURT_ROSEMARY_ST("Mansfield Youth Court (Rosemary St)"),
  MARGATE_YOUTH_COURT("Margate Youth Court"),
  MARKET_DRAYTON_YOUTH_COURT("Market Drayton Youth Court"),
  MARKET_HARBOROUGH_YOUTH_COURT("Market Harborough Youth Court"),
  MELTON_MOWBRAY_YOUTH_COURT("Melton Mowbray Youth Court"),
  MERTHYR_TYDFIL_YOUTH_COURT("Merthyr Tydfil Youth Court"),
  MIDDLESBROUGH_YOUTH_COURT("Middlesbrough Youth Court"),
  MILTON_KEYNES_YOUTH_COURT("Milton Keynes Youth Court"),
  MINEHEAD_YOUTH_COURT("Minehead Youth Court"),
  MOLD_YOUTH_COURT("Mold Youth Court"),
  NEATH_YOUTH_COURT("Neath Youth Court"),
  NEW_FOREST_YOUTH_COURT("New Forest Youth Court"),
  NEWARK_YOUTH_COURT("Newark Youth Court"),
  NEWCASTLE_UNDER_LYME_YOUTH_COURT("Newcastle under Lyme Youth Court"),
  NEWCASTLE_UPON_TYNE_YOUTH_COURT("Newcastle Upon Tyne Youth Court"),
  NEWTON_ABBOT_YOUTH_COURT("Newton Abbot Youth Court"),
  NEWTON_AYCLIFFE_YOUTH_COURT("Newton Aycliffe Youth Court"),
  NORTH_NORFOLK_YOUTH_COURT("North Norfolk Youth Court"),
  NORTH_SEFTON_YOUTH_COURT("North Sefton Youth Court"),
  NORTH_SHIELDS_YOUTH_COURT("North Shields Youth Court"),
  NORTHALLERTON_YOUTH_COURT("Northallerton Youth Court"),
  NORTHAMPTON_YOUTH_COURT("Northampton Youth Court"),
  NORTHWICH_YOUTH_COURT("Northwich Youth Court"),
  NORWICH_YOUTH_COURT("Norwich Youth Court"),
  NOTTINGHAM_YOUTH_COURT_CARRINGTON_ST("Nottingham Youth Court (Carrington St)"),
  NUNEATON_YOUTH_COURT_VICARAGE_ST("Nuneaton Youth Court, Vicarage St"),
  OLDBURY_YOUTH_COURT("Oldbury Youth Court"),
  OLDHAM_YOUTH_COURT("Oldham Youth Court"),
  ORMSKIRK_YOUTH_COURT("Ormskirk Youth Court"),
  OSWESTRY_YOUTH_COURT("Oswestry Youth Court"),
  OXFORD_YOUTH_COURT("Oxford Youth Court"),
  PENRITH_YOUTH_CODE("Penrith Youth Code"),
  PENZANCE_YOUTH_COURT("Penzance Youth Court"),
  PETERBOROUGH_YOUTH_COURT("Peterborough Youth Court"),
  PETERLEE_YOUTH_COURT("Peterlee Youth Court"),
  PLYMOUTH_YOUTH_COURT("Plymouth Youth Court"),
  PONTEFRACT_YOUTH_COURT("Pontefract Youth Court"),
  POOLE_YOUTH_COURT("Poole Youth Court"),
  PORT_TALBOT_YOUTH_COURT("Port Talbot Youth Court"),
  PORTSMOUTH_YOUTH_COURT("Portsmouth Youth Court"),
  PRESTATYN_YOUTH_COURT("Prestatyn Youth Court"),
  PRESTON_YOUTH_COURT("Preston Youth Court"),
  PWLLHELI_YOUTH_COURT("Pwllheli Youth Court"),
  RAWTENSTALL_YOUTH_COURT("Rawtenstall Youth Court"),
  READING_YOUTH_COURT("Reading Youth Court"),
  REDBRIDGE_YOUTH_COURT("Redbridge Youth Court"),
  REDHILL_YOUTH_COURT("Redhill Youth Court"),
  REEDLEY_YOUTH_COURT("Reedley Youth Court"),
  RETFORD_YOUTH_COURT("Retford Youth Court"),
  RICHMOND_UPON_THAMES_YOUTH_COURT("Richmond upon Thames Youth Court"),
  ROCHDALE_YOUTH_COURT("Rochdale Youth Court"),
  ROTHERHAM_YOUTH_COURT("Rotherham Youth Court"),
  RUGBY_YOUTH_COURT("Rugby Youth Court"),
  SALISBURY_YOUTH_COURT("Salisbury Youth Court"),
  SCARBOROUGH_YOUTH_COURT_NORTHWAY("Scarborough Youth Court (Northway)"),
  SCUNTHORPE_YOUTH_COURT("Scunthorpe Youth Court"),
  SELBY_YOUTH_COURT("Selby Youth Court"),
  SEVENOAKS_YOUTH_COURT("Sevenoaks Youth Court"),
  SHEFFIELD_YOUTH_COURT("Sheffield Youth Court"),
  SHREWSBURY_YOUTH_COURT("Shrewsbury Youth Court"),
  SITTINGBOURNE_YOUTH_COURT("Sittingbourne Youth Court"),
  SKEGNESS_YOUTH_COURT("Skegness Youth Court"),
  SKIPTON_YOUTH_COURT("Skipton Youth Court"),
  SLEAFORD_YOUTH_COURT("Sleaford Youth Court"),
  SOLIHULL_YOUTH_COURT("Solihull Youth Court"),
  SOUTH_EAST_NORTHUMBERLAND_YOUTH_COURT("South East Northumberland Youth Court"),
  SOUTH_NORFOLK_YOUTH_COURT("South Norfolk Youth Court"),
  SOUTH_SEFTON_YOUTH_COURT("South Sefton Youth Court"),
  SOUTH_SHIELDS_YOUTH_COURT_MILLBANK("South Shields Youth Court (Millbank)"),
  SOUTH_SHROPSHIRE_YOUTH_COURT("South Shropshire Youth Court"),
  SOUTH_WORCESTER_YOUTH_COURT("South Worcester Youth Court"),
  SOUTHAMPTON_YOUTH_COURT("Southampton Youth Court"),
  SOUTHEND_ON_SEA_YOUTH_COURT("Southend on Sea Youth Court"),
  SPALDING_YOUTH_COURT("Spalding Youth Court"),
  ST_ALBANS_YOUTH_COURT("St Albans Youth Court"),
  ST_HELENS_YOUTH_COURT("St Helens Youth Court"),
  STAFFORD_YOUTH_COURT("Stafford Youth Court"),
  STAINES_YOUTH_COURT("Staines Youth Court"),
  STEVENAGE_YOUTH_COURT("Stevenage Youth Court"),
  STOCKPORT_YOUTH_COURT("Stockport Youth Court"),
  STOKE_ON_TRENT_YOUTH_COURT("Stoke on Trent Youth Court"),
  STRATFORD_YOUTH_COURT("Stratford Youth Court"),
  SUDBURY_YOUTH_COURT("Sudbury Youth Court"),
  SUNDERLAND_YOUTH_COURT("Sunderland Youth Court"),
  SUTTON_COLDFIELD_YOUTH_COURT("Sutton Coldfield Youth Court"),
  SUTTON_YOUTH_COURT("Sutton Youth Court"),
  SWANSEA_YOUTH_COURT_DYNEVOR_PLACE("Swansea Youth Court (Dynevor Place)"),
  SWINDON_YOUTH_COURT("Swindon Youth Court"),
  TAMESIDE_YOUTH_COURT("Tameside Youth Court"),
  TAMWORTH_YOUTH_COURT("Tamworth Youth Court"),
  TAUNTON_YOUTH_COURT("Taunton Youth Court"),
  TELFORD_AND_BRIDGENORTH_YOUTH_COURT("Telford and Bridgenorth Youth Court"),
  TOTTENHAM_YOUTH_COURT("Tottenham Youth Court"),
  TRAFFORD_YOUTH_COURT("Trafford Youth Court"),
  TRURO_YOUTH_COURT("Truro Youth Court"),
  TYNEDALE_YOUTH_COURT("Tynedale Youth Court"),
  UXBRIDGE_YOUTH_COURT("Uxbridge Youth Court"),
  WAKEFIELD_YOUTH_COURT("Wakefield Youth Court"),
  WALSALL_YOUTH_COURT_STAFFORD_STREET("Walsall Youth Court (Stafford Street)"),
  WALTHAM_FOREST_YOUTH_COURT("Waltham Forest Youth Court"),
  WARRINGTON_YOUTH_COURT_ARPLEY_STREET("Warrington Youth Court (Arpley Street)"),
  WELLINGBOROUGH_YOUTH_COURT("Wellingborough Youth Court"),
  WELLS_YOUTH_COURT("Wells Youth Court"),
  WELSHPOOL_YOUTH_COURT("Welshpool Youth Court"),
  WEST_BERKSHIRE_YOUTH_COURT("West Berkshire Youth Court"),
  WEST_BROMWICH_YOUTH_COURT("West Bromwich Youth Court"),
  WEST_NORFOLK_YOUTH_COURT("West Norfolk Youth Court"),
  WESTON_SUPER_MARE_YOUTH_COURT("Weston-super-Mare Youth Court"),
  WEYMOUTH_YOUTH_COURT("Weymouth Youth Court"),
  WHITEHAVEN_YOUTH_COURT("Whitehaven Youth Court"),
  WIDNES_YOUTH_COURT("Widnes Youth Court"),
  WIGAN_YOUTH_COURT("Wigan Youth Court"),
  WIMBLEDON_YOUTH_COURT("Wimbledon Youth Court"),
  WIRRAL_YOUTH_COURT("Wirral Youth Court"),
  WISBECH_YOUTH_COURT("Wisbech Youth Court"),
  WITHAM_YOUTH_COURT("Witham Youth Court"),
  WOKING_YOUTH_COURT("Woking Youth Court"),
  WOLVERHAMPTON_YOUTH_COURT("Wolverhampton Youth Court"),
  WORKINGTON_YOUTH_COURT("Workington Youth Court"),
  WORKSOP_YOUTH_COURT("Worksop Youth Court"),
  WORTHING_YOUTH_COURT("Worthing Youth Court"),
  WREXHAM_YOUTH_COURT("Wrexham Youth Court"),
  WYCOMBE_YOUTH_COURT("Wycombe Youth Court"),
  YATE_YOUTH_COURT("Yate Youth Court"),
  YEOVIL_YOUTH_COURT("Yeovil Youth Court"),
  YORK_YOUTH_COURT("York Youth Court"),
  ;

  companion object {
    fun from(value: String?): YouthCourtDDv5? = YouthCourtDDv5.entries.firstOrNull {
      it.name == value
    }
  }
}
