spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    datasource:
      url: jdbc:postgresql://localhost:5432/postgres?sslmode=prefer
      username: postgres
      password: postgres
    cloud:
  #      queueName: court_case_events_queue
  #      queueArn: arn:aws:sns:eu-west-2:000000000000:court_case_events_queue
  #      dlqName: court_case_events_dead_letter_queue
  hmpps.s3:
    bucketName: testbucket
  services:
    hmppsauth:
      url: http://localhost:9090/auth
    #    url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    document:
      url: http://localhost:8081/
    #    url: https://document-api-dev.hmpps.service.justice.gov.uk/
    manage-user:
      url: http://localhost:9091/manage-user/
  #    url: https://manage-users-dev.hmpps.service.justice.gov.uk/
  CLIENT_ID: hmpps-electronic-monitoring-create-an-order-api
  CLIENT_SECRET: clientsecret

  settings:
    device-wearer-payload-version: Dev
MANAGE_USER_URL: http://localhost:9091/manage-user
DDV6_COURT_MAPPINGS: true


