spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?sslmode=prefer
    username: postgres
    password: postgres
  cloud:
    aws:
      region:
        static: eu-west-2
      endpoint: http://127.0.0.1:4566

#Uncomment the below to setup localstack for sqs listener, require localstack running in docker compose
#hmpps.sqs:
#  provider: localstack
#  localstackUrl: http://localhost:4566
#  useWebToken: false
#  queues:
#    courthearingeventqueue:
#      queueName: court_case_events_queue
#      queueArn: arn:aws:sns:eu-west-2:000000000000:court_case_events_queue
#      dlqName: court_case_events_dead_letter_queue
hmpps.s3:
  bucketName: testbucket
services:
  hmppsauth:
    url: http://localhost:9091/auth
  #    url: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
  document:
    url: http://localhost:9091/hmpps
  #    url: https://document-api-dev.hmpps.service.justice.gov.uk/
  manage-user:
    url: http://localhost:9091/manage-user/
  #    url: https://manage-users-api-dev.hmpps.service.justice.gov.uk/
  core-person-record:
    url: http://localhost:9091/cpr
#    url: https://hmpps-person-record-dev.hmpps.service.justice.gov.uk/

notify:
  api-key: test
  templates:
    order-rejected-user: 5222afcd-cd14-47a2-ac94-f4e9fb546619
    order-rejected-no: a46310e0-e7f9-43a4-8fde-bc00e3b19c7a

CLIENT_ID: hmpps-electronic-monitoring-create-an-order-api
CLIENT_SECRET: clientsecret

settings:
  device-wearer-payload-version: Dev
