package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.models.enums.ddv6

enum class PoliceAreasDDv6(val value: String) {
  AVON_AND_SOMERSET("Avon and Somerset Constabulary"),
  BEDFORDSHIRE("Bedfordshire Police"),
  BRITISH_TRANSPORT_POLICE("British Transport Police"),
  CAMBRIDGESHIRE("Cambridgeshire Constabulary"),
  CHESHIRE("Cheshire Constabulary"),
  CITY_OF_LONDON("City of London Police"),
  CLEVELAND("Cleveland Police"),
  COUNTER_TERRORISM_POLICE_NORTH_EAST("Counter Terrorism Police - North East"),
  COUNTER_TERRORISM_POLICE_NORTH_WEST("Counter Terrorism Police - North West"),
  COUNTER_TERRORISM_POLICE_SOUTH_CENTRAL("Counter Terrorism Police - South Central"),
  COUNTER_TERRORISM_POLICE_SOUTH_EAST("Counter Terrorism Police - South East"),
  COUNTER_TERRORISM_POLICE_SOUTH_WEST("Counter Terrorism Police - South West"),
  COUNTER_TERRORISM_POLICE_WALES("Counter Terrorism Police - Wales"),
  CUMBRIA("Cumbria Constabulary"),
  DERBYSHIRE("Derbyshire Constabulary"),
  DEVON_AND_CORNWALL("Devon and Cornwall Police"),
  DORSET("Dorset Police"),
  DURHAM("Durham Constabulary"),
  DYFED_POWYS("Dyfed-Powys Police"),
  ESSEX("Essex Police"),
  GLOUCESTERSHIRE("Gloucestershire Constabulary"),
  GREATER_MANCHESTER("Greater Manchester Police"),
  GWENT("Gwent Police"),
  HAMPSHIRE("Hampshire Constabulary"),
  HERTFORDSHIRE("Hertfordshire Constabulary"),
  HUMBERSIDE("Humberside Police"),
  KENT("Kent Police"),
  LANCASHIRE("Lancashire Constabulary"),
  LEICESTERSHIRE("Leicestershire Police"),
  LINCOLNSHIRE("Lincolnshire Police"),
  MERSEYSIDE("Merseyside Police"),
  METROPOLITAN_POLICE("Metropolitan Police Service"),
  NATIONAL_CRIME_AGENCY("National Crime Agency"),
  NORFOLK("Norfolk Constabulary"),
  NORTH_WALES("North Wales Police"),
  NORTH_YORKSHIRE("North Yorkshire Police"),
  NORTHAMPTONSHIRE("Northamptonshire Police"),
  NORTHUMBRIA("Northumbria Police"),
  NOTTINGHAMSHIRE("Nottinghamshire Police"),
  SO15_CTNM("SO15 CTNM"),
  SOUTH_WALES("South Wales Police"),
  SOUTH_YORKSHIRE("South Yorkshire Police"),
  STAFFORDSHIRE("Staffordshire Police"),
  SUFFOLK("Suffolk Constabulary"),
  SURREY("Surrey Police"),
  SUSSEX("Sussex Police"),
  THAMES_VALLEY("Thames Valley Police"),
  WARWICKSHIRE("Warwickshire Police"),
  WEST_MERCIA("West Mercia Police"),
  WEST_MIDLANDS("West Midlands Police"),
  WEST_YORKSHIRE("West Yorkshire Police"),
  WILTSHIRE("Wiltshire Police"),
  DIFFERENT_POLICE_AREA("The device wearer's release address is in a different police force area"),
  ;

  companion object {
    fun from(value: String?): PoliceAreasDDv6? = entries.firstOrNull {
      it.name == value
    }
  }
}
