package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.models.enums.ddv6

enum class PoliceAreasDDv6(val value: String) {
  AVON_AND_SOMERSET("Avon and Somerset"),
  BEDFORDSHIRE("Bedfordshire"),
  BRITISH_TRANSPORT_POLICE("British Transport Police"),
  CAMBRIDGESHIRE("Cambridgeshire"),
  CHESHIRE("Cheshire"),
  CITY_OF_LONDON("City of London"),
  CLEVELAND("Cleveland"),
  COUNTER_TERRORISM_POLICE_NORTH_EAST("Counter Terrorism Police North East"),
  COUNTER_TERRORISM_POLICE_NORTH_WEST("Counter Terrorism Police North West"),
  COUNTER_TERRORISM_POLICE_SOUTH_CENTRAL("Counter Terrorism Police South Central"),
  COUNTER_TERRORISM_POLICE_SOUTH_EAST("Counter Terrorism Police South East"),
  COUNTER_TERRORISM_POLICE_SOUTH_WEST("Counter Terrorism Police South West"),
  COUNTER_TERRORISM_POLICE_WALES("Counter Terrorism Police Wales"),
  CUMBRIA("Cumbria"),
  DERBYSHIRE("Derbyshire"),
  DEVON_AND_CORNWALL("Devon and Cornwall"),
  DORSET("Dorset"),
  DURHAM("Durham"),
  DYFED_POWYS("Dyfed-Powys"),
  ESSEX("Essex"),
  GLOUCESTERSHIRE("Gloucestershire"),
  GREATER_MANCHESTER("Greater Manchester"),
  GWENT("Gwent"),
  HAMPSHIRE("Hampshire"),
  HERTFORDSHIRE("Hertfordshire"),
  HUMBERSIDE("Humberside"),
  KENT("Kent"),
  LANCASHIRE("Lancashire"),
  LEICESTERSHIRE("Leicestershire"),
  LINCOLNSHIRE("Lincolnshire"),
  MERSEYSIDE("Merseyside"),
  METROPOLITAN_POLICE("Metropolitan Police"),
  NATIONAL_CRIME_AGENCY("National Crime Agency"),
  NORFOLK("Norfolk"),
  NORTH_WALES("North Wales"),
  NORTH_YORKSHIRE("North Yorkshire"),
  NORTHAMPTONSHIRE("Northamptonshire"),
  NORTHUMBRIA("Northumbria"),
  NOTTINGHAMSHIRE("Nottinghamshire"),
  SO15_CTNM("SO15 CTNM"),
  SOUTH_WALES("South Wales"),
  SOUTH_YORKSHIRE("South Yorkshire"),
  STAFFORDSHIRE("Staffordshire"),
  SUFFOLK("Suffolk"),
  SURREY("Surrey"),
  SUSSEX("Sussex"),
  THAMES_VALLEY("Thames Valley"),
  WARWICKSHIRE("Warwickshire"),
  WEST_MERCIA("West Mercia"),
  WEST_MIDLANDS("West Midlands"),
  WEST_YORKSHIRE("West Yorkshire"),
  WILTSHIRE("Wiltshire"),
  DIFFERENT_POLICE_AREA("The device wearer's release address is in a different police force area"),
  ;

  companion object {
    fun from(value: String?): PoliceAreasDDv6? = entries.firstOrNull {
      it.name == value
    }
  }
}
