package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.model.fms.argumentsProvider

import org.junit.jupiter.api.extension.ExtensionContext
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.ArgumentsProvider
import java.util.stream.Stream

class CrownCourtArgumentsProvider : ArgumentsProvider {
  override fun provideArguments(context: ExtensionContext?): Stream<out Arguments?>? = Stream.of(
    Arguments.of("AMERSHAM_CROWN_COURT", "Amersham Crown Court"),
    Arguments.of("AYLESBURY_CROWN_COURT", "Aylesbury Crown Court"),
    Arguments.of("BARBICAN_ALDERSGATE_HOUSE_CROWN_COURT", "Barbican (Aldersgate House) Crown Court"),
    Arguments.of("BARNSTAPLE_CROWN_COURT", "Barnstaple Crown Court"),
    Arguments.of("BARROW_IN_FURNESS_CROWN_COURT", "Barrow in Furness Crown Court"),
    Arguments.of("BASILDON_CROWN_COURT", "Basildon Crown Court"),
    Arguments.of("BIRMINGHAM_CROWN_COURT", "Birmingham Crown Court"),
    Arguments.of("BLACKFRIARS_CROWN_COURT", "Blackfriars Crown Court"),
    Arguments.of("BOLTON_CROWN_COURT", "Bolton Crown Court"),
    Arguments.of("BOURNEMOUTH_CROWN_COURT", "Bournemouth Crown Court"),
    Arguments.of("BRADFORD_CROWN_COURT", "Bradford Crown Court"),
    Arguments.of("BRISTOL_CROWN_COURT", "Bristol Crown Court"),
    Arguments.of("BURNLEY_CROWN_COURT", "Burnley Crown Court"),
    Arguments.of("BURY_ST_EDMUNDS_CROWN_COURT", "Bury St Edmunds Crown Court"),
    Arguments.of("CAERNARFON_CROWN_COURT", "Caernarfon Crown Court"),
    Arguments.of("CAMBRIDGE_CROWN_COURT", "Cambridge Crown Court"),
    Arguments.of("CANTERBURY_CROWN_COURT", "Canterbury Crown Court"),
    Arguments.of("CARDIFF_CROWN_COURT", "Cardiff Crown Court"),
    Arguments.of("CARLISLE_CROWN_COURT", "Carlisle Crown Court"),
    Arguments.of("CARMARTHEN_CROWN_COURT", "Carmarthen Crown Court"),
    Arguments.of("CHELMSFORD_CROWN_COURT", "Chelmsford Crown Court"),
    Arguments.of("CHESTER_CROWN_COURT", "Chester Crown Court"),
    Arguments.of("CHICHESTER_CROWN_COURT", "Chichester Crown Court"),
    Arguments.of("CIRENCESTER_GLOUCESTER_CROWN_COURT", "Cirencester (Gloucester) Crown Court"),
    Arguments.of("COVENTRY_CROWN_COURT", "Coventry Crown Court"),
    Arguments.of("CROYDON_CROWN_COURT", "Croydon Crown Court"),
    Arguments.of("DERBY_CROWN_COURT", "Derby Crown Court"),
    Arguments.of("DOLGELLAU_CROWN_COURT", "Dolgellau Crown Court"),
    Arguments.of("DONCASTER_CROWN_COURT", "Doncaster Crown Court"),
    Arguments.of("DORCHESTER_CROWN_COURT", "Dorchester Crown Court"),
    Arguments.of("DURHAM_CROWN_COURT", "Durham Crown Court"),
    Arguments.of("EXETER_CROWN_COURT", "Exeter Crown Court"),
    Arguments.of("GLOUCESTER_CROWN_COURT", "Gloucester Crown Court"),
    Arguments.of("GRIMSBY_CROWN_COURT", "Grimsby Crown Court"),
    Arguments.of("GUILDFORD_CROWN_COURT", "Guildford Crown Court"),
    Arguments.of("HARROW_CROWN_COURT", "Harrow Crown Court"),
    Arguments.of("HAVERFORDWEST_CROWN_COURT", "Haverfordwest Crown Court"),
    Arguments.of("HEREFORD_CROWN_COURT", "Hereford Crown Court"),
    Arguments.of("INNER_LONDON_CROWN_COURT", "Inner London Crown Court"),
    Arguments.of("IPSWICH_CROWN_COURT", "Ipswich Crown Court"),
    Arguments.of("ISLEWORTH_CROWN_COURT", "Isleworth Crown Court"),
    Arguments.of("JURYS_INN_CROYDON_CROWN_COURT", "Jury's Inn Croydon Crown Court"),
    Arguments.of("KINGS_LYNN_CROWN_COURT", "King's Lynn Crown Court"),
    Arguments.of("KINGSTON_UPON_HULL_CROWN_COURT", "Kingston upon Hull Crown Court"),
    Arguments.of("KINGSTON_UPON_THAMES_CROWN_COURT", "Kingston upon Thames Crown Court"),
    Arguments.of("KNUTSFORD_CROWN_COURT", "Knutsford Crown Court"),
    Arguments.of("LANCASTER_CROWN_COURT", "Lancaster Crown Court"),
    Arguments.of("LEEDS_CROWN_COURT", "Leeds Crown Court"),
    Arguments.of("LEICESTER_CROWN_COURT", "Leicester Crown Court"),
    Arguments.of("LEWES_CROWN_COURT", "Lewes Crown Court"),
    Arguments.of("LINCOLN_CROWN_COURT", "Lincoln Crown Court"),
    Arguments.of("LIVERPOOL_CROWN_COURT", "Liverpool Crown Court"),
    Arguments.of("LOUGHBOROUGH_CROWN_COURT", "Loughborough Crown Court"),
    Arguments.of("LUTON_CROWN_COURT", "Luton Crown Court"),
    Arguments.of("MAIDSTONE_CROWN_COURT", "Maidstone Crown Court"),
    Arguments.of("MANCHESTER_CROWN_COURT_CROWN_SQUARE", "Manchester Crown Court (Crown Square)"),
    Arguments.of("MANCHESTER_CROWN_COURT_MINSHULL_ST", "Manchester Crown Court (Minshull St)"),
    Arguments.of("MERTHYR_TYDFIL_CROWN_COURT", "Merthyr Tydfil Crown Court"),
    Arguments.of("MIDDLESEX_GUILDHALL_CROWN_COURT", "Middlesex Guildhall Crown Court"),
    Arguments.of("MINSHULL_STREET_MANCHESTER__CROWN_COURT", "Minshull Street Manchester  Crown Court"),
    Arguments.of("MOLD_CROWN_COURT", "Mold Crown Court"),
    Arguments.of("MONUMENT_CROWN_COURT", "Monument Crown Court"),
    Arguments.of("NEWCASTLE_UPON_TYNE_CROWN_COURT", "Newcastle upon Tyne Crown Court"),
    Arguments.of("NEWPORT_SOUTH_WALES_CROWN_COURT", "Newport (South Wales) Crown Court"),
    Arguments.of("NORTHAMPTON_CROWN_COURT", "Northampton Crown Court"),
    Arguments.of("NORWICH_CROWN_COURT", "Norwich Crown Court"),
    Arguments.of("NOTTINGHAM_CROWN_COURT", "Nottingham Crown Court"),
    Arguments.of("OXFORD_CROWN_COURT", "Oxford Crown Court"),
    Arguments.of("PETERBOROUGH_CROWN_COURT", "Peterborough Crown Court"),
    Arguments.of("PLYMOUTH_CROWN_COURT", "Plymouth Crown Court"),
    Arguments.of("PORTSMOUTH_CROWN_COURT", "Portsmouth Crown Court"),
    Arguments.of("PRESTON_CROWN_COURT", "Preston Crown Court"),
    Arguments.of("PRESTON_NORTH_END_CROWN_COURT_CROWN_COURT", "Preston North End Crown Court Crown Court"),
    Arguments.of("READING_CROWN_COURT", "Reading Crown Court"),
    Arguments.of("ROYAL_COURTS_OF_JUSTICE_CROWN_COURT", "Royal Courts of Justice Crown Court"),
    Arguments.of("SALFORD_LOWRY_THEATRE_CROWN_COURT", "Salford Lowry Theatre Crown Court"),
    Arguments.of("SALISBURY_CROWN_COURT", "Salisbury Crown Court"),
    Arguments.of("SHEFFIELD_CROWN_COURT", "Sheffield Crown Court"),
    Arguments.of("SHREWSBURY_CROWN_COURT", "Shrewsbury Crown Court"),
    Arguments.of("SNARESBROOK_CROWN_COURT", "Snaresbrook Crown Court"),
    Arguments.of("SOUTHAMPTON_CROWN_COURT", "Southampton Crown Court"),
    Arguments.of("SOUTHEND_CROWN_COURT", "Southend Crown Court"),
    Arguments.of("SOUTHWARK_CROWN_COURT", "Southwark Crown Court"),
    Arguments.of("ST_ALBANS_CROWN_COURT", "St Albans Crown Court"),
    Arguments.of("STAFFORD_CROWN_COURT", "Stafford Crown Court"),
    Arguments.of("STOKE_CROWN_COURT", "Stoke Crown Court"),
    Arguments.of("SWANSEA_CROWN_COURT", "Swansea Crown Court"),
    Arguments.of("SWINDON_CROWN_COURT", "Swindon Crown Court"),
    Arguments.of("TAUNTON_CROWN_COURT", "Taunton Crown Court"),
    Arguments.of("TEESSIDE_CROWN_COURT", "Teesside Crown Court"),
    Arguments.of("TRURO_CROWN_COURT", "Truro Crown Court"),
    Arguments.of("WARRINGTON_CROWN_COURT", "Warrington Crown Court"),
    Arguments.of("WARWICK_CROWN_COURT", "Warwick Crown Court"),
    Arguments.of("WELSHPOOL_CROWN_COURT", "Welshpool Crown Court"),
    Arguments.of("WEYMOUTH_CROWN_COURT", "Weymouth Crown Court"),
    Arguments.of("WINCHESTER_CROWN_COURT", "Winchester Crown Court"),
    Arguments.of("WOLVERHAMPTON_CROWN_COURT", "Wolverhampton Crown Court"),
    Arguments.of("WOOD_GREEN_CROWN_COURT", "Wood Green Crown Court"),
    Arguments.of("WOOLWICH_CROWN_COURT", "Woolwich Crown Court"),
    Arguments.of("WORCESTER_CROWN_COURT", "Worcester Crown Court"),
    Arguments.of("YORK_CROWN_COURT", "York Crown Court"),
  )
}
