package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.model.fms.argumentsProvider

import org.junit.jupiter.api.extension.ExtensionContext
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.ArgumentsProvider
import java.util.stream.Stream

class FamilyCourtArgumentsProvider : ArgumentsProvider {
  override fun provideArguments(context: ExtensionContext?): Stream<out Arguments?>? = Stream.of(
    Arguments.of("KENT_SURREY_SUSSEX", "Kent, Surrey & Sussex"),
    Arguments.of("ABERYSTWYTH_FAMILY_COURT", "Aberystwyth Family Court"),
    Arguments.of("ALDERSHOT_FAMILY_COURT", "Aldershot Family Court"),
    Arguments.of("BARNET_FAMILY_COURT", "Barnet Family Court"),
    Arguments.of("BARNSLEY_FAMILY_COURT", "Barnsley Family Court"),
    Arguments.of("BARNSTABLE_FAMILY_COURT", "Barnstable Family Court"),
    Arguments.of("BARROW_FAMILY_COURT", "Barrow Family Court"),
    Arguments.of("BASILDON_FAMILY_COURT", "Basildon Family Court"),
    Arguments.of("BASINGSTOKE_FAMILY_COURT", "Basingstoke Family Court"),
    Arguments.of("BATH_FAMILY_COURT", "Bath Family Court"),
    Arguments.of("BEDFORD_FAMILY_COURT", "Bedford Family Court"),
    Arguments.of("BIRKENHEAD_FAMILY_COURT", "Birkenhead Family Court"),
    Arguments.of("BIRMINGHAM_FAMILY_COURT", "Birmingham Family Court"),
    Arguments.of("BLACKBURN_FAMILY_COURT", "Blackburn Family Court"),
    Arguments.of("BLACKPOOL_FAMILY_COURT", "Blackpool Family Court"),
    Arguments.of("BLACKWOOD_FAMILY_COURT", "Blackwood Family Court"),
    Arguments.of("BODMIN_FAMILY_COURT", "Bodmin Family Court"),
    Arguments.of("BOSTON_FAMILY_COURT", "Boston Family Court"),
    Arguments.of("BOURNEMOUTH_FAMILY_COURT", "Bournemouth Family Court"),
    Arguments.of("BRADFORD_FAMILY_COURT", "Bradford Family Court"),
    Arguments.of("BRENTFORD_FAMILY_COURT", "Brentford Family Court"),
    Arguments.of("BRIGHTON_FAMILY_COURT", "Brighton Family Court"),
    Arguments.of("BRISTOL_FAMILY_COURT", "Bristol Family Court"),
    Arguments.of("BROMLEY_FAMILY_COURT", "Bromley Family Court"),
    Arguments.of("BURNLEY_FAMILY_COURT", "Burnley Family Court"),
    Arguments.of("BURY_ST_EDMONDS_FAMILY_COURT", "Bury St Edmonds Family Court"),
    Arguments.of("CAERNARFON_FAMILY_COURT", "Caernarfon Family Court"),
    Arguments.of("CAMBRIDGE_FAMILY_COURT", "Cambridge Family Court"),
    Arguments.of("CANTERBURY_FAMILY_COURT", "Canterbury Family Court"),
    Arguments.of("CARDIFF_FAMILY_COURT", "Cardiff Family Court"),
    Arguments.of("CARLISLE_FAMILY_COURT", "Carlisle Family Court"),
    Arguments.of("CARMARTHEN_HEARINGS_ONLY_FAMILY_COURT", "Carmarthen (hearings only) Family Court"),
    Arguments.of("CENTRAL_FAMILY_COURT", "Central Family Court"),
    Arguments.of("CENTRAL_LONDON_FAMILY_COURT", "Central London Family Court"),
    Arguments.of("CHELMSFORD_FAMILY_COURT", "Chelmsford Family Court"),
    Arguments.of("CHESTER_FAMILY_COURT", "Chester Family Court"),
    Arguments.of("CHESTERFIELD_FAMILY_COURT", "Chesterfield Family Court"),
    Arguments.of("CLERKENWELL_AND_SHOREDITCH_FAMILY_COURT", "Clerkenwell & Shoreditch Family Court"),
    Arguments.of("COURT_OF_PROTECTION_COURT_FAMILY_COURT", "Court of Protection Court Family Court"),
    Arguments.of("COVENTRY_FAMILY_COURT", "Coventry Family Court"),
    Arguments.of("CREWE_FAMILY_COURT", "Crewe Family Court"),
    Arguments.of("CROYDON_FAMILY_COURT", "Croydon Family Court"),
    Arguments.of("DARLINGTON_FAMILY_COURT", "Darlington Family Court"),
    Arguments.of("DARTFORD_FAMILY_COURT", "Dartford Family Court"),
    Arguments.of("DERBY_FAMILY_COURT", "Derby Family Court"),
    Arguments.of("DONCASTER_FAMILY_COURT", "Doncaster Family Court"),
    Arguments.of("DUDLEY_FAMILY_COURT", "Dudley Family Court"),
    Arguments.of("DURHAM_FAMILY_COURT", "Durham Family Court"),
    Arguments.of("EAST_LONDON_FAMILY_COURT", "East London Family Court"),
    Arguments.of("EDMONTON_FAMILY_COURT", "Edmonton Family Court"),
    Arguments.of("EXETER_FAMILY_COURT", "Exeter Family Court"),
    Arguments.of("GATESHEAD_FAMILY_COURT", "Gateshead Family Court"),
    Arguments.of("GLOUCESTER_FAMILY_COURT", "Gloucester Family Court"),
    Arguments.of("GRIMSBY_FAMILY_COURT", "Grimsby Family Court"),
    Arguments.of("GUILDFORD_FAMILY_COURT", "Guildford Family Court"),
    Arguments.of("HARROGATE_FAMILY_COURT", "Harrogate Family Court"),
    Arguments.of("HASTINGS_FAMILY_COURT", "Hastings Family Court"),
    Arguments.of("HAVERFORDWEST_FAMILY_COURT", "Haverfordwest Family Court"),
    Arguments.of("HEREFORD_FAMILY_COURT", "Hereford Family Court"),
    Arguments.of("HERTFORD_FAMILY_COURT", "Hertford Family Court"),
    Arguments.of("HIGH_WYCOMBE_FAMILY_COURT", "High Wycombe Family Court"),
    Arguments.of("HORSHAM_FAMILY_COURT", "Horsham Family Court"),
    Arguments.of("HUDDERSFIELD_FAMILY_COURT", "Huddersfield Family Court"),
    Arguments.of("IPSWICH_FAMILY_COURT", "Ipswich Family Court"),
    Arguments.of("KINGSTON_UPON_HULL_FAMILY_COURT", "Kingston Upon Hull Family Court"),
    Arguments.of("KINGSTON_UPON_THAMES_FAMILY_COURT", "Kingston upon Thames Family Court"),
    Arguments.of("LANCASTER_FAMILY_COURT", "Lancaster Family Court"),
    Arguments.of("LEEDS_FAMILY_COURT", "Leeds Family Court"),
    Arguments.of("LEICESTER_FAMILY_COURT", "Leicester Family Court"),
    Arguments.of("LEWES_FAMILY_COURT", "Lewes Family Court"),
    Arguments.of("LINCOLN_FAMILY_COURT", "Lincoln Family Court"),
    Arguments.of("LIVERPOOL_FAMILY_COURT", "Liverpool Family Court"),
    Arguments.of("LLANDRINDOD_WELLS_HEARINGS_ONLY_FAMILY_COURT", "Llandrindod Wells (hearings only) Family Court"),
    Arguments.of("LLANELLI_FAMILY_COURT", "Llanelli Family Court"),
    Arguments.of("LUTON_FAMILY_COURT", "Luton Family Court"),
    Arguments.of("MAIDSTONE_FAMILY_COURT", "Maidstone Family Court"),
    Arguments.of("MANCHESTER_FAMILY_COURT", "Manchester Family Court"),
    Arguments.of("MANSFIELD__FAMILY_COURT", "Mansfield  Family Court"),
    Arguments.of("MAYORS_AND_CITY_OF_LONDON_FAMILY_COURT", "Mayors & City of London Family Court"),
    Arguments.of("MEDWAY_FAMILY_COURT", "Medway Family Court"),
    Arguments.of("MERTHYR_FAMILY_COURT", "Merthyr Family Court"),
    Arguments.of("MILTON_KEYNES_FAMILY_COURT", "Milton Keynes Family Court"),
    Arguments.of("MOLD_HEARINGS_ONLY__FAMILY_COURT", "Mold (hearings only)  Family Court"),
    Arguments.of("NEWCASTLE_FAMILY_COURT", "Newcastle Family Court"),
    Arguments.of("NEWPORT_IOW_FAMILY_COURT", "Newport (IOW) Family Court"),
    Arguments.of("NEWPORT_SOUTH_WALES__FAMILY_COURT", "Newport (South Wales)  Family Court"),
    Arguments.of("NORTH_SHIELDS_FAMILY_COURT", "North Shields Family Court"),
    Arguments.of("NORTHAMPTON_FAMILY_COURT", "Northampton Family Court"),
    Arguments.of("NORWICH_FAMILY_COURT", "Norwich Family Court"),
    Arguments.of("NOTTINGHAM_FAMILY_COURT", "Nottingham Family Court"),
    Arguments.of("NUNEATON_FAMILY_COURT", "Nuneaton Family Court"),
    Arguments.of("OXFORD_FAMILY_COURT", "Oxford Family Court"),
    Arguments.of("PETERBOROUGH_FAMILY_COURT", "Peterborough Family Court"),
    Arguments.of("PLYMOUTH_FAMILY_COURT", "Plymouth Family Court"),
    Arguments.of("PONTYPRIDD_FAMILY_COURT", "Pontypridd Family Court"),
    Arguments.of("PORT_TALBOT_FAMILY_COURT", "Port Talbot Family Court"),
    Arguments.of("PORTSMOUTH_FAMILY_COURT", "Portsmouth Family Court"),
    Arguments.of("PRESTATYN_FAMILY_COURT", "Prestatyn Family Court"),
    Arguments.of("PRESTON_FAMILY_COURT", "Preston Family Court"),
    Arguments.of("READING_FAMILY_COURT", "Reading Family Court"),
    Arguments.of("ROMFORD_FAMILY_COURT", "Romford Family Court"),
    Arguments.of("SALISBURY_FAMILY_COURT", "Salisbury Family Court"),
    Arguments.of("SCARBOROUGH_FAMILY_COURT", "Scarborough Family Court"),
    Arguments.of("SHEFFIELD_FAMILY_COURT", "Sheffield Family Court"),
    Arguments.of("SKIPTON_FAMILY_COURT", "Skipton Family Court"),
    Arguments.of("SLOUGH_FAMILY_COURT", "Slough Family Court"),
    Arguments.of("SOUTH_SHIELDS_FAMILY_COURT", "South Shields Family Court"),
    Arguments.of("SOUTHAMPTON_FAMILY_COURT", "Southampton Family Court"),
    Arguments.of("SOUTHEND_FAMILY_COURT", "Southend Family Court"),
    Arguments.of("ST_HELENS_FAMILY_COURT", "St Helens Family Court"),
    Arguments.of("STAINES_FAMILY_COURT", "Staines Family Court"),
    Arguments.of("STOCKPORT_FAMILY_COURT", "Stockport Family Court"),
    Arguments.of("STOKE_ON_TRENT_FAMILY_COURT", "Stoke on Trent Family Court"),
    Arguments.of("SUNDERLAND_FAMILY_COURT", "Sunderland Family Court"),
    Arguments.of("SWANSEA_FAMILY_COURT", "Swansea Family Court"),
    Arguments.of("SWINDON_FAMILY_COURT", "Swindon Family Court"),
    Arguments.of("TAUNTON_FAMILY_COURT", "Taunton Family Court"),
    Arguments.of("TEESIDE_FAMILY_COURT", "Teeside Family Court"),
    Arguments.of("TELFORD_FAMILY_COURT", "Telford Family Court"),
    Arguments.of("THANET_FAMILY_COURT", "Thanet Family Court"),
    Arguments.of("TORQUAY_AND_NEWTON_ABBOTT_FAMILY_COURT", "Torquay & Newton Abbott Family Court"),
    Arguments.of("TRURO_FAMILY_COURT", "Truro Family Court"),
    Arguments.of("UXBRIDGE_FAMILY_COURT", "Uxbridge Family Court"),
    Arguments.of("WAKEFIELD_FAMILY_COURT", "Wakefield Family Court"),
    Arguments.of("WALSALL_FAMILY_COURT", "Walsall Family Court"),
    Arguments.of("WANDSWORTH_FAMILY_COURT", "Wandsworth Family Court"),
    Arguments.of("WARWICK_FAMILY_COURT", "Warwick Family Court"),
    Arguments.of("WATFORD_FAMILY_COURT", "Watford Family Court"),
    Arguments.of("WELSHPOOL_HEARINGS_ONLY_FAMILY_COURT", "Welshpool (hearings only) Family Court"),
    Arguments.of("WEST_CUMBRIA_AKA_WORKINGTON_FAMILY_COURT", "West Cumbria (aka Workington) Family Court"),
    Arguments.of("WEST_LONDON_FAMILY_COURT", "West London Family Court"),
    Arguments.of("WESTON_SUPER_MARE_FAMILY_COURT", "Weston Super Mare Family Court"),
    Arguments.of("WEYMOUTH_FAMILY_COURT", "Weymouth Family Court"),
    Arguments.of("WIGAN_FAMILY_COURT", "Wigan Family Court"),
    Arguments.of("WILLESDEN_FAMILY_COURT", "Willesden Family Court"),
    Arguments.of("WINCHESTER_FAMILY_COURT", "Winchester Family Court"),
    Arguments.of("WOLVERHAMPTON_FAMILY_COURT", "Wolverhampton Family Court"),
    Arguments.of("WORCESTER_FAMILY_COURT", "Worcester Family Court"),
    Arguments.of("WORTHING_FAMILY_COURT", "Worthing Family Court"),
    Arguments.of("WREXHAM_FAMILY_COURT", "Wrexham Family Court"),
    Arguments.of("YEOVIL_FAMILY_COURT", "Yeovil Family Court"),
    Arguments.of("YORK_FAMILY_COURT", "York Family Court"),
  )
}
