package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.model.fms.argumentsProvider

import org.junit.jupiter.api.extension.ExtensionContext
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.ArgumentsProvider
import java.util.stream.Stream

class MagistratesCourtArgumentsProvider : ArgumentsProvider {
  override fun provideArguments(context: ExtensionContext?): Stream<out Arguments?>? = Stream.of(
    Arguments.of("ABERDARE_MAGISTRATES_COURT", "Aberdare Magistrates Court"),
    Arguments.of("ABERGAVENNY_MAGISTRATES_COURT", "Abergavenny Magistrates Court"),
    Arguments.of("ABERTILLERY_MAGISTRATES_COURT", "Abertillery Magistrates Court"),
    Arguments.of("ABERYSTWYTH_MAGISTRATES_COURT", "Aberystwyth Magistrates Court"),
    Arguments.of("ACCRINGTON_MAGISTRATES_COURT", "Accrington Magistrates Court"),
    Arguments.of("ACTON_MAGISTRATES_COURT", "Acton Magistrates Court"),
    Arguments.of("AIT_STOKE_ON_TRENT_MAGISTRATES_COURT", "AIT Stoke-on-Trent Magistrates Court"),
    Arguments.of("ALDERSHOT_MAGISTRATES_COURT", "Aldershot Magistrates Court"),
    Arguments.of("ALNWICK_MAGISTRATES_COURT", "Alnwick Magistrates Court"),
    Arguments.of("ALTON_MAGISTRATES_COURT", "Alton Magistrates Court"),
    Arguments.of("AMERSHAM_MAGISTRATES_COURT", "Amersham Magistrates Court"),
    Arguments.of("AMMANFORD_MAGISTRATES_COURT", "Ammanford Magistrates Court"),
    Arguments.of("ANDOVER_MAGISTRATES_COURT", "Andover Magistrates Court"),
    Arguments.of("ASHFORD_MAGISTRATES_COURT", "Ashford Magistrates Court"),
    Arguments.of("ATHERSTONE_MAGISTRATES_COURT", "Atherstone Magistrates Court"),
    Arguments.of("AYLESBURY_MAGISTRATES_COURT", "Aylesbury Magistrates Court"),
    Arguments.of("BANBURY_MAGISTRATES_COURT", "Banbury Magistrates Court"),
    Arguments.of("BANGOR_MAGISTRATES_COURT", "Bangor Magistrates Court"),
    Arguments.of("BARKINGSIDE_MAGISTRATES_COURT", "Barkingside Magistrates Court"),
    Arguments.of("BARNET_MAGISTRATES_COURT", "Barnet Magistrates Court"),
    Arguments.of("BARNSLEY_MAGISTRATES_COURT", "Barnsley Magistrates Court"),
    Arguments.of("BARNSTAPLE_MAGISTRATES_COURT", "Barnstaple Magistrates Court"),
    Arguments.of("BARROW_IN_FURNESS_MAGISTRATES_COURT", "Barrow-in-Furness Magistrates Court"),
    Arguments.of("BARRY_MAGISTRATES_COURT", "Barry Magistrates Court"),
    Arguments.of("BASILDON_MAGISTRATES_COURT", "Basildon Magistrates Court"),
    Arguments.of("BASINGSTOKE_MAGISTRATES_COURT", "Basingstoke Magistrates Court"),
    Arguments.of("BATH_MAGISTRATES_COURT", "Bath Magistrates Court"),
    Arguments.of("BEDFORD_MAGISTRATES_COURT", "Bedford Magistrates Court"),
    Arguments.of("BEDLINGTON_MAGISTRATES_COURT", "Bedlington Magistrates Court"),
    Arguments.of("BELMARSH_MAGISTRATES_COURT", "Belmarsh Magistrates Court"),
    Arguments.of("BERWICK_UPON_TWEED_MAGISTRATES_COURT", "Berwick upon Tweed Magistrates Court"),
    Arguments.of("BEVERLEY_MAGISTRATES_COURT", "Beverley Magistrates Court"),
    Arguments.of("BEXLEY_MAGISTRATES_COURT", "Bexley Magistrates Court"),
    Arguments.of("BICESTER_MAGISTRATES_COURT", "Bicester Magistrates Court"),
    Arguments.of("BINGLEY_MAGISTRATES_COURT", "Bingley Magistrates Court"),
    Arguments.of("BIRKENHEAD_MAGISTRATES_COURT", "Birkenhead Magistrates Court"),
    Arguments.of("BIRMINGHAM_MAGISTRATES_COURT", "Birmingham Magistrates Court"),
    Arguments.of("BISHOP_AUCKLAND_MAGISTRATES_COURT", "Bishop Auckland Magistrates Court"),
    Arguments.of("BLACKBURN_MAGISTRATES_COURT", "Blackburn Magistrates Court"),
    Arguments.of("BLACKPOOL_MAGISTRATES_AND_CIVIL_COURT", "Blackpool Magistrates and Civil Court "),
    Arguments.of("BLACKPOOL_MAGISTRATES_COURT", "Blackpool Magistrates Court"),
    Arguments.of("BLACKWOOD_MAGISTRATES_COURT", "Blackwood Magistrates Court"),
    Arguments.of("BLANDFORD_FORUM_MAGISTRATES_COURT", "Blandford Forum Magistrates Court"),
    Arguments.of("BLANDFORD_MAGISTRATES_COURT", "Blandford Magistrates Court"),
    Arguments.of("BLAYDON_MAGISTRATES_COURT", "Blaydon Magistrates Court"),
    Arguments.of("BODMIN_MAGISTRATES_COURT", "Bodmin Magistrates Court"),
    Arguments.of("BOLTON_MAGISTRATES_COURT", "Bolton Magistrates Court"),
    Arguments.of("BOOTLE_MAGISTRATES_COURT", "Bootle Magistrates Court"),
    Arguments.of("BOSTON_MAGISTRATES_COURT", "Boston Magistrates Court"),
    Arguments.of("BOURNE_MAGISTRATES_COURT", "Bourne Magistrates Court"),
    Arguments.of("BOURNEMOUTH_MAGISTRATES_COURT", "Bournemouth Magistrates Court"),
    Arguments.of("BOW_STREET_MAGISTRATES_COURT", "Bow Street Magistrates Court"),
    Arguments.of("BRACKNELL_MAGISTRATES_COURT", "Bracknell Magistrates Court"),
    Arguments.of("BRADFORD_AND_KEIGHLEY_MAGISTRATES_COURT", "Bradford and Keighley Magistrates Court"),
    Arguments.of("BRADFORD_MAGISTRATES_COURT", "Bradford Magistrates Court"),
    Arguments.of("BRECON_MAGISTRATES_COURT", "Brecon Magistrates Court"),
    Arguments.of("BRENT_MAGISTRATES_COURT", "Brent Magistrates Court"),
    Arguments.of("BRENTFORD_MAGISTRATES_COURT", "Brentford Magistrates Court"),
    Arguments.of("BRIDGEND_MAGISTRATES_COURT", "Bridgend Magistrates Court"),
    Arguments.of("BRIDGNORTH_MAGISTRATES_COURT", "Bridgnorth Magistrates Court"),
    Arguments.of("BRIDGWATER_MAGISTRATES_COURT", "Bridgwater Magistrates Court"),
    Arguments.of("BRIDLINGTON_MAGISTRATES_COURT", "Bridlington Magistrates Court"),
    Arguments.of("BRIDPORT_MAGISTRATES_COURT", "Bridport Magistrates Court"),
    Arguments.of("BRIGHTON_MAGISTRATES_COURT", "Brighton Magistrates Court"),
    Arguments.of("BRISTOL_MAGISTRATES_COURT", "Bristol Magistrates Court"),
    Arguments.of("BROMLEY_MAGISTRATES_COURT", "Bromley Magistrates Court"),
    Arguments.of("BURNLEY_MAGISTRATES_COURT", "Burnley Magistrates Court"),
    Arguments.of("BURTON_UPON_TRENT_MAGISTRATES_COURT", "Burton upon Trent Magistrates Court"),
    Arguments.of("BURY_MAGISTRATES_COURT", "Bury Magistrates Court"),
    Arguments.of("BURY_ST_EDMUNDS_MAGISTRATES_COURT", "Bury St Edmunds Magistrates Court"),
    Arguments.of("BUXTON_MAGISTRATES_COURT", "Buxton Magistrates Court"),
    Arguments.of("CAERNARFON_MAGISTRATES_COURT", "Caernarfon Magistrates Court"),
    Arguments.of("CAERPHILLY_MAGISTRATES_COURT", "Caerphilly Magistrates Court"),
    Arguments.of("CAISTOR_MAGISTRATES_COURT", "Caistor Magistrates Court"),
    Arguments.of("CAMBERLEY_MAGISTRATES_COURT", "Camberley Magistrates Court"),
    Arguments.of("CAMBERWELL_GREEN_MAGISTRATES_COURT", "Camberwell Green Magistrates Court"),
    Arguments.of("CAMBORNE_MAGISTRATES_COURT", "Camborne Magistrates Court"),
    Arguments.of("CAMBRIDGE_MAGISTRATES_COURT", "Cambridge Magistrates Court"),
    Arguments.of("CANNOCK_MAGISTRATES_COURT", "Cannock Magistrates Court"),
    Arguments.of("CANTERBURY_MAGISTRATES_COURT", "Canterbury Magistrates Court"),
    Arguments.of("CARDIFF_MAGISTRATES_COURT", "Cardiff Magistrates Court"),
    Arguments.of("CARDIGAN_MAGISTRATES_COURT", "Cardigan Magistrates Court"),
    Arguments.of("CARLISLE_MAGISTRATES_COURT", "Carlisle Magistrates Court"),
    Arguments.of("CARMARTHEN_MAGISTRATES_COURT", "Carmarthen Magistrates Court"),
    Arguments.of("CASTLEFORD_MAGISTRATES_COURT", "Castleford Magistrates Court"),
    Arguments.of("CHATHAM_MAGISTRATES_COURT", "Chatham Magistrates Court"),
    Arguments.of("CHELMSFORD_MAGISTRATES_COURT", "Chelmsford Magistrates Court"),
    Arguments.of("CHELTENHAM_MAGISTRATES_COURT", "Cheltenham Magistrates Court"),
    Arguments.of("CHEPSTOW_MAGISTRATES_COURT", "Chepstow Magistrates Court"),
    Arguments.of("CHESHUNT_MAGISTRATES_COURT", "Cheshunt Magistrates Court"),
    Arguments.of("CHESTER_LE_STREET_MAGISTRATES_COURT", "Chester le Street Magistrates Court"),
    Arguments.of("CHESTER_MAGISTRATES_COURT", "Chester Magistrates Court"),
    Arguments.of("CHICHESTER_MAGISTRATES_COURT", "Chichester Magistrates Court"),
    Arguments.of("CHORLEY_MAGISTRATES_COURT", "Chorley Magistrates Court"),
    Arguments.of("CIRENCESTER_MAGISTRATES_COURT", "Cirencester Magistrates Court"),
    Arguments.of("CITY_OF_LONDON_MAGISTRATES_COURT", "City of London Magistrates Court"),
    Arguments.of("COALVILLE_MAGISTRATES_COURT", "Coalville Magistrates Court"),
    Arguments.of("COLCHESTER_MAGISTRATES_COURT", "Colchester Magistrates Court"),
    Arguments.of("COLEFORD_MAGISTRATES_COURT", "Coleford Magistrates Court"),
    Arguments.of("CONSETT_MAGISTRATES_COURT", "Consett Magistrates Court"),
    Arguments.of("CORBY_MAGISTRATES_COURT", "Corby Magistrates Court"),
    Arguments.of("COVENTRY_MAGISTRATES_COURT", "Coventry Magistrates Court"),
    Arguments.of("CRAWLEY_MAGISTRATES_COURT", "Crawley Magistrates Court"),
    Arguments.of("CREWE_SOUTH_CHESHIRE_MAGISTRATES_COURT", "Crewe (South Cheshire) Magistrates Court"),
    Arguments.of("CREWE_MAGISTRATES_COURT", "Crewe Magistrates Court"),
    Arguments.of("CROMER_MAGISTRATES_COURT", "Cromer Magistrates Court"),
    Arguments.of("CROYDON_MAGISTRATES_COURT", "Croydon Magistrates Court"),
    Arguments.of("CULLOMPTON_MAGISTRATES_COURT", "Cullompton Magistrates Court"),
    Arguments.of("CWMBRAN_MAGISTRATES_COURT", "Cwmbran Magistrates Court"),
    Arguments.of("DARLINGTON_MAGISTRATES_COURT", "Darlington Magistrates Court"),
    Arguments.of("DARTFORD_MAGISTRATES_COURT", "Dartford Magistrates Court"),
    Arguments.of("DAVENTRY_MAGISTRATES_COURT", "Daventry Magistrates Court"),
    Arguments.of("DENBIGH_MAGISTRATES_COURT", "Denbigh Magistrates Court"),
    Arguments.of("DERBY_MAGISTRATES_COURT", "Derby Magistrates Court"),
    Arguments.of("DEVIZES_MAGISTRATES_COURT", "Devizes Magistrates Court"),
    Arguments.of("DEWSBURY_MAGISTRATES_COURT", "Dewsbury Magistrates Court"),
    Arguments.of("DIDCOT_MAGISTRATES_COURT", "Didcot Magistrates Court"),
    Arguments.of("DOLGELLAU_MAGISTRATES_COURT", "Dolgellau Magistrates Court"),
    Arguments.of("DONCASTER_MAGISTRATES_COURT", "Doncaster Magistrates Court"),
    Arguments.of("DORCHESTER_MAGISTRATES_COURT", "Dorchester Magistrates Court"),
    Arguments.of("DORKING_MAGISTRATES_COURT", "Dorking Magistrates Court"),
    Arguments.of("DOVER_MAGISTRATES_COURT", "Dover Magistrates Court"),
    Arguments.of("DROITWICH_MAGISTRATES_COURT", "Droitwich Magistrates Court"),
    Arguments.of("DUDLEY_MAGISTRATES_COURT", "Dudley Magistrates Court"),
    Arguments.of("DURHAM_MAGISTRATES_COURT", "Durham Magistrates Court"),
    Arguments.of("EALING_MAGISTRATES_COURT", "Ealing Magistrates Court"),
    Arguments.of("EAST_BERKSHIRE_MAGISTRATES_COURT_SLOUGH", "East Berkshire Magistrates Court, Slough"),
    Arguments.of("EASTBOURNE_MAGISTRATES_COURT", "Eastbourne Magistrates Court"),
    Arguments.of("EASTLEIGH_MAGISTRATES_COURT", "Eastleigh Magistrates Court"),
    Arguments.of("ELY_MAGISTRATES_COURT", "Ely Magistrates Court"),
    Arguments.of("ENFIELD_MAGISTRATES_COURT", "Enfield Magistrates Court"),
    Arguments.of("EPPING_MAGISTRATES_COURT", "Epping Magistrates Court"),
    Arguments.of("EPSOM_MAGISTRATES_COURT", "Epsom Magistrates Court"),
    Arguments.of("EVESHAM_MAGISTRATES_COURT", "Evesham Magistrates Court"),
    Arguments.of("EXETER_MAGISTRATES_COURT", "Exeter Magistrates Court"),
    Arguments.of("FAREHAM_MAGISTRATES_COURT", "Fareham Magistrates Court"),
    Arguments.of("FELTHAM_MAGISTRATES_COURT", "Feltham Magistrates Court"),
    Arguments.of("FLAX_BOURTON_MAGISTRATES_COURT", "Flax Bourton Magistrates Court"),
    Arguments.of("FLEETWOOD_MAGISTRATES_COURT", "Fleetwood Magistrates Court"),
    Arguments.of("FLINT_MAGISTRATES_COURT", "Flint Magistrates Court"),
    Arguments.of("FOLKESTONE_MAGISTRATES_COURT", "Folkestone Magistrates Court"),
    Arguments.of("FROME_MAGISTRATES_COURT", "Frome Magistrates Court"),
    Arguments.of("GAINSBOROUGH_MAGISTRATES_COURT", "Gainsborough Magistrates Court"),
    Arguments.of("GATESHEAD_MAGISTRATES_COURT", "Gateshead Magistrates Court"),
    Arguments.of("GLOSSOP_MAGISTRATES_COURT", "Glossop Magistrates Court"),
    Arguments.of("GLOUCESTER_MAGISTRATES_COURT", "Gloucester Magistrates Court"),
    Arguments.of("GOOLE_MAGISTRATES_COURT", "Goole Magistrates Court"),
    Arguments.of("GOSFORTH_MAGISTRATES_COURT", "Gosforth Magistrates Court"),
    Arguments.of("GOWERTON_MAGISTRATES_COURT", "Gowerton Magistrates Court"),
    Arguments.of("GRANTHAM_MAGISTRATES_COURT", "Grantham Magistrates Court"),
    Arguments.of("GRAYS_MAGISTRATES_COURT", "Grays Magistrates Court"),
    Arguments.of("GREAT_YARMOUTH_MAGISTRATES_COURT", "Great Yarmouth Magistrates Court"),
    Arguments.of("GREENWICH_MAGISTRATES_COURT", "Greenwich Magistrates Court"),
    Arguments.of("GRIMSBY_MAGISTRATES_COURT", "Grimsby Magistrates Court"),
    Arguments.of("GUILDFORD_MAGISTRATES_COURT", "Guildford Magistrates Court"),
    Arguments.of("GUISBOROUGH_MAGISTRATES_COURT", "Guisborough Magistrates Court"),
    Arguments.of("HALESOWEN_MAGISTRATES_COURT", "Halesowen Magistrates Court"),
    Arguments.of("HALIFAX_MAGISTRATES_COURT", "Halifax Magistrates Court"),
    Arguments.of("HAMMERSMITH_MAGISTRATES_COURT", "Hammersmith Magistrates Court"),
    Arguments.of("HARLOW_MAGISTRATES_COURT", "Harlow Magistrates Court"),
    Arguments.of("HARROGATE_MAGISTRATES_COURT", "Harrogate Magistrates Court"),
    Arguments.of("HARROW_MAGISTRATES_COURT", "Harrow Magistrates Court"),
    Arguments.of("HARTLEPOOL_MAGISTRATES_COURT", "Hartlepool Magistrates Court"),
    Arguments.of("HARWICH_MAGISTRATES_COURT", "Harwich Magistrates Court"),
    Arguments.of("HASTINGS_MAGISTRATES_COURT", "Hastings Magistrates Court"),
    Arguments.of("HATFIELD_MAGISTRATES_COURT", "Hatfield Magistrates Court"),
    Arguments.of("HAVANT_MAGISTRATES_COURT", "Havant Magistrates Court"),
    Arguments.of("HAVERFORDWEST_MAGISTRATES_COURT", "Haverfordwest Magistrates Court"),
    Arguments.of("HAYWARDS_HEATH_MAGISTRATES_COURT", "Haywards Heath Magistrates Court"),
    Arguments.of("HEMEL_HEMPSTEAD_MAGISTRATES_COURT", "Hemel Hempstead Magistrates Court"),
    Arguments.of("HENDON_MAGISTRATES_COURT", "Hendon Magistrates Court"),
    Arguments.of("HERTFORD_MAGISTRATES_COURT", "Hertford Magistrates Court"),
    Arguments.of("HEXHAM_MAGISTRATES_COURT", "Hexham Magistrates Court"),
    Arguments.of("HIGH_WYCOMBE_MAGISTRATES_COURT", "High Wycombe Magistrates Court"),
    Arguments.of("HIGHBURY_CORNER_MAGISTRATES_COURT", "Highbury Corner Magistrates Court"),
    Arguments.of("HIGHGATE_MAGISTRATES_COURT", "Highgate Magistrates Court"),
    Arguments.of("HINCKLEY_MAGISTRATES_COURT", "Hinckley Magistrates Court"),
    Arguments.of("HOLYHEAD_MAGISTRATES_COURT", "Holyhead Magistrates Court"),
    Arguments.of("HONITON_MAGISTRATES_COURT", "Honiton Magistrates Court"),
    Arguments.of("HORNCASTLE_MAGISTRATES_COURT", "Horncastle Magistrates Court"),
    Arguments.of("HORSEFERRY_ROAD_MAGISTRATES_COURT", "Horseferry Road Magistrates Court"),
    Arguments.of("HORSHAM_MAGISTRATES_COURT", "Horsham Magistrates Court"),
    Arguments.of("HOUGHTON_LE_SPRING_MAGISTRATES_COURT", "Houghton le Spring Magistrates Court"),
    Arguments.of("HUDDERSFIELD_MAGISTRATES_COURT", "Huddersfield Magistrates Court"),
    Arguments.of("HULL_AND_HOLDERNESS_MAGISTRATES_COURT", "Hull and Holderness Magistrates Court"),
    Arguments.of("HUNTINGDON_MAGISTRATES_COURT", "Huntingdon Magistrates Court"),
    Arguments.of("HUYTON_MAGISTRATES_COURT", "Huyton Magistrates Court"),
    Arguments.of("ILKESTON_MAGISTRATES_COURT", "Ilkeston Magistrates Court"),
    Arguments.of("IPSWICH_MAGISTRATES_COURT", "Ipswich Magistrates Court"),
    Arguments.of("ISLES_OF_SCILLY_MAGISTRATES_COURT", "Isles of Scilly Magistrates Court"),
    Arguments.of("KENDAL_MAGISTRATES_COURT", "Kendal Magistrates Court"),
    Arguments.of("KETTERING_MAGISTRATES_COURT", "Kettering Magistrates Court"),
    Arguments.of("KIDDERMINSTER_MAGISTRATES_COURT", "Kidderminster Magistrates Court"),
    Arguments.of("KINGS_LYNN_MAGISTRATES_COURT", "Kings Lynn Magistrates Court"),
    Arguments.of("KINGSTON_UPON_HULL_MAGISTRATES_COURT", "Kingston upon Hull Magistrates Court"),
    Arguments.of("KINGSTON_UPON_THAMES_MAGISTRATES_COURT", "Kingston upon Thames Magistrates Court"),
    Arguments.of("KIRKLEES_HUDDERSFIELD_MAGISTRATES_COURT", "Kirklees (Huddersfield) Magistrates Court"),
    Arguments.of("KNOWSLEY_MAGISTRATES_COURT", "Knowsley Magistrates Court"),
    Arguments.of("LANCASTER_MAGISTRATES_COURT", "Lancaster Magistrates Court"),
    Arguments.of("LAUNCESTON_MAGISTRATES_COURT", "Launceston Magistrates Court"),
    Arguments.of("LAVENDER_HILL_MAGISTRATES_COURT", "Lavender Hill Magistrates Court"),
    Arguments.of("LEAMINGTON_SPA_MAGISTRATES_COURT", "Leamington Spa Magistrates Court"),
    Arguments.of("LEEDS_MAGISTRATES_COURT", "Leeds Magistrates Court"),
    Arguments.of("LEICESTER_MAGISTRATES_COURT", "Leicester Magistrates Court"),
    Arguments.of("LEWES_MAGISTRATES_COURT", "Lewes Magistrates Court"),
    Arguments.of("LEYLAND_MAGISTRATES_COURT", "Leyland Magistrates Court"),
    Arguments.of("LINCOLN_MAGISTRATES_COURT", "Lincoln Magistrates Court"),
    Arguments.of("LISKEARD_MAGISTRATES_COURT", "Liskeard Magistrates Court"),
    Arguments.of("LIVERPOOL_AND_KNOWSLEY_MAGISTRATES_COURT", "Liverpool & Knowsley Magistrates Court"),
    Arguments.of("LLANDOVERY_MAGISTRATES_COURT", "Llandovery Magistrates Court"),
    Arguments.of("LLANDRINDOD_WELLS_MAGISTRATES_COURT", "Llandrindod Wells Magistrates Court"),
    Arguments.of("LLANDUDNO_MAGISTRATES_COURT", "Llandudno Magistrates Court"),
    Arguments.of("LLANELLI_MAGISTRATES_COURT", "Llanelli Magistrates Court"),
    Arguments.of("LLANGEFNI_MAGISTRATES_COURT", "Llangefni Magistrates Court"),
    Arguments.of("LLANTRISANT_MAGISTRATES_COURT", "Llantrisant Magistrates Court"),
    Arguments.of("LLWYNYPIA_MAGISTRATES_COURT", "Llwynypia Magistrates Court"),
    Arguments.of("LONG_SUTTON_MAGISTRATES_COURT", "Long Sutton Magistrates Court"),
    Arguments.of("LOUGHBOROUGH_MAGISTRATES_COURT", "Loughborough Magistrates Court"),
    Arguments.of("LOUTH_MAGISTRATES_COURT", "Louth Magistrates Court"),
    Arguments.of("LOWESTOFT_MAGISTRATES_COURT", "Lowestoft Magistrates Court"),
    Arguments.of("LUDLOW_MAGISTRATES_COURT", "Ludlow Magistrates Court"),
    Arguments.of("LUTON_AND_SOUTH_BEDFORDSHIRE_MAGISTRATES_COURT", "Luton and South Bedfordshire Magistrates Court"),
    Arguments.of("LUTON_MAGISTRATES_COURT", "Luton Magistrates Court"),
    Arguments.of("LYNDHURST_MAGISTRATES_COURT", "Lyndhurst Magistrates Court"),
    Arguments.of("MACHYNLLETH_MAGISTRATES_COURT", "Machynlleth Magistrates Court"),
    Arguments.of("MAIDENHEAD_MAGISTRATES_COURT", "Maidenhead Magistrates Court"),
    Arguments.of("MAIDSTONE_MAGISTRATES_COURT", "Maidstone Magistrates Court"),
    Arguments.of("MANCHESTER_CROWN_SQUARE_MAGISTRATES_COURT", "Manchester (Crown Square) Magistrates Court"),
    Arguments.of(
      "MANCHESTER_CIVIL_JUSTICE_CENTRE_MAGISTRATES_COURT",
      "Manchester Civil Justice Centre Magistrates Court",
    ),
    Arguments.of("MANCHESTER_MAGISTRATES_COURT", "Manchester Magistrates Court"),
    Arguments.of("MANSFIELD_ROSEMARY_ST_MAGISTRATES_COURT", "Mansfield (Rosemary St) Magistrates Court"),
    Arguments.of("MARGATE_MAGISTRATES_COURT", "Margate Magistrates Court"),
    Arguments.of("MARKET_DRAYTON_MAGISTRATES_COURT", "Market Drayton Magistrates Court"),
    Arguments.of("MARKET_HARBOROUGH_MAGISTRATES_COURT", "Market Harborough Magistrates Court"),
    Arguments.of("MEDWAY_MAGISTRATES_COURT", "Medway Magistrates Court"),
    Arguments.of("MELTON_MOWBRAY_MAGISTRATES_COURT", "Melton Mowbray Magistrates Court"),
    Arguments.of("MERTHYR_TYDFIL_MAGISTRATES_COURT", "Merthyr Tydfil Magistrates Court"),
    Arguments.of("MIDDLESBROUGH_TEESSIDE_MAGISTRATES_COURT", "Middlesbrough (Teesside) Magistrates Court"),
    Arguments.of("MILDENHALL_MAGISTRATES_COURT", "Mildenhall Magistrates Court"),
    Arguments.of("MILTON_KEYNES_MAGISTRATES_COURT", "Milton Keynes Magistrates Court"),
    Arguments.of("MINEHEAD_MAGISTRATES_COURT", "Minehead Magistrates Court"),
    Arguments.of("MOLD_MAGISTRATES_COURT", "Mold Magistrates Court"),
    Arguments.of("NEATH_MAGISTRATES_COURT", "Neath Magistrates Court"),
    Arguments.of("NEWARK_MAGISTRATES_COURT", "Newark Magistrates Court"),
    Arguments.of("NEWBURY_MAGISTRATES_COURT", "Newbury Magistrates Court"),
    Arguments.of("NEWCASTLE_MAGISTRATES_COURT", "Newcastle Magistrates Court"),
    Arguments.of("NEWCASTLE_UPON_TYNE_MAGISTRATES_COURT", "Newcastle Upon Tyne Magistrates Court"),
    Arguments.of("NEWPORT_SOUTH_WALES_MAGISTRATES_COURT", "Newport (South Wales) Magistrates Court"),
    Arguments.of("NEWPORT_MAGISTRATES_COURT", "Newport Magistrates Court"),
    Arguments.of("NEWTON_ABBOT_MAGISTRATES_COURT", "Newton Abbot Magistrates Court"),
    Arguments.of("NEWTON_AYCLIFFE_MAGISTRATES_COURT", "Newton Aycliffe Magistrates Court"),
    Arguments.of("NEWTON_MAGISTRATES_COURT", "Newton Magistrates Court"),
    Arguments.of("NEWTOWN_MAGISTRATES_COURT", "Newtown Magistrates Court"),
    Arguments.of("NORTH_SHIELDS_MAGISTRATES_COURT", "North Shields Magistrates Court"),
    Arguments.of("NORTH_SOMERSET_MAGISTRATES_COURT", "North Somerset Magistrates Court"),
    Arguments.of(
      "NORTH_STAFFORDSHIRE_JUSTICE_CENTRE_MAGISTRATES_COURT",
      "North Staffordshire Justice Centre Magistrates Court",
    ),
    Arguments.of("NORTH_TYNESIDE_MAGISTRATES_COURT", "North Tyneside Magistrates Court"),
    Arguments.of("NORTHALLERTON_MAGISTRATES_COURT", "Northallerton Magistrates Court"),
    Arguments.of("NORTHAMPTON_MAGISTRATES_COURT", "Northampton Magistrates Court"),
    Arguments.of("NORTHWICH_MAGISTRATES_COURT", "Northwich Magistrates Court"),
    Arguments.of("NORWICH_MAGISTRATES_COURT", "Norwich Magistrates Court"),
    Arguments.of("NOTTINGHAM_MAGISTRATES_COURT", "Nottingham Magistrates Court"),
    Arguments.of("NUNEATON_MAGISTRATES_COURT", "Nuneaton Magistrates Court"),
    Arguments.of("NUNEATON_VICARAGE_ST_MAGISTRATES_COURT", "Nuneaton, Vicarage St Magistrates Court"),
    Arguments.of("OAKHAM_MAGISTRATES_COURT", "Oakham Magistrates Court"),
    Arguments.of("OKEHAMPTON_MAGISTRATES_COURT", "Okehampton Magistrates Court"),
    Arguments.of("OLDHAM_MAGISTRATES_COURT", "Oldham Magistrates Court"),
    Arguments.of("ORMSKIRK_MAGISTRATES_COURT", "Ormskirk Magistrates Court"),
    Arguments.of("OSWESTRY_MAGISTRATES_COURT", "Oswestry Magistrates Court"),
    Arguments.of("OXFORD_MAGISTRATES_COURT", "Oxford Magistrates Court"),
    Arguments.of("PENRITH_MAGISTRATES_COURT", "Penrith Magistrates Court"),
    Arguments.of("PENZANCE_MAGISTRATES_COURT", "Penzance Magistrates Court"),
    Arguments.of("PETERBOROUGH_MAGISTRATES_COURT", "Peterborough Magistrates Court"),
    Arguments.of("PETERLEE_MAGISTRATES_COURT", "Peterlee Magistrates Court"),
    Arguments.of("PICKERING_MAGISTRATES_COURT", "Pickering Magistrates Court"),
    Arguments.of("PLYMOUTH_MAGISTRATES_COURT", "Plymouth Magistrates Court"),
    Arguments.of("PONTEFRACT_MAGISTRATES_COURT", "Pontefract Magistrates Court"),
    Arguments.of("PONTYPRIDD_MAGISTRATES_COURT", "Pontypridd Magistrates Court"),
    Arguments.of("POOLE_MAGISTRATES_COURT", "Poole Magistrates Court"),
    Arguments.of("PORT_TALBOT_MAGISTRATES_COURT", "Port Talbot Magistrates Court"),
    Arguments.of("PORTSMOUTH_MAGISTRATES_COURT", "Portsmouth Magistrates Court"),
    Arguments.of("PRESTATYN_MAGISTRATES_COURT", "Prestatyn Magistrates Court"),
    Arguments.of("PRESTON_MAGISTRATES_COURT", "Preston Magistrates Court"),
    Arguments.of("PWLLHELI_MAGISTRATES_COURT", "Pwllheli Magistrates Court"),
    Arguments.of("RAWTENSTALL_MAGISTRATES_COURT", "Rawtenstall Magistrates Court"),
    Arguments.of("READING_MAGISTRATES_COURT", "Reading Magistrates Court"),
    Arguments.of("REDBRIDGE_MAGISTRATES_COURT", "Redbridge Magistrates Court"),
    Arguments.of("REDDITCH_MAGISTRATES_COURT", "Redditch Magistrates Court"),
    Arguments.of("REDHILL_MAGISTRATES_COURT", "Redhill Magistrates Court"),
    Arguments.of("REEDLEY_MAGISTRATES_COURT", "Reedley Magistrates Court"),
    Arguments.of("RETFORD_MAGISTRATES_COURT", "Retford Magistrates Court"),
    Arguments.of("RHONDDA_MAGISTRATES_COURT", "Rhondda Magistrates Court"),
    Arguments.of("RICHMOND_MAGISTRATES_COURT", "Richmond Magistrates Court"),
    Arguments.of("ROCHDALE_MAGISTRATES_COURT", "Rochdale Magistrates Court"),
    Arguments.of("ROMFORD_MAGISTRATES_COURT", "Romford Magistrates Court"),
    Arguments.of("ROSSENDALE_MAGISTRATES_COURT", "Rossendale Magistrates Court"),
    Arguments.of("ROTHERHAM_MAGISTRATES_COURT", "Rotherham Magistrates Court"),
    Arguments.of("RUGBY_MAGISTRATES_COURT", "Rugby Magistrates Court"),
    Arguments.of("RUGELEY_MAGISTRATES_COURT", "Rugeley Magistrates Court"),
    Arguments.of("RUNCORN_MAGISTRATES_COURT", "Runcorn Magistrates Court"),
    Arguments.of("RUTLAND_MAGISTRATES_COURT", "Rutland Magistrates Court"),
    Arguments.of("SALE_MAGISTRATES_COURT", "Sale Magistrates Court"),
    Arguments.of("SALFORD_MAGISTRATES_COURT", "Salford Magistrates Court"),
    Arguments.of("SALISBURY_MAGISTRATES_COURT", "Salisbury Magistrates Court"),
    Arguments.of("SCARBOROUGH_MAGISTRATES_COURT", "Scarborough Magistrates Court"),
    Arguments.of("SCUNTHORPE_MAGISTRATES_COURT", "Scunthorpe Magistrates Court"),
    Arguments.of("SEFTON_MAGISTRATES_COURT", "Sefton Magistrates Court"),
    Arguments.of("SELBY_MAGISTRATES_COURT", "Selby Magistrates Court"),
    Arguments.of("SEVENOAKS_MAGISTRATES_COURT", "Sevenoaks Magistrates Court"),
    Arguments.of("SHEFFIELD_MAGISTRATES_COURT", "Sheffield Magistrates Court"),
    Arguments.of("SHERBORNE_MAGISTRATES_COURT", "Sherborne Magistrates Court"),
    Arguments.of("SHREWSBURY_MAGISTRATES_COURT", "Shrewsbury Magistrates Court"),
    Arguments.of("SITTINGBOURNE_MAGISTRATES_COURT", "Sittingbourne Magistrates Court"),
    Arguments.of("SKEGNESS_MAGISTRATES_COURT", "Skegness Magistrates Court"),
    Arguments.of("SKIPTON_MAGISTRATES_COURT", "Skipton Magistrates Court"),
    Arguments.of("SLEAFORD_MAGISTRATES_COURT", "Sleaford Magistrates Court"),
    Arguments.of("SLOUGH_MAGISTRATES_COURT", "Slough Magistrates Court"),
    Arguments.of("SOLIHULL_MAGISTRATES_COURT", "Solihull Magistrates Court"),
    Arguments.of("SOUTH_SEFTON_MAGISTRATES_COURT", "South Sefton Magistrates Court"),
    Arguments.of("SOUTH_TYNESIDE_MAGISTRATES_COURT", "South Tyneside Magistrates Court"),
    Arguments.of("SOUTH_WESTERN_MAGISTRATES_COURT", "South Western Magistrates Court"),
    Arguments.of("SOUTHAMPTON_THE_AVENUE_MAGISTRATES_COURT", "Southampton (The Avenue) Magistrates Court"),
    Arguments.of("SOUTHEND_MAGISTRATES_COURT", "Southend Magistrates Court"),
    Arguments.of("SOUTHEND_ON_SEA_MAGISTRATES_COURT", "Southend on Sea Magistrates Court"),
    Arguments.of("SOUTHPORT_MAGISTRATES_COURT", "Southport Magistrates Court"),
    Arguments.of("SPALDING_MAGISTRATES_COURT", "Spalding Magistrates Court"),
    Arguments.of("ST_ALBANS_MAGISTRATES_COURT", "St Albans Magistrates Court"),
    Arguments.of("ST_GEORGES_HALL_MAGISTRATES_COURT", "St Georges Hall Magistrates Court"),
    Arguments.of("ST_HELENS_MAGISTRATES_COURT", "St Helens Magistrates Court"),
    Arguments.of("STAFFORD_MAGISTRATES_COURT", "Stafford Magistrates Court"),
    Arguments.of("STAINES_MAGISTRATES_COURT", "Staines Magistrates Court"),
    Arguments.of("STAMFORD_MAGISTRATES_COURT", "Stamford Magistrates Court"),
    Arguments.of("STEVENAGE_MAGISTRATES_COURT", "Stevenage Magistrates Court"),
    Arguments.of("STOCKPORT_MAGISTRATES_COURT", "Stockport Magistrates Court"),
    Arguments.of("STOKE_ON_TRENT_MAGISTRATES_COURT", "Stoke on Trent Magistrates Court"),
    Arguments.of("STOURBRIDGE_MAGISTRATES_COURT", "Stourbridge Magistrates Court"),
    Arguments.of("STRATFORD_MAGISTRATES_COURT", "Stratford Magistrates Court"),
    Arguments.of("STRATFORD_UPON_AVON_MAGISTRATES_COURT", "Stratford upon Avon Magistrates Court"),
    Arguments.of("STROUD_MAGISTRATES_COURT", "Stroud Magistrates Court"),
    Arguments.of("SUDBURY_MAGISTRATES_COURT", "Sudbury Magistrates Court"),
    Arguments.of("SUNDERLAND_MAGISTRATES_COURT", "Sunderland Magistrates Court"),
    Arguments.of("SUTTON_COLDFIELD_MAGISTRATES_COURT", "Sutton Coldfield Magistrates Court"),
    Arguments.of("SUTTON_MAGISTRATES_COURT", "Sutton Magistrates Court"),
    Arguments.of("SWAFFHAM_MAGISTRATES_COURT", "Swaffham Magistrates Court"),
    Arguments.of("SWANSEA_MAGISTRATES_COURT", "Swansea Magistrates Court"),
    Arguments.of("SWINDON_MAGISTRATES_COURT", "Swindon Magistrates Court"),
    Arguments.of("TAMESIDE_MAGISTRATES_COURT", "Tameside Magistrates Court"),
    Arguments.of("TAMWORTH_MAGISTRATES_COURT", "Tamworth Magistrates Court"),
    Arguments.of("TAUNTON_MAGISTRATES_COURT", "Taunton Magistrates Court"),
    Arguments.of("TEESSIDE_MAGISTRATES_COURT", "Teesside Magistrates Court"),
    Arguments.of("TELFORD_MAGISTRATES_COURT", "Telford Magistrates Court"),
    Arguments.of("TENBY_MAGISTRATES_COURT", "Tenby Magistrates Court"),
    Arguments.of("TEWKESBURY_MAGISTRATES_COURT", "Tewkesbury Magistrates Court"),
    Arguments.of("THAME_MAGISTRATES_COURT", "Thame Magistrates Court"),
    Arguments.of("THAMES_MAGISTRATES_COURT", "Thames Magistrates Court"),
    Arguments.of("THETFORD_MAGISTRATES_COURT", "Thetford Magistrates Court"),
    Arguments.of("TORQUAY_MAGISTRATES_COURT", "Torquay Magistrates Court"),
    Arguments.of("TOTNES_MAGISTRATES_COURT", "Totnes Magistrates Court"),
    Arguments.of("TOTTENHAM_MAGISTRATES_COURT", "Tottenham Magistrates Court"),
    Arguments.of("TOWCESTER_MAGISTRATES_COURT", "Towcester Magistrates Court"),
    Arguments.of("TOWER_BRIDGE_MAGISTRATES_COURT", "Tower Bridge Magistrates Court"),
    Arguments.of("TREDEGAR_MAGISTRATES_COURT", "Tredegar Magistrates Court"),
    Arguments.of("TROWBRIDGE_MAGISTRATES_COURT", "Trowbridge Magistrates Court"),
    Arguments.of("TRURO_MAGISTRATES_COURT", "Truro Magistrates Court"),
    Arguments.of("UXBRIDGE_MAGISTRATES_COURT", "Uxbridge Magistrates Court"),
    Arguments.of("WAKEFIELD_MAGISTRATES_COURT", "Wakefield Magistrates Court"),
    Arguments.of("WALLASEY_MAGISTRATES_COURT", "Wallasey Magistrates Court"),
    Arguments.of("WALSALL_MAGISTRATES_COURT", "Walsall Magistrates Court"),
    Arguments.of("WALTHAM_FOREST_MAGISTRATES_COURT", "Waltham Forest Magistrates Court"),
    Arguments.of("WANTAGE_MAGISTRATES_COURT", "Wantage Magistrates Court"),
    Arguments.of("WAREHAM_MAGISTRATES_COURT", "Wareham Magistrates Court"),
    Arguments.of("WARLEY_MAGISTRATES_COURT", "Warley Magistrates Court"),
    Arguments.of("WARRINGTON_MAGISTRATES_COURT", "Warrington Magistrates Court"),
    Arguments.of("WATFORD_MAGISTRATES_COURT", "Watford Magistrates Court"),
    Arguments.of("WELLINGBOROUGH_MAGISTRATES_COURT", "Wellingborough Magistrates Court"),
    Arguments.of("WELLS_MAGISTRATES_COURT", "Wells Magistrates Court"),
    Arguments.of("WELSHPOOL_MAGISTRATES_COURT", "Welshpool Magistrates Court"),
    Arguments.of("WEST_BROMWICH_MAGISTRATES_COURT", "West Bromwich Magistrates Court"),
    Arguments.of("WEST_HAMPSHIRE_MAGISTRATES_COURT", "West Hampshire Magistrates Court"),
    Arguments.of("WEST_LONDON_MAGISTRATES_COURT", "West London Magistrates Court"),
    Arguments.of("WESTMINSTER_MAGISTRATES_COURT", "Westminster Magistrates Court"),
    Arguments.of(
      "WESTMINSTER_MAGISTRATES_COURT_INTERNATIONAL_DIVISION",
      "Westminster Magistrates Court - International Division",
    ),
    Arguments.of("WESTON_SUPER_MARE_MAGISTRATES_COURT", "Weston Super Mare Magistrates Court"),
    Arguments.of("WETHERBY_MAGISTRATES_COURT", "Wetherby Magistrates Court"),
    Arguments.of("WEYMOUTH_MAGISTRATES_COURT", "Weymouth Magistrates Court"),
    Arguments.of("WHITBY_MAGISTRATES_COURT", "Whitby Magistrates Court"),
    Arguments.of("WHITCHURCH_MAGISTRATES_COURT", "Whitchurch Magistrates Court"),
    Arguments.of("WHITEHAVEN_MAGISTRATES_COURT", "Whitehaven Magistrates Court"),
    Arguments.of("WIDNES_MAGISTRATES_COURT", "Widnes Magistrates Court"),
    Arguments.of("WIGAN_AND_LEIGH_MAGISTRATES_COURT", "Wigan and Leigh Magistrates Court"),
    Arguments.of("WIGAN_MAGISTRATES_COURT", "Wigan Magistrates Court"),
    Arguments.of("WILLESDEN_MAGISTRATES_COURT", "Willesden Magistrates Court"),
    Arguments.of("WIMBLEDON_MAGISTRATES_COURT", "Wimbledon Magistrates Court"),
    Arguments.of("WIMBORNE_MAGISTRATES_COURT", "Wimborne Magistrates Court"),
    Arguments.of(
      "WINCHESTER_COMBINED_COURT_CENTRE_MAGISTRATES_COURT",
      "Winchester Combined Court Centre Magistrates Court",
    ),
    Arguments.of("WIRRAL_MAGISTRATES_COURT", "Wirral Magistrates Court"),
    Arguments.of("WISBECH_MAGISTRATES_COURT", "Wisbech Magistrates Court"),
    Arguments.of("WITHAM_MAGISTRATES_COURT", "Witham Magistrates Court"),
    Arguments.of("WITNEY_MAGISTRATES_COURT", "Witney Magistrates Court"),
    Arguments.of("WOKING_MAGISTRATES_COURT", "Woking Magistrates Court"),
    Arguments.of("WOLVERHAMPTON_MAGISTRATES_COURT", "Wolverhampton Magistrates Court"),
    Arguments.of("WOOLWICH_MAGISTRATES_COURT", "Woolwich Magistrates Court"),
    Arguments.of("WORCESTER_CASTLE_ST_MAGISTRATES_COURT", "Worcester (Castle St) Magistrates Court"),
    Arguments.of("WORKINGTON_MAGISTRATES_COURT", "Workington Magistrates Court"),
    Arguments.of("WORKSOP_MAGISTRATES_COURT", "Worksop Magistrates Court"),
    Arguments.of("WORTHING_MAGISTRATES_COURT", "Worthing Magistrates Court"),
    Arguments.of("WREXHAM_MAGISTRATES_COURT", "Wrexham Magistrates Court"),
    Arguments.of("WYCOMBE_MAGISTRATES_COURT", "Wycombe Magistrates Court"),
    Arguments.of("YATE_MAGISTRATES_COURT", "Yate Magistrates Court"),
    Arguments.of("YEOVIL_COUNTY_MAGISTRATES_COURT", "Yeovil County, Magistrates Court"),
    Arguments.of("YEOVIL_MAGISTRATES_COURT", "Yeovil Magistrates Court"),
    Arguments.of("YORK_MAGISTRATES_COURT", "York Magistrates Court"),
    Arguments.of("YSTRADGYNLAIS_MAGISTRATES_COURT", "Ystradgynlais Magistrates Court"),
  )
}
