package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.model.fms.argumentsProvider

import org.junit.jupiter.api.extension.ExtensionContext
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.ArgumentsProvider
import java.util.stream.Stream

class PoliceForceAreasDDv6ArgumentsProvider : ArgumentsProvider {
  override fun provideArguments(context: ExtensionContext?): Stream<out Arguments?>? = Stream.of(
    Arguments.of("AVON_AND_SOMERSET", "Avon and Somerset"),
    Arguments.of("BEDFORDSHIRE", "Bedfordshire"),
    Arguments.of("BRITISH_TRANSPORT_POLICE", "British Transport Police"),
    Arguments.of("CAMBRIDGESHIRE", "Cambridgeshire"),
    Arguments.of("CHESHIRE", "Cheshire"),
    Arguments.of("CITY_OF_LONDON", "City of London"),
    Arguments.of("CLEVELAND", "Cleveland"),
    Arguments.of("COUNTER_TERRORISM_POLICE_NORTH_EAST", "Counter Terrorism Police North East"),
    Arguments.of("COUNTER_TERRORISM_POLICE_NORTH_WEST", "Counter Terrorism Police North West"),
    Arguments.of("COUNTER_TERRORISM_POLICE_SOUTH_CENTRAL", "Counter Terrorism Police South Central"),
    Arguments.of("COUNTER_TERRORISM_POLICE_SOUTH_EAST", "Counter Terrorism Police South East"),
    Arguments.of("COUNTER_TERRORISM_POLICE_SOUTH_WEST", "Counter Terrorism Police South West"),
    Arguments.of("COUNTER_TERRORISM_POLICE_WALES", "Counter Terrorism Police Wales"),
    Arguments.of("CUMBRIA", "Cumbria"),
    Arguments.of("DERBYSHIRE", "Derbyshire"),
    Arguments.of("DEVON_AND_CORNWALL", "Devon and Cornwall"),
    Arguments.of("DORSET", "Dorset"),
    Arguments.of("DURHAM", "Durham"),
    Arguments.of("DYFED_POWYS", "Dyfed-Powys"),
    Arguments.of("ESSEX", "Essex"),
    Arguments.of("GLOUCESTERSHIRE", "Gloucestershire"),
    Arguments.of("GREATER_MANCHESTER", "Greater Manchester"),
    Arguments.of("GWENT", "Gwent"),
    Arguments.of("HAMPSHIRE", "Hampshire"),
    Arguments.of("HERTFORDSHIRE", "Hertfordshire"),
    Arguments.of("HUMBERSIDE", "Humberside"),
    Arguments.of("KENT", "Kent"),
    Arguments.of("LANCASHIRE", "Lancashire"),
    Arguments.of("LEICESTERSHIRE", "Leicestershire"),
    Arguments.of("LINCOLNSHIRE", "Lincolnshire"),
    Arguments.of("MERSEYSIDE", "Merseyside"),
    Arguments.of("METROPOLITAN_POLICE", "Metropolitan Police"),
    Arguments.of("NATIONAL_CRIME_AGENCY", "National Crime Agency"),
    Arguments.of("NORFOLK", "Norfolk"),
    Arguments.of("NORTH_WALES", "North Wales"),
    Arguments.of("NORTH_YORKSHIRE", "North Yorkshire"),
    Arguments.of("NORTHAMPTONSHIRE", "Northamptonshire"),
    Arguments.of("NORTHUMBRIA", "Northumbria"),
    Arguments.of("NOTTINGHAMSHIRE", "Nottinghamshire"),
    Arguments.of("SO15_CTNM", "SO15 CTNM"),
    Arguments.of("SOUTH_WALES", "South Wales"),
    Arguments.of("SOUTH_YORKSHIRE", "South Yorkshire"),
    Arguments.of("STAFFORDSHIRE", "Staffordshire"),
    Arguments.of("SUFFOLK", "Suffolk"),
    Arguments.of("SURREY", "Surrey"),
    Arguments.of("SUSSEX", "Sussex"),
    Arguments.of("THAMES_VALLEY", "Thames Valley"),
    Arguments.of("WARWICKSHIRE", "Warwickshire"),
    Arguments.of("WEST_MERCIA", "West Mercia"),
    Arguments.of("WEST_MIDLANDS", "West Midlands"),
    Arguments.of("WEST_YORKSHIRE", "West Yorkshire"),
    Arguments.of("WILTSHIRE", "Wiltshire"),
    Arguments.of("DIFFERENT_POLICE_AREA", "The device wearer's release address is in a different police force area"),
  )
}
