package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.model.fms.argumentsProvider

import org.junit.jupiter.api.extension.ExtensionContext
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.ArgumentsProvider
import java.util.stream.Stream

class PoliceForceAreasDDv6ArgumentsProvider : ArgumentsProvider {
  override fun provideArguments(context: ExtensionContext?): Stream<out Arguments?>? = Stream.of(
    Arguments.of("AVON_AND_SOMERSET", "Avon and Somerset Constabulary"),
    Arguments.of("BEDFORDSHIRE", "Bedfordshire Police"),
    Arguments.of("BRITISH_TRANSPORT_POLICE", "British Transport Police"),
    Arguments.of("CAMBRIDGESHIRE", "Cambridgeshire Constabulary"),
    Arguments.of("CHESHIRE", "Cheshire Constabulary"),
    Arguments.of("CITY_OF_LONDON", "City of London Police"),
    Arguments.of("CLEVELAND", "Cleveland Police"),
    Arguments.of("COUNTER_TERRORISM_POLICE_NORTH_EAST", "Counter Terrorism Police - North East"),
    Arguments.of("COUNTER_TERRORISM_POLICE_NORTH_WEST", "Counter Terrorism Police - North West"),
    Arguments.of("COUNTER_TERRORISM_POLICE_SOUTH_CENTRAL", "Counter Terrorism Police - South Central"),
    Arguments.of("COUNTER_TERRORISM_POLICE_SOUTH_EAST", "Counter Terrorism Police - South East"),
    Arguments.of("COUNTER_TERRORISM_POLICE_SOUTH_WEST", "Counter Terrorism Police - South West"),
    Arguments.of("COUNTER_TERRORISM_POLICE_WALES", "Counter Terrorism Police - Wales"),
    Arguments.of("CUMBRIA", "Cumbria Constabulary"),
    Arguments.of("DERBYSHIRE", "Derbyshire Constabulary"),
    Arguments.of("DEVON_AND_CORNWALL", "Devon & Cornwall Police"),
    Arguments.of("DORSET", "Dorset Police"),
    Arguments.of("DURHAM", "Durham Constabulary"),
    Arguments.of("DYFED_POWYS", "Dyfed-Powys Police"),
    Arguments.of("ESSEX", "Essex Police"),
    Arguments.of("GLOUCESTERSHIRE", "Gloucestershire Constabulary"),
    Arguments.of("GREATER_MANCHESTER", "Greater Manchester Police"),
    Arguments.of("GWENT", "Gwent Police"),
    Arguments.of("HAMPSHIRE", "Hampshire Constabulary"),
    Arguments.of("HERTFORDSHIRE", "Hertfordshire Constabulary"),
    Arguments.of("HUMBERSIDE", "Humberside Police"),
    Arguments.of("KENT", "Kent Police"),
    Arguments.of("LANCASHIRE", "Lancashire Constabulary"),
    Arguments.of("LEICESTERSHIRE", "Leicestershire Police"),
    Arguments.of("LINCOLNSHIRE", "Lincolnshire Police"),
    Arguments.of("MERSEYSIDE", "Merseyside Police"),
    Arguments.of("METROPOLITAN_POLICE", "Metropolitan Police Service"),
    Arguments.of("NATIONAL_CRIME_AGENCY", "National Crime Agency"),
    Arguments.of("NORFOLK", "Norfolk Constabulary"),
    Arguments.of("NORTH_WALES", "North Wales Police"),
    Arguments.of("NORTH_YORKSHIRE", "North Yorkshire Police"),
    Arguments.of("NORTHAMPTONSHIRE", "Northamptonshire Police"),
    Arguments.of("NORTHUMBRIA", "Northumbria Police"),
    Arguments.of("NOTTINGHAMSHIRE", "Nottinghamshire Police"),
    Arguments.of("SO15_CTNM", "SO15 CTNM"),
    Arguments.of("SOUTH_WALES", "South Wales Police"),
    Arguments.of("SOUTH_YORKSHIRE", "South Yorkshire Police"),
    Arguments.of("STAFFORDSHIRE", "Staffordshire Police"),
    Arguments.of("SUFFOLK", "Suffolk Constabulary"),
    Arguments.of("SURREY", "Surrey Police"),
    Arguments.of("SUSSEX", "Sussex Police"),
    Arguments.of("THAMES_VALLEY", "Thames Valley Police"),
    Arguments.of("WARWICKSHIRE", "Warwickshire Police"),
    Arguments.of("WEST_MERCIA", "West Mercia Police"),
    Arguments.of("WEST_MIDLANDS", "West Midlands Police"),
    Arguments.of("WEST_YORKSHIRE", "West Yorkshire Police"),
    Arguments.of("WILTSHIRE", "Wiltshire Police"),
    Arguments.of("DIFFERENT_POLICE_AREA", "The device wearer's release address is in a different police force area"),
  )
}
