package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.model.fms.argumentsProvider

import org.junit.jupiter.api.extension.ExtensionContext
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.ArgumentsProvider
import java.util.stream.Stream

class YouthCourtArgumentsProvider : ArgumentsProvider {
  override fun provideArguments(context: ExtensionContext?): Stream<out Arguments?>? = Stream.of(
    Arguments.of("ABERYSTWYTH_YOUTH_COURT", "Aberystwyth Youth Court"),
    Arguments.of("ACCRINGTON_YOUTH_COURT", "Accrington Youth Court"),
    Arguments.of("ACTON_YOUTH_COURT", "Acton Youth Court"),
    Arguments.of("ALDRIDGE_YOUTH_COURT", "Aldridge Youth Court"),
    Arguments.of("ALNWICK_YOUTH_COURT", "Alnwick Youth Court"),
    Arguments.of("ALTON_YOUTH_COURT", "Alton Youth Court"),
    Arguments.of("AMERSHAM_YOUTH_COURT", "Amersham Youth Court"),
    Arguments.of("AMMANFORD_YOUTH_COURT", "Ammanford Youth Court"),
    Arguments.of("ANDOVER_YOUTH_COURT", "Andover Youth Court"),
    Arguments.of("AYLESBURY_YOUTH_COURT", "Aylesbury Youth Court"),
    Arguments.of("BARKING_YOUTH_COURT", "Barking Youth Court"),
    Arguments.of("BARNET_YOUTH_COURT", "Barnet Youth Court"),
    Arguments.of("BARNSLEY_YOUTH_COURT", "Barnsley Youth Court"),
    Arguments.of("BARNSTAPLE_YOUTH_COURT", "Barnstaple Youth Court"),
    Arguments.of("BARROW_IN_FURNESS_YOUTH_COURT", "Barrow in Furness Youth Court"),
    Arguments.of("BARRY_YOUTH_COURT", "Barry Youth Court"),
    Arguments.of("BASILDON_YOUTH_COURT", "Basildon Youth Court"),
    Arguments.of("BASINGSTOKE_YOUTH_COURT", "Basingstoke Youth Court"),
    Arguments.of("BATH_YOUTH_COURT", "Bath Youth Court"),
    Arguments.of("BATLEY_AND_DEWSBURY_YOUTH_COURT", "Batley and Dewsbury Youth Court"),
    Arguments.of("BEDFORD_YOUTH_COURT", "Bedford Youth Court"),
    Arguments.of("BERWICK_UPON_TWEED_YOUTH_COURT", "Berwick upon Tweed Youth Court"),
    Arguments.of("BEVERLEY_YOUTH_COURT", "Beverley Youth Court"),
    Arguments.of("BEXLEY_YOUTH_COURT", "Bexley Youth Court"),
    Arguments.of("BICESTER_YOUTH_COURT", "Bicester Youth Court"),
    Arguments.of("BIRMINGHAM_YOUTH_COURT", "Birmingham Youth Court"),
    Arguments.of("BISHOP_AUCKLAND_YOUTH_COURT", "Bishop Auckland Youth Court"),
    Arguments.of("BLACKBURN_YOUTH_COURT", "Blackburn Youth Court"),
    Arguments.of("BLACKPOOL_YOUTH_COURT", "Blackpool Youth Court"),
    Arguments.of("BLACKWOOD_YOUTH_COURT", "Blackwood Youth Court"),
    Arguments.of("BLANDFORD_FORUM_YOUTH_COURT", "Blandford Forum Youth Court"),
    Arguments.of("BLAYDON_YOUTH_COURT", "Blaydon Youth Court"),
    Arguments.of("BODMIN_YOUTH_COURT", "Bodmin Youth Court"),
    Arguments.of("BOLTON_YOUTH_COURT", "Bolton Youth Court"),
    Arguments.of("BOSTON_YOUTH_COURT", "Boston Youth Court"),
    Arguments.of("BOURNE_YOUTH_COURT", "Bourne Youth Court"),
    Arguments.of("BRADFORD_YOUTH_COURT", "Bradford Youth Court"),
    Arguments.of("BRENT_YOUTH_COURT", "Brent Youth Court"),
    Arguments.of("BRENTFORD_YOUTH_COURT", "Brentford Youth Court"),
    Arguments.of("BRIDGEND_YOUTH_COURT", "Bridgend Youth Court"),
    Arguments.of("BRIDGWATER_YOUTH_COURT", "Bridgwater Youth Court"),
    Arguments.of("BRIDLINGTON_YOUTH_COURT", "Bridlington Youth Court"),
    Arguments.of("BRIGHTON_YOUTH_COURT_JOHN_STREET", "Brighton Youth Court (John Street)"),
    Arguments.of("BRISTOL_YOUTH_COURT", "Bristol Youth Court"),
    Arguments.of("BROMLEY_YOUTH_COURT", "Bromley Youth Court"),
    Arguments.of("BROMSGROVE_AND_REDDITCH_YOUTH_COURT", "Bromsgrove and Redditch Youth Court"),
    Arguments.of("BURNLEY_YOUTH_COURT", "Burnley Youth Court"),
    Arguments.of("BURTON_UPON_TRENT_YOUTH_COURT", "Burton upon Trent Youth Court"),
    Arguments.of("BURY_ST_EDMUNDS_YOUTH_COURT", "Bury St Edmunds Youth Court"),
    Arguments.of("BURY_YOUTH_COURT", "Bury Youth Court"),
    Arguments.of("BUXTON_YOUTH_COURT", "Buxton Youth Court"),
    Arguments.of("CAERNARFON_YOUTH_COURT", "Caernarfon Youth Court"),
    Arguments.of("CALDERDALE_YOUTH_COURT", "Calderdale Youth Court"),
    Arguments.of("CAMBORNE_YOUTH_COURT", "Camborne Youth Court"),
    Arguments.of("CAMBRIDGE_YOUTH_COURT", "Cambridge Youth Court"),
    Arguments.of("CANNOCK_YOUTH_COURT", "Cannock Youth Court"),
    Arguments.of("CANTERBURY_YOUTH_COURT", "Canterbury Youth Court"),
    Arguments.of("CARDIFF_YOUTH_COURT", "Cardiff Youth Court"),
    Arguments.of("CARDIGAN_YOUTH_COURT", "Cardigan Youth Court"),
    Arguments.of("CARLISLE_YOUTH_COURT", "Carlisle Youth Court"),
    Arguments.of("CARMARTHEN_YOUTH_COURT", "Carmarthen Youth Court"),
    Arguments.of("CENTRAL_NORFOLK_YOUTH_COURT", "Central Norfolk Youth Court"),
    Arguments.of("CHATHAM_YOUTH_COURT", "Chatham Youth Court"),
    Arguments.of("CHELTENHAM_YOUTH_COURT", "Cheltenham Youth Court"),
    Arguments.of("CHESHUNT_YOUTH_COURT", "Cheshunt Youth Court"),
    Arguments.of("CHESTER_YOUTH_COURT", "Chester Youth Court"),
    Arguments.of("CHESTERFIELD_YOUTH_COURT_TAPTON_LANE", "Chesterfield Youth Court (Tapton Lane)"),
    Arguments.of("CHICHESTER_YOUTH_COURT", "Chichester Youth Court"),
    Arguments.of("CHIPPENHAM_YOUTH_COURT", "Chippenham Youth Court"),
    Arguments.of("CHORLEY_YOUTH_COURT", "Chorley Youth Court"),
    Arguments.of("CITY_OF_SALFORD_YOUTH_COURT", "City of Salford Youth Court"),
    Arguments.of("COALVILLE_YOUTH_COURT", "Coalville Youth Court"),
    Arguments.of("CONSETT_YOUTH_COURT", "Consett Youth Court"),
    Arguments.of("COVENTRY_YOUTH_COURT", "Coventry Youth Court"),
    Arguments.of("CRAWLEY_YOUTH_COURT", "Crawley Youth Court"),
    Arguments.of("CREWE_YOUTH_COURT", "Crewe Youth Court"),
    Arguments.of("CROYDON_YOUTH_COURT", "Croydon Youth Court"),
    Arguments.of("CWMBRAN_YOUTH_COURT", "Cwmbran Youth Court"),
    Arguments.of("DARLINGTON_YOUTH_COURT", "Darlington Youth Court"),
    Arguments.of("DARTFORD_YOUTH_COURT", "Dartford Youth Court"),
    Arguments.of("DENBIGH_YOUTH_COURT", "Denbigh Youth Court"),
    Arguments.of("DERBY_YOUTH_COURT_ST_MARYS_GATE", "Derby Youth Court (St Mary's Gate)"),
    Arguments.of("DIDCOT_YOUTH_COURT", "Didcot Youth Court"),
    Arguments.of("DONCASTER_YOUTH_COURT", "Doncaster Youth Court"),
    Arguments.of("DUDLEY_YOUTH_COURT", "Dudley Youth Court"),
    Arguments.of("DURHAM_YOUTH_COURT", "Durham Youth Court"),
    Arguments.of("EASTBOURNE_YOUTH_COURT", "Eastbourne Youth Court"),
    Arguments.of("ELY_YOUTH_COURT", "Ely Youth Court"),
    Arguments.of("EXETER_YOUTH_COURT", "Exeter Youth Court"),
    Arguments.of("FAREHAM_YOUTH_COURT", "Fareham Youth Court"),
    Arguments.of("FLEETWOOD_YOUTH_COURT", "Fleetwood Youth Court"),
    Arguments.of("FOLKESTONE_YOUTH_COURT", "Folkestone Youth Court"),
    Arguments.of("FROME_YOUTH_COURT", "Frome Youth Court"),
    Arguments.of("GAINSBOROUGH_YOUTH_COURT", "Gainsborough Youth Court"),
    Arguments.of("GLOSSOP_YOUTH_COURT", "Glossop Youth Court"),
    Arguments.of("GLOUCESTER_YOUTH_COURT", "Gloucester Youth Court"),
    Arguments.of("GOOLE_YOUTH_COURT", "Goole Youth Court"),
    Arguments.of("GOSFORTH_YOUTH_COURT", "Gosforth Youth Court"),
    Arguments.of("GRANTHAM_YOUTH_COURT", "Grantham Youth Court"),
    Arguments.of("GRAYS_YOUTH_COURT", "Grays Youth Court"),
    Arguments.of("GREAT_YARMOUTH_YOUTH_COURT", "Great Yarmouth Youth Court"),
    Arguments.of("GRIMSBY_YOUTH_COURT", "Grimsby Youth Court"),
    Arguments.of("HALESOWEN_YOUTH_COURT", "Halesowen Youth Court"),
    Arguments.of("HARLOW_YOUTH_COURT", "Harlow Youth Court"),
    Arguments.of("HARROGATE_YOUTH_COURT", "Harrogate Youth Court"),
    Arguments.of("HARROW_YOUTH_COURT", "Harrow Youth Court"),
    Arguments.of("HARTLEPOOL_YOUTH_COURT", "Hartlepool Youth Court"),
    Arguments.of("HARWICH_YOUTH_COURT", "Harwich Youth Court"),
    Arguments.of("HASTINGS_YOUTH_COURT", "Hastings Youth Court"),
    Arguments.of("HAVERFORDWEST_YOUTH_COURT", "Haverfordwest Youth Court"),
    Arguments.of("HAVERING_YOUTH_COURT", "Havering Youth Court"),
    Arguments.of("HEMEL_HEMPSTEAD_YOUTH_COURT", "Hemel Hempstead Youth Court"),
    Arguments.of("HENDON_YOUTH_COURT", "Hendon Youth Court"),
    Arguments.of("HEREFORD_YOUTH_COURT_BATH_STREET", "Hereford Youth Court (Bath Street)"),
    Arguments.of("HIGHGATE_YOUTH_COURT", "Highgate Youth Court"),
    Arguments.of("HINCKLEY_YOUTH_COURT", "Hinckley Youth Court"),
    Arguments.of("HOLYHEAD_YOUTH_COURT", "Holyhead Youth Court"),
    Arguments.of("HORSHAM_YOUTH_COURT", "Horsham Youth Court"),
    Arguments.of("HOUGHTON_LE_SPRING_YOUTH_COURT", "Houghton le Spring Youth Court"),
    Arguments.of("HUDDERSFIELD_YOUTH_COURT", "Huddersfield Youth Court"),
    Arguments.of("HULL_YOUTH_COURT", "Hull Youth Court"),
    Arguments.of("HUNTINGDON_YOUTH_COURT", "Huntingdon Youth Court"),
    Arguments.of("HUYTON_YOUTH_COURT", "Huyton Youth Court"),
    Arguments.of("ILKESTON_YOUTH_COURT", "Ilkeston Youth Court"),
    Arguments.of("INNER_LONDON_YOUTH_COURTS_CENTRE_1", "Inner London Youth Courts Centre 1"),
    Arguments.of("INNER_LONDON_YOUTH_COURTS_CENTRE_2", "Inner London Youth Courts Centre 2"),
    Arguments.of("INNER_LONDON_YOUTH_COURTS_CENTRE_3", "Inner London Youth Courts Centre 3"),
    Arguments.of("INNER_LONDON_YOUTH_COURTS_CENTRE_4", "Inner London Youth Courts Centre 4"),
    Arguments.of("IPSWICH_YOUTH_COURT", "Ipswich Youth Court"),
    Arguments.of("ISLE_OF_WIGHT_YOUTH_COURT", "Isle of Wight Youth Court"),
    Arguments.of("KEIGHLEY_YOUTH_COURT", "Keighley Youth Court"),
    Arguments.of("KENDAL_YOUTH_COURT", "Kendal Youth Court"),
    Arguments.of("KETTERING_YOUTH_COURT", "Kettering Youth Court"),
    Arguments.of("KIDDERMINSTER_YOUTH_COURT_COMBERTON_PLACE", "Kidderminster Youth Court (Comberton Place)"),
    Arguments.of("KINGSTON_UPON_THAMES_YOUTH_COURT", "Kingston upon Thames Youth Court"),
    Arguments.of("LANBAURGH_EAST_YOUTH_COURT_GUISBOROUGH", "Lanbaurgh East Youth Court (Guisborough)"),
    Arguments.of("LANCASTER_YOUTH_COURT", "Lancaster Youth Court"),
    Arguments.of("LEAMINGTON_SPA_YOUTH_COURT", "Leamington Spa Youth Court"),
    Arguments.of("LEEDS_YOUTH_COURT", "Leeds Youth Court"),
    Arguments.of("LEICESTER_YOUTH_COURT", "Leicester Youth Court"),
    Arguments.of("LEWES_YOUTH_COURT", "Lewes Youth Court"),
    Arguments.of("LEYLAND_YOUTH_COURT", "Leyland Youth Court"),
    Arguments.of("LINCOLN_YOUTH_COURT", "Lincoln Youth Court"),
    Arguments.of("LIVERPOOL_YOUTH_CODE_HATTON_GARDEN", "Liverpool Youth Code (Hatton Garden)"),
    Arguments.of("LLANDRINDOD_WELLS_YOUTH_COURT", "Llandrindod Wells Youth Court"),
    Arguments.of("LLANDUDNO_YOUTH_COURT", "Llandudno Youth Court"),
    Arguments.of("LLANELLI_YOUTH_COURT", "Llanelli Youth Court"),
    Arguments.of("LLANGEFNI_YOUTH_COURT", "Llangefni Youth Court"),
    Arguments.of("LLWYNYPIA_YOUTH_COURT", "Llwynypia Youth Court"),
    Arguments.of("LOUGHBOROUGH_YOUTH_COURT", "Loughborough Youth Court"),
    Arguments.of("LOUTH_YOUTH_COURT", "Louth Youth Court"),
    Arguments.of("LOWESTOFT_YOUTH_COURT", "Lowestoft Youth Court"),
    Arguments.of("LUTON_YOUTH_COURT", "Luton Youth Court"),
    Arguments.of("MACCLESFIELD_YOUTH_COURT_HIBEL_RD", "Macclesfield Youth Court (Hibel Rd)"),
    Arguments.of("MAIDENHEAD_YOUTH_COURT", "Maidenhead Youth Court"),
    Arguments.of("MAIDSTONE_YOUTH_COURT", "Maidstone Youth Court"),
    Arguments.of("MANCHESTER_CITY_YOUTH_COURT", "Manchester City Youth Court"),
    Arguments.of("MANSFIELD_YOUTH_COURT_ROSEMARY_ST", "Mansfield Youth Court (Rosemary St)"),
    Arguments.of("MARGATE_YOUTH_COURT", "Margate Youth Court"),
    Arguments.of("MARKET_DRAYTON_YOUTH_COURT", "Market Drayton Youth Court"),
    Arguments.of("MARKET_HARBOROUGH_YOUTH_COURT", "Market Harborough Youth Court"),
    Arguments.of("MELTON_MOWBRAY_YOUTH_COURT", "Melton Mowbray Youth Court"),
    Arguments.of("MERTHYR_TYDFIL_YOUTH_COURT", "Merthyr Tydfil Youth Court"),
    Arguments.of("MIDDLESBROUGH_YOUTH_COURT", "Middlesbrough Youth Court"),
    Arguments.of("MILTON_KEYNES_YOUTH_COURT", "Milton Keynes Youth Court"),
    Arguments.of("MINEHEAD_YOUTH_COURT", "Minehead Youth Court"),
    Arguments.of("MOLD_YOUTH_COURT", "Mold Youth Court"),
    Arguments.of("NEATH_YOUTH_COURT", "Neath Youth Court"),
    Arguments.of("NEW_FOREST_YOUTH_COURT", "New Forest Youth Court"),
    Arguments.of("NEWARK_YOUTH_COURT", "Newark Youth Court"),
    Arguments.of("NEWCASTLE_UNDER_LYME_YOUTH_COURT", "Newcastle under Lyme Youth Court"),
    Arguments.of("NEWCASTLE_UPON_TYNE_YOUTH_COURT", "Newcastle Upon Tyne Youth Court"),
    Arguments.of("NEWTON_ABBOT_YOUTH_COURT", "Newton Abbot Youth Court"),
    Arguments.of("NEWTON_AYCLIFFE_YOUTH_COURT", "Newton Aycliffe Youth Court"),
    Arguments.of("NORTH_NORFOLK_YOUTH_COURT", "North Norfolk Youth Court"),
    Arguments.of("NORTH_SEFTON_YOUTH_COURT", "North Sefton Youth Court"),
    Arguments.of("NORTH_SHIELDS_YOUTH_COURT", "North Shields Youth Court"),
    Arguments.of("NORTHALLERTON_YOUTH_COURT", "Northallerton Youth Court"),
    Arguments.of("NORTHAMPTON_YOUTH_COURT", "Northampton Youth Court"),
    Arguments.of("NORTHWICH_YOUTH_COURT", "Northwich Youth Court"),
    Arguments.of("NORWICH_YOUTH_COURT", "Norwich Youth Court"),
    Arguments.of("NOTTINGHAM_YOUTH_COURT_CARRINGTON_ST", "Nottingham Youth Court (Carrington St)"),
    Arguments.of("NUNEATON_YOUTH_COURT_VICARAGE_ST", "Nuneaton Youth Court, Vicarage St"),
    Arguments.of("OLDBURY_YOUTH_COURT", "Oldbury Youth Court"),
    Arguments.of("OLDHAM_YOUTH_COURT", "Oldham Youth Court"),
    Arguments.of("ORMSKIRK_YOUTH_COURT", "Ormskirk Youth Court"),
    Arguments.of("OSWESTRY_YOUTH_COURT", "Oswestry Youth Court"),
    Arguments.of("OXFORD_YOUTH_COURT", "Oxford Youth Court"),
    Arguments.of("PENRITH_YOUTH_CODE", "Penrith Youth Code"),
    Arguments.of("PENZANCE_YOUTH_COURT", "Penzance Youth Court"),
    Arguments.of("PETERBOROUGH_YOUTH_COURT", "Peterborough Youth Court"),
    Arguments.of("PETERLEE_YOUTH_COURT", "Peterlee Youth Court"),
    Arguments.of("PLYMOUTH_YOUTH_COURT", "Plymouth Youth Court"),
    Arguments.of("PONTEFRACT_YOUTH_COURT", "Pontefract Youth Court"),
    Arguments.of("POOLE_YOUTH_COURT", "Poole Youth Court"),
    Arguments.of("PORT_TALBOT_YOUTH_COURT", "Port Talbot Youth Court"),
    Arguments.of("PORTSMOUTH_YOUTH_COURT", "Portsmouth Youth Court"),
    Arguments.of("PRESTATYN_YOUTH_COURT", "Prestatyn Youth Court"),
    Arguments.of("PRESTON_YOUTH_COURT", "Preston Youth Court"),
    Arguments.of("PWLLHELI_YOUTH_COURT", "Pwllheli Youth Court"),
    Arguments.of("RAWTENSTALL_YOUTH_COURT", "Rawtenstall Youth Court"),
    Arguments.of("READING_YOUTH_COURT", "Reading Youth Court"),
    Arguments.of("REDBRIDGE_YOUTH_COURT", "Redbridge Youth Court"),
    Arguments.of("REDHILL_YOUTH_COURT", "Redhill Youth Court"),
    Arguments.of("REEDLEY_YOUTH_COURT", "Reedley Youth Court"),
    Arguments.of("RETFORD_YOUTH_COURT", "Retford Youth Court"),
    Arguments.of("RICHMOND_UPON_THAMES_YOUTH_COURT", "Richmond upon Thames Youth Court"),
    Arguments.of("ROCHDALE_YOUTH_COURT", "Rochdale Youth Court"),
    Arguments.of("ROTHERHAM_YOUTH_COURT", "Rotherham Youth Court"),
    Arguments.of("RUGBY_YOUTH_COURT", "Rugby Youth Court"),
    Arguments.of("SALISBURY_YOUTH_COURT", "Salisbury Youth Court"),
    Arguments.of("SCARBOROUGH_YOUTH_COURT_NORTHWAY", "Scarborough Youth Court (Northway)"),
    Arguments.of("SCUNTHORPE_YOUTH_COURT", "Scunthorpe Youth Court"),
    Arguments.of("SELBY_YOUTH_COURT", "Selby Youth Court"),
    Arguments.of("SEVENOAKS_YOUTH_COURT", "Sevenoaks Youth Court"),
    Arguments.of("SHEFFIELD_YOUTH_COURT", "Sheffield Youth Court"),
    Arguments.of("SHREWSBURY_YOUTH_COURT", "Shrewsbury Youth Court"),
    Arguments.of("SITTINGBOURNE_YOUTH_COURT", "Sittingbourne Youth Court"),
    Arguments.of("SKEGNESS_YOUTH_COURT", "Skegness Youth Court"),
    Arguments.of("SKIPTON_YOUTH_COURT", "Skipton Youth Court"),
    Arguments.of("SLEAFORD_YOUTH_COURT", "Sleaford Youth Court"),
    Arguments.of("SOLIHULL_YOUTH_COURT", "Solihull Youth Court"),
    Arguments.of("SOUTH_EAST_NORTHUMBERLAND_YOUTH_COURT", "South East Northumberland Youth Court"),
    Arguments.of("SOUTH_NORFOLK_YOUTH_COURT", "South Norfolk Youth Court"),
    Arguments.of("SOUTH_SEFTON_YOUTH_COURT", "South Sefton Youth Court"),
    Arguments.of("SOUTH_SHIELDS_YOUTH_COURT_MILLBANK", "South Shields Youth Court (Millbank)"),
    Arguments.of("SOUTH_SHROPSHIRE_YOUTH_COURT", "South Shropshire Youth Court"),
    Arguments.of("SOUTH_WORCESTER_YOUTH_COURT", "South Worcester Youth Court"),
    Arguments.of("SOUTHAMPTON_YOUTH_COURT", "Southampton Youth Court"),
    Arguments.of("SOUTHEND_ON_SEA_YOUTH_COURT", "Southend on Sea Youth Court"),
    Arguments.of("SPALDING_YOUTH_COURT", "Spalding Youth Court"),
    Arguments.of("ST_ALBANS_YOUTH_COURT", "St Albans Youth Court"),
    Arguments.of("ST_HELENS_YOUTH_COURT", "St Helens Youth Court"),
    Arguments.of("STAFFORD_YOUTH_COURT", "Stafford Youth Court"),
    Arguments.of("STAINES_YOUTH_COURT", "Staines Youth Court"),
    Arguments.of("STEVENAGE_YOUTH_COURT", "Stevenage Youth Court"),
    Arguments.of("STOCKPORT_YOUTH_COURT", "Stockport Youth Court"),
    Arguments.of("STOKE_ON_TRENT_YOUTH_COURT", "Stoke on Trent Youth Court"),
    Arguments.of("STRATFORD_YOUTH_COURT", "Stratford Youth Court"),
    Arguments.of("SUDBURY_YOUTH_COURT", "Sudbury Youth Court"),
    Arguments.of("SUNDERLAND_YOUTH_COURT", "Sunderland Youth Court"),
    Arguments.of("SUTTON_COLDFIELD_YOUTH_COURT", "Sutton Coldfield Youth Court"),
    Arguments.of("SUTTON_YOUTH_COURT", "Sutton Youth Court"),
    Arguments.of("SWANSEA_YOUTH_COURT_DYNEVOR_PLACE", "Swansea Youth Court (Dynevor Place)"),
    Arguments.of("SWINDON_YOUTH_COURT", "Swindon Youth Court"),
    Arguments.of("TAMESIDE_YOUTH_COURT", "Tameside Youth Court"),
    Arguments.of("TAMWORTH_YOUTH_COURT", "Tamworth Youth Court"),
    Arguments.of("TAUNTON_YOUTH_COURT", "Taunton Youth Court"),
    Arguments.of("TELFORD_AND_BRIDGENORTH_YOUTH_COURT", "Telford and Bridgenorth Youth Court"),
    Arguments.of("TOTTENHAM_YOUTH_COURT", "Tottenham Youth Court"),
    Arguments.of("TRAFFORD_YOUTH_COURT", "Trafford Youth Court"),
    Arguments.of("TRURO_YOUTH_COURT", "Truro Youth Court"),
    Arguments.of("TYNEDALE_YOUTH_COURT", "Tynedale Youth Court"),
    Arguments.of("UXBRIDGE_YOUTH_COURT", "Uxbridge Youth Court"),
    Arguments.of("WAKEFIELD_YOUTH_COURT", "Wakefield Youth Court"),
    Arguments.of("WALSALL_YOUTH_COURT_STAFFORD_STREET", "Walsall Youth Court (Stafford Street)"),
    Arguments.of("WALTHAM_FOREST_YOUTH_COURT", "Waltham Forest Youth Court"),
    Arguments.of("WARRINGTON_YOUTH_COURT_ARPLEY_STREET", "Warrington Youth Court (Arpley Street)"),
    Arguments.of("WELLINGBOROUGH_YOUTH_COURT", "Wellingborough Youth Court"),
    Arguments.of("WELLS_YOUTH_COURT", "Wells Youth Court"),
    Arguments.of("WELSHPOOL_YOUTH_COURT", "Welshpool Youth Court"),
    Arguments.of("WEST_BERKSHIRE_YOUTH_COURT", "West Berkshire Youth Court"),
    Arguments.of("WEST_BROMWICH_YOUTH_COURT", "West Bromwich Youth Court"),
    Arguments.of("WEST_NORFOLK_YOUTH_COURT", "West Norfolk Youth Court"),
    Arguments.of("WESTON_SUPER_MARE_YOUTH_COURT", "Weston-super-Mare Youth Court"),
    Arguments.of("WEYMOUTH_YOUTH_COURT", "Weymouth Youth Court"),
    Arguments.of("WHITEHAVEN_YOUTH_COURT", "Whitehaven Youth Court"),
    Arguments.of("WIDNES_YOUTH_COURT", "Widnes Youth Court"),
    Arguments.of("WIGAN_YOUTH_COURT", "Wigan Youth Court"),
    Arguments.of("WIMBLEDON_YOUTH_COURT", "Wimbledon Youth Court"),
    Arguments.of("WIRRAL_YOUTH_COURT", "Wirral Youth Court"),
    Arguments.of("WISBECH_YOUTH_COURT", "Wisbech Youth Court"),
    Arguments.of("WITHAM_YOUTH_COURT", "Witham Youth Court"),
    Arguments.of("WOKING_YOUTH_COURT", "Woking Youth Court"),
    Arguments.of("WOLVERHAMPTON_YOUTH_COURT", "Wolverhampton Youth Court"),
    Arguments.of("WORKINGTON_YOUTH_COURT", "Workington Youth Court"),
    Arguments.of("WORKSOP_YOUTH_COURT", "Worksop Youth Court"),
    Arguments.of("WORTHING_YOUTH_COURT", "Worthing Youth Court"),
    Arguments.of("WREXHAM_YOUTH_COURT", "Wrexham Youth Court"),
    Arguments.of("WYCOMBE_YOUTH_COURT", "Wycombe Youth Court"),
    Arguments.of("YATE_YOUTH_COURT", "Yate Youth Court"),
    Arguments.of("YEOVIL_YOUTH_COURT", "Yeovil Youth Court"),
    Arguments.of("YORK_YOUTH_COURT", "York Youth Court"),
  )
}
