---
# Per environment values which override defaults in hmpps-electronic-monitoring-create-an-order-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-electronic-monitoring-create-an-order-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    DOCUMENT_MANAGEMENT_URL: "https://document-api-dev.hmpps.service.justice.gov.uk/"
    CP_INTEGRATION_ENABLED: true

  namespace_secrets:
    hmpps-electronic-monitoring-create-an-order-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      CLIENT_ID: "API_CLIENT_ID"
      CLIENT_SECRET: "API_CLIENT_SECRET"
    serco-secret:
      SERCO_AUTH_URL: "SERCO_AUTH_URL"
      SERCO_CLIENT_ID: "SERCO_CLIENT_ID"
      SERCO_CLIENT_SECRET: "SERCO_CLIENT_SECRET"
      SERCO_USERNAME: "SERCO_USERNAME"
      SERCO_PASSWORD: "SERCO_PASSWORD"
      SERCO_URL: "SERCO_URL"
    rds-postgresql-instance-output:
      DB_SERVER: "rds_instance_endpoint"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    sqs-court-case-events-fifo-secret:
      HMPPS_SQS_QUEUES_COURTHEARINGEVENTQUEUE_QUEUENAME: "sqs_queue_name"
      HMPPS_SQS_QUEUES_COURTHEARINGEVENTQUEUE_QUEUEARN: "sqs_queue_arn"
    sqs-court-case-events-fifo-dlq-secret:
      HMPPS_SQS_QUEUES_COURTHEARINGEVENTQUEUE_DLQNAME: "sqs_queue_name"
# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
