package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.models.enums

enum class Prison(val id: String, val prisonName: String) {
  ALTCOURSE_PRISON("ACI", "Altcourse Prison"),
  ASHFIELD_PRISON("ASI", "Ashfield Prison"),
  ASKHAM_GRANGE_PRISON_AND_YOUNG_OFFENDER_INSTITUTION("AGI", "Askham Grange Prison and Young Offender Institution"),
  AYLESBURY_PRISON_AND_YOUNG_OFFENDER_INSTITUTION("AYI", "Aylesbury Prison and Young Offender Institution"),
  BEDFORD_PRISON("BFI", "Bedford Prison"),
  BELMARSH_PRISON("BAI", "Belmarsh Prison"),
  BERWYN_PRISON("BWI", "Berwyn Prison"),
  BIRMINGHAM_PRISON("BMI", "Birmingham Prison"),
  BRINSFORD_PRISON("BSI", "Brinsford Prison"),
  BRISTOL_PRISON("BLI", "Bristol Prison"),
  BRIXTON_PRISON("BXI", "Brixton Prison"),
  BRONZEFIELD_PRISON("BZI", "Bronzefield Prison"),
  BUCKLEY_HALL_PRISON("BCI", "Buckley Hall Prison"),
  BULLINGDON_PRISON("BNI", "Bullingdon Prison"),
  BURE_PRISON("BRI", "Bure Prison"),
  CARDIFF_PRISON("CFI", "Cardiff Prison"),
  CHANNINGS_WOOD_PRISON("CWI", "Channings Wood Prison"),
  CHELMSFORD_PRISON("CDI", "Chelmsford Prison"),
  COLDINGLEY_PRISON("CLI", "Coldingley Prison"),
  COOKHAM_WOOD_YOUNG_OFFENDER_INSTITUTION("CKI", "Cookham Wood Young Offender Institution"),
  COOKHAM_WOOD_PRISON("CKI", "Cookham Wood Prison"),
  DARTMOOR_PRISON("DAI", "Dartmoor Prison"),
  DEERBOLT_PRISON("DTI", "Deerbolt Prison"),
  DONCASTER_PRISON("DNI", "Doncaster Prison"),
  DOVEGATE_PRISON("DGI", "Dovegate Prison"),
  DOWNVIEW_PRISON_AND_YOUNG_OFFENDER_INSTITUTION("DWI", "Downview Prison and Young Offender Institution"),
  DRAKE_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION("DHI", "Drake Hall Prison and Young Offender Institution"),
  DURHAM_PRISON("DMI", "Durham Prison"),
  EAST_SUTTON_PARK_PRISON_AND_YOUNG_OFFENDER_INSTITUTION(
    "ESI",
    "East Sutton Park Prison and Young Offender Institution",
  ),
  EASTWOOD_PARK_PRISON_AND_YOUNG_OFFENDER_INSTITUTION("EWI", "Eastwood Park Prison and Young Offender Institution"),
  ELMLEY_PRISON("EYI", "Elmley Prison"),
  ERLESTOKE_PRISON("EEI", "Erlestoke Prison"),
  EXETER_PRISON("EXI", "Exeter Prison"),
  FEATHERSTONE_PRISON("FSI", "Featherstone Prison"),
  FELTHAM_YOUNG_OFFENDER_INSTITUTION("FYI", "Feltham Young Offender Institution"),
  FELTHAM_PRISON("FMI", "Feltham Prison"),
  FIVE_WELLS_PRISON("FWI", "Five Wells Prison"),
  FORD_PRISON("FDI", "Ford Prison"),
  FOREST_BANK_PRISON("FBI", "Forest Bank Prison"),
  FOSSE_WAY_PRISON("FEI", "Fosse Way Prison"),
  FOSTON_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION("FHI", "Foston Hall Prison and Young Offender Institution"),
  FRANKLAND_PRISON("FKI", "Frankland Prison"),
  FULL_SUTTON_PRISON("FNI", "Full Sutton Prison"),
  GARTH_PRISON("GHI", "Garth Prison"),
  GARTREE_PRISON("GTI", "Gartree Prison"),
  GRENDON_PRISON("GNI", "Grendon Prison"),
  GUYS_MARSH_PRISON("GMI", "Guys Marsh Prison"),
  HATFIELD_PRISON("HDI", "Hatfield Prison"),
  HAVERIGG_PRISON("HVI", "Haverigg Prison"),
  HEWELL_PRISON("HEI", "Hewell Prison"),
  HIGH_DOWN_PRISON("HOI", "High Down Prison"),
  HIGHPOINT_PRISON("HPI", "Highpoint Prison"),
  HINDLEY_PRISON("HII", "Hindley Prison"),
  HOLLESLEY_BAY_PRISON("HBI", "Hollesley Bay Prison"),
  HOLME_HOUSE_PRISON("HHI", "Holme House Prison"),
  HULL_PRISON("HLI", "Hull Prison"),
  HUMBER_PRISON("HMI", "Humber Prison"),
  HUNTERCOMBE_PRISON("HCI", "Huntercombe Prison"),
  ISIS_PRISON("ISI", "Isis Prison"),
  ISLE_OF_WIGHT_PRISON("IWI", "Isle of Wight Prison"),
  KIRKHAM_PRISON("KMI", "Kirkham Prison"),
  KIRKLEVINGTON_GRANGE_PRISON("KVI", "Kirklevington Grange Prison"),
  LANCASTER_FARMS_PRISON("LFI", "Lancaster Farms Prison"),
  LEEDS_PRISON("LEI", "Leeds Prison"),
  LEICESTER_PRISON("LCI", "Leicester Prison"),
  LEWES_PRISON("LWI", "Lewes Prison"),
  LEYHILL_PRISON("LYI", "Leyhill Prison"),
  LINCOLN_PRISON("LII", "Lincoln Prison"),
  LINDHOLME_PRISON("LHI", "Lindholme Prison"),
  LITTLEHEY_PRISON("LTI", "Littlehey Prison"),
  LIVERPOOL_PRISON("LPI", "Liverpool Prison"),
  LONG_LARTIN_PRISON("LLI", "Long Lartin Prison"),
  LOW_NEWTON_PRISON_AND_YOUNG_OFFENDER_INSTITUTION("LNI", "Low Newton Prison and Young Offender Institution"),
  LOWDHAM_GRANGE_PRISON("LGI", "Lowdham Grange Prison"),
  MAIDSTONE_PRISON("MSI", "Maidstone Prison"),
  MANCHESTER_PRISON("MRI", "Manchester Prison"),
  MOORLAND_PRISON("MDI", "Moorland Prison"),
  MORTON_HALL_PRISON("MHI", "Morton Hall Prison"),
  NEW_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION("NHI", "New Hall Prison and Young Offender Institution"),
  NORTH_SEA_CAMP_PRISON("NSI", "North Sea Camp Prison"),
  NORTHUMBERLAND_PRISON("NLI", "Northumberland Prison"),
  NORWICH_PRISON("NWI", "Norwich Prison"),
  NOTTINGHAM_PRISON("NMI", "Nottingham Prison"),
  OAKWOOD_PRISON("OWI", "Oakwood Prison"),
  ONLEY_PRISON("ONI", "Onley Prison"),
  PARC_PRISON_AND_YOUNG_OFFENDER_INSTITUTION("PRI", "Parc Prison and Young Offender Institute"),
  PENTONVILLE_PRISON("PVI", "Pentonville Prison"),
  PETERBOROUGH_PRISON("PBI", "Peterborough Prison"),
  PORTLAND_PRISON_AND_YOUNG_OFFENDER_INSTITUTION("PDI", "Portland Prison and Young Offender Institution"),
  PRESCOED_PRISON("UPI", "Prescoed Prison"),
  PRESTON_PRISON("PNI", "Preston Prison"),
  RANBY_PRISON("RNI", "Ranby Prison"),
  RISLEY_PRISON("RSI", "Risley Prison"),
  ROCHESTER_PRISON("RCI", "Rochester Prison"),
  RYE_HILL_PRISON("RHI", "Rye Hill Prison"),
  SEND_PRISON("SDI", "Send Prison"),
  SPRING_HILL_PRISON("SPI", "Spring Hill Prison"),
  STAFFORD_PRISON("SFI", "Stafford Prison"),
  STANDFORD_HILL_PRISON("EHI", "Standford Hill Prison"),
  STOCKEN_PRISON("SKI", "Stocken Prison"),
  STOKE_HEATH_PRISON("SHI", "Stoke Heath Prison"),
  STYAL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION("STI", "Styal Prison and Young Offender Institution"),
  SUDBURY_PRISON("SUI", "Sudbury Prison"),
  SWALESIDE_PRISON("SLI", "Swaleside Prison"),
  SWANSEA_PRISON("SWI", "Swansea Prison"),
  SWINFEN_HALL_PRISON("SNI", "Swinfen Hall Prison"),
  THAMESIDE_PRISON("TSI", "Thameside Prison"),
  THE_MOUNT_PRISON("MTI", "The Mount Prison"),
  THE_VERNE_PRISON("VEI", "The Verne Prison"),
  THORN_CROSS_PRISON("TCI", "Thorn Cross Prison"),
  USK_PRISON("UKI", "Usk Prison"),
  WAKEFIELD_PRISON("WDI", "Wakefield Prison"),
  WANDSWORTH_PRISON("WWI", "Wandsworth Prison"),
  WARREN_HILL_PRISON("WII", "Warren Hill Prison"),
  WAYLAND_PRISON("WLI", "Wayland Prison"),
  WEALSTUN_PRISON("WEI", "Wealstun Prison"),
  WERRINGTON_YOUNG_OFFENDER_INSTITUTION("WNI", "Werrington Young Offender Institution"),
  WETHERBY_YOUNG_OFFENDER_INSTITUTION("WYI", "Wetherby Young Offender Institution"),
  WHATTON_PRISON("WTI", "Whatton Prison"),
  WHITEMOOR_PRISON("WRI", "Whitemoor Prison"),
  WINCHESTER_PRISON("WCI", "Winchester Prison"),
  WOODHILL_PRISON("WHI", "Woodhill Prison"),
  WORMWOOD_SCRUBS_PRISON("WSI", "Wormwood Scrubs Prison"),
  WYMOTT_PRISON("WMI", "Wymott Prison"),
  ;

  companion object {
    val PRISONS_IN_PILOT = listOf(
      CARDIFF_PRISON,
      FOSSE_WAY_PRISON,
      PETERBOROUGH_PRISON,
      RANBY_PRISON,
      SUDBURY_PRISON,
      SWANSEA_PRISON,
    )

    fun from(value: String?): Prison? = Prison.entries.firstOrNull {
      it.name == value
    }

    fun fromId(id: String?): Prison? = entries.find { it.id.equals(id, ignoreCase = true) }
  }
}
