package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.model.enums

import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource
import uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.models.enums.Prison

class PrisonTest {

  companion object {
    @JvmStatic
    fun prisonIdProvider(): List<Arguments> = listOf(
      Arguments.of("ACI", Prison.ALTCOURSE_PRISON),
      Arguments.of("ASI", Prison.ASHFIELD_PRISON),
      Arguments.of("AGI", Prison.ASKHAM_GRANGE_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("AYI", Prison.AYLESBURY_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("BFI", Prison.BEDFORD_PRISON),
      Arguments.of("BAI", Prison.BELMARSH_PRISON),
      Arguments.of("BWI", Prison.BERWYN_PRISON),
      Arguments.of("BMI", Prison.BIRMINGHAM_PRISON),
      Arguments.of("BSI", Prison.BRINSFORD_PRISON),
      Arguments.of("BLI", Prison.BRISTOL_PRISON),
      Arguments.of("BXI", Prison.BRIXTON_PRISON),
      Arguments.of("BZI", Prison.BRONZEFIELD_PRISON),
      Arguments.of("BCI", Prison.BUCKLEY_HALL_PRISON),
      Arguments.of("BNI", Prison.BULLINGDON_PRISON),
      Arguments.of("BRI", Prison.BURE_PRISON),
      Arguments.of("CFI", Prison.CARDIFF_PRISON),
      Arguments.of("CWI", Prison.CHANNINGS_WOOD_PRISON),
      Arguments.of("CDI", Prison.CHELMSFORD_PRISON),
      Arguments.of("CLI", Prison.COLDINGLEY_PRISON),
      Arguments.of("CKI", Prison.COOKHAM_WOOD_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("CKI", Prison.COOKHAM_WOOD_PRISON),
      Arguments.of("DAI", Prison.DARTMOOR_PRISON),
      Arguments.of("DTI", Prison.DEERBOLT_PRISON),
      Arguments.of("DNI", Prison.DONCASTER_PRISON),
      Arguments.of("DGI", Prison.DOVEGATE_PRISON),
      Arguments.of("DWI", Prison.DOWNVIEW_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("DHI", Prison.DRAKE_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("DMI", Prison.DURHAM_PRISON),
      Arguments.of("ESI", Prison.EAST_SUTTON_PARK_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("EWI", Prison.EASTWOOD_PARK_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("EYI", Prison.ELMLEY_PRISON),
      Arguments.of("EEI", Prison.ERLESTOKE_PRISON),
      Arguments.of("EXI", Prison.EXETER_PRISON),
      Arguments.of("FSI", Prison.FEATHERSTONE_PRISON),
      Arguments.of("FYI", Prison.FELTHAM_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("FMI", Prison.FELTHAM_PRISON),
      Arguments.of("FWI", Prison.FIVE_WELLS_PRISON),
      Arguments.of("FDI", Prison.FORD_PRISON),
      Arguments.of("FEI", Prison.FOSSE_WAY_PRISON),
      Arguments.of("FBI", Prison.FOREST_BANK_PRISON),
      Arguments.of("FHI", Prison.FOSTON_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("FKI", Prison.FRANKLAND_PRISON),
      Arguments.of("FNI", Prison.FULL_SUTTON_PRISON),
      Arguments.of("GHI", Prison.GARTH_PRISON),
      Arguments.of("GTI", Prison.GARTREE_PRISON),
      Arguments.of("GNI", Prison.GRENDON_PRISON),
      Arguments.of("GMI", Prison.GUYS_MARSH_PRISON),
      Arguments.of("HDI", Prison.HATFIELD_PRISON),
      Arguments.of("HVI", Prison.HAVERIGG_PRISON),
      Arguments.of("HEI", Prison.HEWELL_PRISON),
      Arguments.of("HOI", Prison.HIGH_DOWN_PRISON),
      Arguments.of("HPI", Prison.HIGHPOINT_PRISON),
      Arguments.of("HII", Prison.HINDLEY_PRISON),
      Arguments.of("HBI", Prison.HOLLESLEY_BAY_PRISON),
      Arguments.of("HHI", Prison.HOLME_HOUSE_PRISON),
      Arguments.of("HLI", Prison.HULL_PRISON),
      Arguments.of("HMI", Prison.HUMBER_PRISON),
      Arguments.of("HCI", Prison.HUNTERCOMBE_PRISON),
      Arguments.of("ISI", Prison.ISIS_PRISON),
      Arguments.of("IWI", Prison.ISLE_OF_WIGHT_PRISON),
      Arguments.of("KMI", Prison.KIRKHAM_PRISON),
      Arguments.of("KVI", Prison.KIRKLEVINGTON_GRANGE_PRISON),
      Arguments.of("LFI", Prison.LANCASTER_FARMS_PRISON),
      Arguments.of("LEI", Prison.LEEDS_PRISON),
      Arguments.of("LCI", Prison.LEICESTER_PRISON),
      Arguments.of("LWI", Prison.LEWES_PRISON),
      Arguments.of("LYI", Prison.LEYHILL_PRISON),
      Arguments.of("LII", Prison.LINCOLN_PRISON),
      Arguments.of("LHI", Prison.LINDHOLME_PRISON),
      Arguments.of("LTI", Prison.LITTLEHEY_PRISON),
      Arguments.of("LPI", Prison.LIVERPOOL_PRISON),
      Arguments.of("LLI", Prison.LONG_LARTIN_PRISON),
      Arguments.of("LNI", Prison.LOW_NEWTON_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("LGI", Prison.LOWDHAM_GRANGE_PRISON),
      Arguments.of("MSI", Prison.MAIDSTONE_PRISON),
      Arguments.of("MRI", Prison.MANCHESTER_PRISON),
      Arguments.of("MKI", Prison.MILLSIKE_PRISON),
      Arguments.of("MDI", Prison.MOORLAND_PRISON),
      Arguments.of("MHI", Prison.MORTON_HALL_PRISON),
      Arguments.of("NHI", Prison.NEW_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("NSI", Prison.NORTH_SEA_CAMP_PRISON),
      Arguments.of("NLI", Prison.NORTHUMBERLAND_PRISON),
      Arguments.of("NWI", Prison.NORWICH_PRISON),
      Arguments.of("NMI", Prison.NOTTINGHAM_PRISON),
      Arguments.of("OWI", Prison.OAKWOOD_PRISON),
      Arguments.of("ONI", Prison.ONLEY_PRISON),
      Arguments.of("PRI", Prison.PARC_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("PYI", Prison.PARC_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("PVI", Prison.PENTONVILLE_PRISON),
      Arguments.of("PBI", Prison.PETERBOROUGH_PRISON),
      Arguments.of("PFI", Prison.PETERBOROUGH_PRISON),
      Arguments.of("PDI", Prison.PORTLAND_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("UPI", Prison.PRESCOED_PRISON),
      Arguments.of("PNI", Prison.PRESTON_PRISON),
      Arguments.of("RNI", Prison.RANBY_PRISON),
      Arguments.of("RSI", Prison.RISLEY_PRISON),
      Arguments.of("RCI", Prison.ROCHESTER_PRISON),
      Arguments.of("RHI", Prison.RYE_HILL_PRISON),
      Arguments.of("SDI", Prison.SEND_PRISON),
      Arguments.of("SPI", Prison.SPRING_HILL_PRISON),
      Arguments.of("SFI", Prison.STAFFORD_PRISON),
      Arguments.of("EHI", Prison.STANDFORD_HILL_PRISON),
      Arguments.of("SKI", Prison.STOCKEN_PRISON),
      Arguments.of("SHI", Prison.STOKE_HEATH_PRISON),
      Arguments.of("STI", Prison.STYAL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("SUI", Prison.SUDBURY_PRISON),
      Arguments.of("SLI", Prison.SWALESIDE_PRISON),
      Arguments.of("SWI", Prison.SWANSEA_PRISON),
      Arguments.of("SNI", Prison.SWINFEN_HALL_PRISON),
      Arguments.of("TSI", Prison.THAMESIDE_PRISON),
      Arguments.of("MTI", Prison.THE_MOUNT_PRISON),
      Arguments.of("VEI", Prison.THE_VERNE_PRISON),
      Arguments.of("TCI", Prison.THORN_CROSS_PRISON),
      Arguments.of("UKI", Prison.USK_PRISON),
      Arguments.of("WDI", Prison.WAKEFIELD_PRISON),
      Arguments.of("WWI", Prison.WANDSWORTH_PRISON),
      Arguments.of("WII", Prison.WARREN_HILL_PRISON),
      Arguments.of("WLI", Prison.WAYLAND_PRISON),
      Arguments.of("WEI", Prison.WEALSTUN_PRISON),
      Arguments.of("WNI", Prison.WERRINGTON_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("WYI", Prison.WETHERBY_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("WTI", Prison.WHATTON_PRISON),
      Arguments.of("WRI", Prison.WHITEMOOR_PRISON),
      Arguments.of("WCI", Prison.WINCHESTER_PRISON),
      Arguments.of("WHI", Prison.WOODHILL_PRISON),
      Arguments.of("WSI", Prison.WORMWOOD_SCRUBS_PRISON),
      Arguments.of("WMI", Prison.WYMOTT_PRISON),
    )
  }

  @ParameterizedTest
  @MethodSource("prisonIdProvider")
  fun `fromId should return correct PrisonDDv5 for each id`(id: String, expectedPrison: Prison) {
    val result = Prison.fromId(id)

    assert(result.contains(expectedPrison))
  }
}
