package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.model.enums

import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource
import uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.models.enums.PrisonDDv5


class PrisonDDv5Test {

  companion object {
    @JvmStatic
    fun prisonIdProvider(): List<Arguments> = listOf(
      Arguments.of("ACI", PrisonDDv5.ALTCOURSE_PRISON),
      Arguments.of("ASI", PrisonDDv5.ASHFIELD_PRISON),
      Arguments.of("AGI", PrisonDDv5.ASKHAM_GRANGE_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("AYI", PrisonDDv5.AYLESBURY_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("BFI", PrisonDDv5.BEDFORD_PRISON),
      Arguments.of("BAI", PrisonDDv5.BELMARSH_PRISON),
      Arguments.of("BWI", PrisonDDv5.BERWYN_PRISON),
      Arguments.of("BMI", PrisonDDv5.BIRMINGHAM_PRISON),
      Arguments.of("BSI", PrisonDDv5.BRINSFORD_PRISON),
      Arguments.of("BLI", PrisonDDv5.BRISTOL_PRISON),
      Arguments.of("BXI", PrisonDDv5.BRIXTON_PRISON),
      Arguments.of("BZI", PrisonDDv5.BRONZEFIELD_PRISON),
      Arguments.of("BCI", PrisonDDv5.BUCKLEY_HALL_PRISON),
      Arguments.of("BNI", PrisonDDv5.BULLINGDON_PRISON),
      Arguments.of("BRI", PrisonDDv5.BURE_PRISON),
      Arguments.of("CFI", PrisonDDv5.CARDIFF_PRISON),
      Arguments.of("CWI", PrisonDDv5.CHANNINGS_WOOD_PRISON),
      Arguments.of("CDI", PrisonDDv5.CHELMSFORD_PRISON),
      Arguments.of("CLI", PrisonDDv5.COLDINGLEY_PRISON),
      Arguments.of("CKI", PrisonDDv5.COOKHAM_WOOD_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("CKI", PrisonDDv5.COOKHAM_WOOD_PRISON),
      Arguments.of("DAI", PrisonDDv5.DARTMOOR_PRISON),
      Arguments.of("DTI", PrisonDDv5.DEERBOLT_PRISON),
      Arguments.of("DNI", PrisonDDv5.DONCASTER_PRISON),
      Arguments.of("DGI", PrisonDDv5.DOVEGATE_PRISON),
      Arguments.of("DWI", PrisonDDv5.DOWNVIEW_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("DHI", PrisonDDv5.DRAKE_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("DMI", PrisonDDv5.DURHAM_PRISON),
      Arguments.of("ESI", PrisonDDv5.EAST_SUTTON_PARK_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("EWI", PrisonDDv5.EASTWOOD_PARK_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("EYI", PrisonDDv5.ELMLEY_PRISON),
      Arguments.of("EEI", PrisonDDv5.ERLESTOKE_PRISON),
      Arguments.of("EXI", PrisonDDv5.EXETER_PRISON),
      Arguments.of("FSI", PrisonDDv5.FEATHERSTONE_PRISON),
      Arguments.of("FYI", PrisonDDv5.FELTHAM_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("FMI", PrisonDDv5.FELTHAM_PRISON),
      Arguments.of("FWI", PrisonDDv5.FIVE_WELLS_PRISON),
      Arguments.of("FDI", PrisonDDv5.FORD_PRISON),
      Arguments.of("FEI", PrisonDDv5.FOSSE_WAY_PRISON),
      Arguments.of("FBI", PrisonDDv5.FOREST_BANK_PRISON),
      Arguments.of("FHI", PrisonDDv5.FOSTON_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("FKI", PrisonDDv5.FRANKLAND_PRISON),
      Arguments.of("FNI", PrisonDDv5.FULL_SUTTON_PRISON),
      Arguments.of("GHI", PrisonDDv5.GARTH_PRISON),
      Arguments.of("GTI", PrisonDDv5.GARTREE_PRISON),
      Arguments.of("GNI", PrisonDDv5.GRENDON_PRISON),
      Arguments.of("GMI", PrisonDDv5.GUYS_MARSH_PRISON),
      Arguments.of("HDI", PrisonDDv5.HATFIELD_PRISON),
      Arguments.of("HVI", PrisonDDv5.HAVERIGG_PRISON),
      Arguments.of("HEI", PrisonDDv5.HEWELL_PRISON),
      Arguments.of("HOI", PrisonDDv5.HIGH_DOWN_PRISON),
      Arguments.of("HPI", PrisonDDv5.HIGHPOINT_PRISON),
      Arguments.of("HII", PrisonDDv5.HINDLEY_PRISON),
      Arguments.of("HBI", PrisonDDv5.HOLLESLEY_BAY_PRISON),
      Arguments.of("HHI", PrisonDDv5.HOLME_HOUSE_PRISON),
      Arguments.of("HLI", PrisonDDv5.HULL_PRISON),
      Arguments.of("HMI", PrisonDDv5.HUMBER_PRISON),
      Arguments.of("HCI", PrisonDDv5.HUNTERCOMBE_PRISON),
      Arguments.of("ISI", PrisonDDv5.ISIS_PRISON),
      Arguments.of("IWI", PrisonDDv5.ISLE_OF_WIGHT_PRISON),
      Arguments.of("KMI", PrisonDDv5.KIRKHAM_PRISON),
      Arguments.of("KVI", PrisonDDv5.KIRKLEVINGTON_GRANGE_PRISON),
      Arguments.of("LFI", PrisonDDv5.LANCASTER_FARMS_PRISON),
      Arguments.of("LEI", PrisonDDv5.LEEDS_PRISON),
      Arguments.of("LCI", PrisonDDv5.LEICESTER_PRISON),
      Arguments.of("LWI", PrisonDDv5.LEWES_PRISON),
      Arguments.of("LYI", PrisonDDv5.LEYHILL_PRISON),
      Arguments.of("LII", PrisonDDv5.LINCOLN_PRISON),
      Arguments.of("LHI", PrisonDDv5.LINDHOLME_PRISON),
      Arguments.of("LTI", PrisonDDv5.LITTLEHEY_PRISON),
      Arguments.of("LPI", PrisonDDv5.LIVERPOOL_PRISON),
      Arguments.of("LLI", PrisonDDv5.LONG_LARTIN_PRISON),
      Arguments.of("LNI", PrisonDDv5.LOW_NEWTON_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("LGI", PrisonDDv5.LOWDHAM_GRANGE_PRISON),
      Arguments.of("MSI", PrisonDDv5.MAIDSTONE_PRISON),
      Arguments.of("MRI", PrisonDDv5.MANCHESTER_PRISON),
      Arguments.of("MKI", PrisonDDv5.MILLSIKE_PRISON),
      Arguments.of("MDI", PrisonDDv5.MOORLAND_PRISON),
      Arguments.of("MHI", PrisonDDv5.MORTON_HALL_PRISON),
      Arguments.of("NHI", PrisonDDv5.NEW_HALL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("NSI", PrisonDDv5.NORTH_SEA_CAMP_PRISON),
      Arguments.of("NLI", PrisonDDv5.NORTHUMBERLAND_PRISON),
      Arguments.of("NWI", PrisonDDv5.NORWICH_PRISON),
      Arguments.of("NMI", PrisonDDv5.NOTTINGHAM_PRISON),
      Arguments.of("OWI", PrisonDDv5.OAKWOOD_PRISON),
      Arguments.of("ONI", PrisonDDv5.ONLEY_PRISON),
      Arguments.of("PRI", PrisonDDv5.PARC_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("PYI", PrisonDDv5.PARC_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("PVI", PrisonDDv5.PENTONVILLE_PRISON),
      Arguments.of("PBI", PrisonDDv5.PETERBOROUGH_PRISON),
      Arguments.of("PFI", PrisonDDv5.PETERBOROUGH_PRISON),
      Arguments.of("PDI", PrisonDDv5.PORTLAND_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("UPI", PrisonDDv5.PRESCOED_PRISON),
      Arguments.of("PNI", PrisonDDv5.PRESTON_PRISON),
      Arguments.of("RNI", PrisonDDv5.RANBY_PRISON),
      Arguments.of("RSI", PrisonDDv5.RISLEY_PRISON),
      Arguments.of("RCI", PrisonDDv5.ROCHESTER_PRISON),
      Arguments.of("RHI", PrisonDDv5.RYE_HILL_PRISON),
      Arguments.of("SDI", PrisonDDv5.SEND_PRISON),
      Arguments.of("SPI", PrisonDDv5.SPRING_HILL_PRISON),
      Arguments.of("SFI", PrisonDDv5.STAFFORD_PRISON),
      Arguments.of("EHI", PrisonDDv5.STANDFORD_HILL_PRISON),
      Arguments.of("SKI", PrisonDDv5.STOCKEN_PRISON),
      Arguments.of("SHI", PrisonDDv5.STOKE_HEATH_PRISON),
      Arguments.of("STI", PrisonDDv5.STYAL_PRISON_AND_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("SUI", PrisonDDv5.SUDBURY_PRISON),
      Arguments.of("SLI", PrisonDDv5.SWALESIDE_PRISON),
      Arguments.of("SWI", PrisonDDv5.SWANSEA_PRISON),
      Arguments.of("SNI", PrisonDDv5.SWINFEN_HALL_PRISON),
      Arguments.of("TSI", PrisonDDv5.THAMESIDE_PRISON),
      Arguments.of("MTI", PrisonDDv5.THE_MOUNT_PRISON),
      Arguments.of("VEI", PrisonDDv5.THE_VERNE_PRISON),
      Arguments.of("TCI", PrisonDDv5.THORN_CROSS_PRISON),
      Arguments.of("UKI", PrisonDDv5.USK_PRISON),
      Arguments.of("WDI", PrisonDDv5.WAKEFIELD_PRISON),
      Arguments.of("WWI", PrisonDDv5.WANDSWORTH_PRISON),
      Arguments.of("WII", PrisonDDv5.WARREN_HILL_PRISON),
      Arguments.of("WLI", PrisonDDv5.WAYLAND_PRISON),
      Arguments.of("WEI", PrisonDDv5.WEALSTUN_PRISON),
      Arguments.of("WNI", PrisonDDv5.WERRINGTON_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("WYI", PrisonDDv5.WETHERBY_YOUNG_OFFENDER_INSTITUTION),
      Arguments.of("WTI", PrisonDDv5.WHATTON_PRISON),
      Arguments.of("WRI", PrisonDDv5.WHITEMOOR_PRISON),
      Arguments.of("WCI", PrisonDDv5.WINCHESTER_PRISON),
      Arguments.of("WHI", PrisonDDv5.WOODHILL_PRISON),
      Arguments.of("WSI", PrisonDDv5.WORMWOOD_SCRUBS_PRISON),
      Arguments.of("WMI", PrisonDDv5.WYMOTT_PRISON)
    )
  }

  @ParameterizedTest
  @MethodSource("prisonIdProvider")
  fun `fromId should return correct PrisonDDv5 for each id`(id: String, expectedPrison: PrisonDDv5) {
    val result = PrisonDDv5.fromId(id)

    assert(result.contains(expectedPrison))
  }
}
