package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.model.enums.ddv5

enum class CrownCourtDDv5(val value: String) {
  AMERSHAM_CROWN_COURT("Amersham Crown Court"),
  AYLESBURY_CROWN_COURT("Aylesbury Crown Court"),
  BARBICAN_ALDERSGATE_HOUSE_CROWN_COURT("Barbican (Aldersgate House) Crown Court"),
  BARNSTAPLE_CROWN_COURT("Barnstaple Crown Court"),
  BARROW_IN_FURNESS_CROWN_COURT("Barrow in Furness Crown Court"),
  BASILDON_CROWN_COURT("Basildon Crown Court"),
  BIRMINGHAM_CROWN_COURT("Birmingham Crown Court"),
  BLACKFRIARS_CROWN_COURT("Blackfriars Crown Court"),
  BOLTON_CROWN_COURT("Bolton Crown Court"),
  BOURNEMOUTH_CROWN_COURT("Bournemouth Crown Court"),
  BRADFORD_CROWN_COURT("Bradford Crown Court"),
  BRISTOL_CROWN_COURT("Bristol Crown Court"),
  BURNLEY_CROWN_COURT("Burnley Crown Court"),
  BURY_ST_EDMUNDS_CROWN_COURT("Bury St Edmunds Crown Court"),
  CAERNARFON_CROWN_COURT("Caernarfon Crown Court"),
  CAMBRIDGE_CROWN_COURT("Cambridge Crown Court"),
  CANTERBURY_CROWN_COURT("Canterbury Crown Court"),
  CARDIFF_CROWN_COURT("Cardiff Crown Court"),
  CARLISLE_CROWN_COURT("Carlisle Crown Court"),
  CARMARTHEN_CROWN_COURT("Carmarthen Crown Court"),
  CHELMSFORD_CROWN_COURT("Chelmsford Crown Court"),
  CHESTER_CROWN_COURT("Chester Crown Court"),
  CHICHESTER_CROWN_COURT("Chichester Crown Court"),
  CIRENCESTER_GLOUCESTER_CROWN_COURT("Cirencester (Gloucester) Crown Court"),
  COVENTRY_CROWN_COURT("Coventry Crown Court"),
  CROYDON_CROWN_COURT("Croydon Crown Court"),
  DERBY_CROWN_COURT("Derby Crown Court"),
  DOLGELLAU_CROWN_COURT("Dolgellau Crown Court"),
  DONCASTER_CROWN_COURT("Doncaster Crown Court"),
  DORCHESTER_CROWN_COURT("Dorchester Crown Court"),
  DURHAM_CROWN_COURT("Durham Crown Court"),
  EXETER_CROWN_COURT("Exeter Crown Court"),
  GLOUCESTER_CROWN_COURT("Gloucester Crown Court"),
  GRIMSBY_CROWN_COURT("Grimsby Crown Court"),
  GUILDFORD_CROWN_COURT("Guildford Crown Court"),
  HARROW_CROWN_COURT("Harrow Crown Court"),
  HAVERFORDWEST_CROWN_COURT("Haverfordwest Crown Court"),
  HEREFORD_CROWN_COURT("Hereford Crown Court"),
  INNER_LONDON_CROWN_COURT("Inner London Crown Court"),
  IPSWICH_CROWN_COURT("Ipswich Crown Court"),
  ISLEWORTH_CROWN_COURT("Isleworth Crown Court"),
  JURYS_INN_CROYDON_CROWN_COURT("Jury's Inn Croydon Crown Court"),
  KINGS_LYNN_CROWN_COURT("King's Lynn Crown Court"),
  KINGSTON_UPON_HULL_CROWN_COURT("Kingston upon Hull Crown Court"),
  KINGSTON_UPON_THAMES_CROWN_COURT("Kingston upon Thames Crown Court"),
  KNUTSFORD_CROWN_COURT("Knutsford Crown Court"),
  LANCASTER_CROWN_COURT("Lancaster Crown Court"),
  LEEDS_CROWN_COURT("Leeds Crown Court"),
  LEICESTER_CROWN_COURT("Leicester Crown Court"),
  LEWES_CROWN_COURT("Lewes Crown Court"),
  LINCOLN_CROWN_COURT("Lincoln Crown Court"),
  LIVERPOOL_CROWN_COURT("Liverpool Crown Court"),
  LOUGHBOROUGH_CROWN_COURT("Loughborough Crown Court"),
  LUTON_CROWN_COURT("Luton Crown Court"),
  MAIDSTONE_CROWN_COURT("Maidstone Crown Court"),
  MANCHESTER_CROWN_COURT_CROWN_SQUARE("Manchester Crown Court (Crown Square)"),
  MANCHESTER_CROWN_COURT_MINSHULL_ST("Manchester Crown Court (Minshull St)"),
  MERTHYR_TYDFIL_CROWN_COURT("Merthyr Tydfil Crown Court"),
  MIDDLESEX_GUILDHALL_CROWN_COURT("Middlesex Guildhall Crown Court"),
  MINSHULL_STREET_MANCHESTER__CROWN_COURT("Minshull Street Manchester  Crown Court"),
  MOLD_CROWN_COURT("Mold Crown Court"),
  MONUMENT_CROWN_COURT("Monument Crown Court"),
  NEWCASTLE_UPON_TYNE_CROWN_COURT("Newcastle upon Tyne Crown Court"),
  NEWPORT_SOUTH_WALES_CROWN_COURT("Newport (South Wales) Crown Court"),
  NORTHAMPTON_CROWN_COURT("Northampton Crown Court"),
  NORWICH_CROWN_COURT("Norwich Crown Court"),
  NOTTINGHAM_CROWN_COURT("Nottingham Crown Court"),
  OXFORD_CROWN_COURT("Oxford Crown Court"),
  PETERBOROUGH_CROWN_COURT("Peterborough Crown Court"),
  PLYMOUTH_CROWN_COURT("Plymouth Crown Court"),
  PORTSMOUTH_CROWN_COURT("Portsmouth Crown Court"),
  PRESTON_CROWN_COURT("Preston Crown Court"),
  PRESTON_NORTH_END_CROWN_COURT_CROWN_COURT("Preston North End Crown Court Crown Court"),
  READING_CROWN_COURT("Reading Crown Court"),
  ROYAL_COURTS_OF_JUSTICE_CROWN_COURT("Royal Courts of Justice Crown Court"),
  SALFORD_LOWRY_THEATRE_CROWN_COURT("Salford Lowry Theatre Crown Court"),
  SALISBURY_CROWN_COURT("Salisbury Crown Court"),
  SHEFFIELD_CROWN_COURT("Sheffield Crown Court"),
  SHREWSBURY_CROWN_COURT("Shrewsbury Crown Court"),
  SNARESBROOK_CROWN_COURT("Snaresbrook Crown Court"),
  SOUTHAMPTON_CROWN_COURT("Southampton Crown Court"),
  SOUTHEND_CROWN_COURT("Southend Crown Court"),
  SOUTHWARK_CROWN_COURT("Southwark Crown Court"),
  ST_ALBANS_CROWN_COURT("St Albans Crown Court"),
  STAFFORD_CROWN_COURT("Stafford Crown Court"),
  STOKE_CROWN_COURT("Stoke Crown Court"),
  SWANSEA_CROWN_COURT("Swansea Crown Court"),
  SWINDON_CROWN_COURT("Swindon Crown Court"),
  TAUNTON_CROWN_COURT("Taunton Crown Court"),
  TEESSIDE_CROWN_COURT("Teesside Crown Court"),
  TRURO_CROWN_COURT("Truro Crown Court"),
  WARRINGTON_CROWN_COURT("Warrington Crown Court"),
  WARWICK_CROWN_COURT("Warwick Crown Court"),
  WELSHPOOL_CROWN_COURT("Welshpool Crown Court"),
  WEYMOUTH_CROWN_COURT("Weymouth Crown Court"),
  WINCHESTER_CROWN_COURT("Winchester Crown Court"),
  WOLVERHAMPTON_CROWN_COURT("Wolverhampton Crown Court"),
  WOOD_GREEN_CROWN_COURT("Wood Green Crown Court"),
  WOOLWICH_CROWN_COURT("Woolwich Crown Court"),
  WORCESTER_CROWN_COURT("Worcester Crown Court"),
  YORK_CROWN_COURT("York Crown Court"),
  ;

  companion object {
    fun from(value: String?): CrownCourtDDv5? = entries.firstOrNull {
      it.name == value
    }
  }
}
