package uk.gov.justice.digital.hmpps.hmppselectronicmonitoringcreateanorderapi.model.enums.ddv5

enum class MagistrateCourtDDv5(val value: String) {
  ABERDARE_MAGISTRATES_COURT("Aberdare Magistrates Court"),
  ABERGAVENNY_MAGISTRATES_COURT("Abergavenny Magistrates Court"),
  ABERTILLERY_MAGISTRATES_COURT("Abertillery Magistrates Court"),
  ABERYSTWYTH_MAGISTRATES_COURT("Aberystwyth Magistrates Court"),
  ACCRINGTON_MAGISTRATES_COURT("Accrington Magistrates Court"),
  ACTON_MAGISTRATES_COURT("Acton Magistrates Court"),
  AIT_STOKE_ON_TRENT_MAGISTRATES_COURT("AIT Stoke-on-Trent Magistrates Court"),
  ALDERSHOT_MAGISTRATES_COURT("Aldershot Magistrates Court"),
  ALNWICK_MAGISTRATES_COURT("Alnwick Magistrates Court"),
  ALTON_MAGISTRATES_COURT("Alton Magistrates Court"),
  AMERSHAM_MAGISTRATES_COURT("Amersham Magistrates Court"),
  AMMANFORD_MAGISTRATES_COURT("Ammanford Magistrates Court"),
  ANDOVER_MAGISTRATES_COURT("Andover Magistrates Court"),
  ASHFORD_MAGISTRATES_COURT("Ashford Magistrates Court"),
  ATHERSTONE_MAGISTRATES_COURT("Atherstone Magistrates Court"),
  AYLESBURY_MAGISTRATES_COURT("Aylesbury Magistrates Court"),
  BANBURY_MAGISTRATES_COURT("Banbury Magistrates Court"),
  BANGOR_MAGISTRATES_COURT("Bangor Magistrates Court"),
  BARKINGSIDE_MAGISTRATES_COURT("Barkingside Magistrates Court"),
  BARNET_MAGISTRATES_COURT("Barnet Magistrates Court"),
  BARNSLEY_MAGISTRATES_COURT("Barnsley Magistrates Court"),
  BARNSTAPLE_MAGISTRATES_COURT("Barnstaple Magistrates Court"),
  BARROW_IN_FURNESS_MAGISTRATES_COURT("Barrow-in-Furness Magistrates Court"),
  BARRY_MAGISTRATES_COURT("Barry Magistrates Court"),
  BASILDON_MAGISTRATES_COURT("Basildon Magistrates Court"),
  BASINGSTOKE_MAGISTRATES_COURT("Basingstoke Magistrates Court"),
  BATH_MAGISTRATES_COURT("Bath Magistrates Court"),
  BEDFORD_MAGISTRATES_COURT("Bedford Magistrates Court"),
  BEDLINGTON_MAGISTRATES_COURT("Bedlington Magistrates Court"),
  BELMARSH_MAGISTRATES_COURT("Belmarsh Magistrates Court"),
  BERWICK_UPON_TWEED_MAGISTRATES_COURT("Berwick upon Tweed Magistrates Court"),
  BEVERLEY_MAGISTRATES_COURT("Beverley Magistrates Court"),
  BEXLEY_MAGISTRATES_COURT("Bexley Magistrates Court"),
  BICESTER_MAGISTRATES_COURT("Bicester Magistrates Court"),
  BINGLEY_MAGISTRATES_COURT("Bingley Magistrates Court"),
  BIRKENHEAD_MAGISTRATES_COURT("Birkenhead Magistrates Court"),
  BIRMINGHAM_MAGISTRATES_COURT("Birmingham Magistrates Court"),
  BISHOP_AUCKLAND_MAGISTRATES_COURT("Bishop Auckland Magistrates Court"),
  BLACKBURN_MAGISTRATES_COURT("Blackburn Magistrates Court"),
  BLACKPOOL_MAGISTRATES_AND_CIVIL_COURT("Blackpool Magistrates and Civil Court "),
  BLACKPOOL_MAGISTRATES_COURT("Blackpool Magistrates Court"),
  BLACKWOOD_MAGISTRATES_COURT("Blackwood Magistrates Court"),
  BLANDFORD_FORUM_MAGISTRATES_COURT("Blandford Forum Magistrates Court"),
  BLANDFORD_MAGISTRATES_COURT("Blandford Magistrates Court"),
  BLAYDON_MAGISTRATES_COURT("Blaydon Magistrates Court"),
  BODMIN_MAGISTRATES_COURT("Bodmin Magistrates Court"),
  BOLTON_MAGISTRATES_COURT("Bolton Magistrates Court"),
  BOOTLE_MAGISTRATES_COURT("Bootle Magistrates Court"),
  BOSTON_MAGISTRATES_COURT("Boston Magistrates Court"),
  BOURNE_MAGISTRATES_COURT("Bourne Magistrates Court"),
  BOURNEMOUTH_MAGISTRATES_COURT("Bournemouth Magistrates Court"),
  BOW_STREET_MAGISTRATES_COURT("Bow Street Magistrates Court"),
  BRACKNELL_MAGISTRATES_COURT("Bracknell Magistrates Court"),
  BRADFORD_AND_KEIGHLEY_MAGISTRATES_COURT("Bradford and Keighley Magistrates Court"),
  BRADFORD_MAGISTRATES_COURT("Bradford Magistrates Court"),
  BRECON_MAGISTRATES_COURT("Brecon Magistrates Court"),
  BRENT_MAGISTRATES_COURT("Brent Magistrates Court"),
  BRENTFORD_MAGISTRATES_COURT("Brentford Magistrates Court"),
  BRIDGEND_MAGISTRATES_COURT("Bridgend Magistrates Court"),
  BRIDGNORTH_MAGISTRATES_COURT("Bridgnorth Magistrates Court"),
  BRIDGWATER_MAGISTRATES_COURT("Bridgwater Magistrates Court"),
  BRIDLINGTON_MAGISTRATES_COURT("Bridlington Magistrates Court"),
  BRIDPORT_MAGISTRATES_COURT("Bridport Magistrates Court"),
  BRIGHTON_MAGISTRATES_COURT("Brighton Magistrates Court"),
  BRISTOL_MAGISTRATES_COURT("Bristol Magistrates Court"),
  BROMLEY_MAGISTRATES_COURT("Bromley Magistrates Court"),
  BURNLEY_MAGISTRATES_COURT("Burnley Magistrates Court"),
  BURTON_UPON_TRENT_MAGISTRATES_COURT("Burton upon Trent Magistrates Court"),
  BURY_MAGISTRATES_COURT("Bury Magistrates Court"),
  BURY_ST_EDMUNDS_MAGISTRATES_COURT("Bury St Edmunds Magistrates Court"),
  BUXTON_MAGISTRATES_COURT("Buxton Magistrates Court"),
  CAERNARFON_MAGISTRATES_COURT("Caernarfon Magistrates Court"),
  CAERPHILLY_MAGISTRATES_COURT("Caerphilly Magistrates Court"),
  CAISTOR_MAGISTRATES_COURT("Caistor Magistrates Court"),
  CAMBERLEY_MAGISTRATES_COURT("Camberley Magistrates Court"),
  CAMBERWELL_GREEN_MAGISTRATES_COURT("Camberwell Green Magistrates Court"),
  CAMBORNE_MAGISTRATES_COURT("Camborne Magistrates Court"),
  CAMBRIDGE_MAGISTRATES_COURT("Cambridge Magistrates Court"),
  CANNOCK_MAGISTRATES_COURT("Cannock Magistrates Court"),
  CANTERBURY_MAGISTRATES_COURT("Canterbury Magistrates Court"),
  CARDIFF_MAGISTRATES_COURT("Cardiff Magistrates Court"),
  CARDIGAN_MAGISTRATES_COURT("Cardigan Magistrates Court"),
  CARLISLE_MAGISTRATES_COURT("Carlisle Magistrates Court"),
  CARMARTHEN_MAGISTRATES_COURT("Carmarthen Magistrates Court"),
  CASTLEFORD_MAGISTRATES_COURT("Castleford Magistrates Court"),
  CHATHAM_MAGISTRATES_COURT("Chatham Magistrates Court"),
  CHELMSFORD_MAGISTRATES_COURT("Chelmsford Magistrates Court"),
  CHELTENHAM_MAGISTRATES_COURT("Cheltenham Magistrates Court"),
  CHEPSTOW_MAGISTRATES_COURT("Chepstow Magistrates Court"),
  CHESHUNT_MAGISTRATES_COURT("Cheshunt Magistrates Court"),
  CHESTER_LE_STREET_MAGISTRATES_COURT("Chester le Street Magistrates Court"),
  CHESTER_MAGISTRATES_COURT("Chester Magistrates Court"),
  CHICHESTER_MAGISTRATES_COURT("Chichester Magistrates Court"),
  CHORLEY_MAGISTRATES_COURT("Chorley Magistrates Court"),
  CIRENCESTER_MAGISTRATES_COURT("Cirencester Magistrates Court"),
  CITY_OF_LONDON_MAGISTRATES_COURT("City of London Magistrates Court"),
  COALVILLE_MAGISTRATES_COURT("Coalville Magistrates Court"),
  COLCHESTER_MAGISTRATES_COURT("Colchester Magistrates Court"),
  COLEFORD_MAGISTRATES_COURT("Coleford Magistrates Court"),
  CONSETT_MAGISTRATES_COURT("Consett Magistrates Court"),
  CORBY_MAGISTRATES_COURT("Corby Magistrates Court"),
  COVENTRY_MAGISTRATES_COURT("Coventry Magistrates Court"),
  CRAWLEY_MAGISTRATES_COURT("Crawley Magistrates Court"),
  CREWE_SOUTH_CHESHIRE_MAGISTRATES_COURT("Crewe (South Cheshire) Magistrates Court"),
  CREWE_MAGISTRATES_COURT("Crewe Magistrates Court"),
  CROMER_MAGISTRATES_COURT("Cromer Magistrates Court"),
  CROYDON_MAGISTRATES_COURT("Croydon Magistrates Court"),
  CULLOMPTON_MAGISTRATES_COURT("Cullompton Magistrates Court"),
  CWMBRAN_MAGISTRATES_COURT("Cwmbran Magistrates Court"),
  DARLINGTON_MAGISTRATES_COURT("Darlington Magistrates Court"),
  DARTFORD_MAGISTRATES_COURT("Dartford Magistrates Court"),
  DAVENTRY_MAGISTRATES_COURT("Daventry Magistrates Court"),
  DENBIGH_MAGISTRATES_COURT("Denbigh Magistrates Court"),
  DERBY_MAGISTRATES_COURT("Derby Magistrates Court"),
  DEVIZES_MAGISTRATES_COURT("Devizes Magistrates Court"),
  DEWSBURY_MAGISTRATES_COURT("Dewsbury Magistrates Court"),
  DIDCOT_MAGISTRATES_COURT("Didcot Magistrates Court"),
  DOLGELLAU_MAGISTRATES_COURT("Dolgellau Magistrates Court"),
  DONCASTER_MAGISTRATES_COURT("Doncaster Magistrates Court"),
  DORCHESTER_MAGISTRATES_COURT("Dorchester Magistrates Court"),
  DORKING_MAGISTRATES_COURT("Dorking Magistrates Court"),
  DOVER_MAGISTRATES_COURT("Dover Magistrates Court"),
  DROITWICH_MAGISTRATES_COURT("Droitwich Magistrates Court"),
  DUDLEY_MAGISTRATES_COURT("Dudley Magistrates Court"),
  DURHAM_MAGISTRATES_COURT("Durham Magistrates Court"),
  EALING_MAGISTRATES_COURT("Ealing Magistrates Court"),
  EAST_BERKSHIRE_MAGISTRATES_COURT_SLOUGH("East Berkshire Magistrates Court, Slough"),
  EASTBOURNE_MAGISTRATES_COURT("Eastbourne Magistrates Court"),
  EASTLEIGH_MAGISTRATES_COURT("Eastleigh Magistrates Court"),
  ELY_MAGISTRATES_COURT("Ely Magistrates Court"),
  ENFIELD_MAGISTRATES_COURT("Enfield Magistrates Court"),
  EPPING_MAGISTRATES_COURT("Epping Magistrates Court"),
  EPSOM_MAGISTRATES_COURT("Epsom Magistrates Court"),
  EVESHAM_MAGISTRATES_COURT("Evesham Magistrates Court"),
  EXETER_MAGISTRATES_COURT("Exeter Magistrates Court"),
  FAREHAM_MAGISTRATES_COURT("Fareham Magistrates Court"),
  FELTHAM_MAGISTRATES_COURT("Feltham Magistrates Court"),
  FLAX_BOURTON_MAGISTRATES_COURT("Flax Bourton Magistrates Court"),
  FLEETWOOD_MAGISTRATES_COURT("Fleetwood Magistrates Court"),
  FLINT_MAGISTRATES_COURT("Flint Magistrates Court"),
  FOLKESTONE_MAGISTRATES_COURT("Folkestone Magistrates Court"),
  FROME_MAGISTRATES_COURT("Frome Magistrates Court"),
  GAINSBOROUGH_MAGISTRATES_COURT("Gainsborough Magistrates Court"),
  GATESHEAD_MAGISTRATES_COURT("Gateshead Magistrates Court"),
  GLOSSOP_MAGISTRATES_COURT("Glossop Magistrates Court"),
  GLOUCESTER_MAGISTRATES_COURT("Gloucester Magistrates Court"),
  GOOLE_MAGISTRATES_COURT("Goole Magistrates Court"),
  GOSFORTH_MAGISTRATES_COURT("Gosforth Magistrates Court"),
  GOWERTON_MAGISTRATES_COURT("Gowerton Magistrates Court"),
  GRANTHAM_MAGISTRATES_COURT("Grantham Magistrates Court"),
  GRAYS_MAGISTRATES_COURT("Grays Magistrates Court"),
  GREAT_YARMOUTH_MAGISTRATES_COURT("Great Yarmouth Magistrates Court"),
  GREENWICH_MAGISTRATES_COURT("Greenwich Magistrates Court"),
  GRIMSBY_MAGISTRATES_COURT("Grimsby Magistrates Court"),
  GUILDFORD_MAGISTRATES_COURT("Guildford Magistrates Court"),
  GUISBOROUGH_MAGISTRATES_COURT("Guisborough Magistrates Court"),
  HALESOWEN_MAGISTRATES_COURT("Halesowen Magistrates Court"),
  HALIFAX_MAGISTRATES_COURT("Halifax Magistrates Court"),
  HAMMERSMITH_MAGISTRATES_COURT("Hammersmith Magistrates Court"),
  HARLOW_MAGISTRATES_COURT("Harlow Magistrates Court"),
  HARROGATE_MAGISTRATES_COURT("Harrogate Magistrates Court"),
  HARROW_MAGISTRATES_COURT("Harrow Magistrates Court"),
  HARTLEPOOL_MAGISTRATES_COURT("Hartlepool Magistrates Court"),
  HARWICH_MAGISTRATES_COURT("Harwich Magistrates Court"),
  HASTINGS_MAGISTRATES_COURT("Hastings Magistrates Court"),
  HATFIELD_MAGISTRATES_COURT("Hatfield Magistrates Court"),
  HAVANT_MAGISTRATES_COURT("Havant Magistrates Court"),
  HAVERFORDWEST_MAGISTRATES_COURT("Haverfordwest Magistrates Court"),
  HAYWARDS_HEATH_MAGISTRATES_COURT("Haywards Heath Magistrates Court"),
  HEMEL_HEMPSTEAD_MAGISTRATES_COURT("Hemel Hempstead Magistrates Court"),
  HENDON_MAGISTRATES_COURT("Hendon Magistrates Court"),
  HERTFORD_MAGISTRATES_COURT("Hertford Magistrates Court"),
  HEXHAM_MAGISTRATES_COURT("Hexham Magistrates Court"),
  HIGH_WYCOMBE_MAGISTRATES_COURT("High Wycombe Magistrates Court"),
  HIGHBURY_CORNER_MAGISTRATES_COURT("Highbury Corner Magistrates Court"),
  HIGHGATE_MAGISTRATES_COURT("Highgate Magistrates Court"),
  HINCKLEY_MAGISTRATES_COURT("Hinckley Magistrates Court"),
  HOLYHEAD_MAGISTRATES_COURT("Holyhead Magistrates Court"),
  HONITON_MAGISTRATES_COURT("Honiton Magistrates Court"),
  HORNCASTLE_MAGISTRATES_COURT("Horncastle Magistrates Court"),
  HORSEFERRY_ROAD_MAGISTRATES_COURT("Horseferry Road Magistrates Court"),
  HORSHAM_MAGISTRATES_COURT("Horsham Magistrates Court"),
  HOUGHTON_LE_SPRING_MAGISTRATES_COURT("Houghton le Spring Magistrates Court"),
  HUDDERSFIELD_MAGISTRATES_COURT("Huddersfield Magistrates Court"),
  HULL_AND_HOLDERNESS_MAGISTRATES_COURT("Hull and Holderness Magistrates Court"),
  HUNTINGDON_MAGISTRATES_COURT("Huntingdon Magistrates Court"),
  HUYTON_MAGISTRATES_COURT("Huyton Magistrates Court"),
  ILKESTON_MAGISTRATES_COURT("Ilkeston Magistrates Court"),
  IPSWICH_MAGISTRATES_COURT("Ipswich Magistrates Court"),
  ISLES_OF_SCILLY_MAGISTRATES_COURT("Isles of Scilly Magistrates Court"),
  KENDAL_MAGISTRATES_COURT("Kendal Magistrates Court"),
  KETTERING_MAGISTRATES_COURT("Kettering Magistrates Court"),
  KIDDERMINSTER_MAGISTRATES_COURT("Kidderminster Magistrates Court"),
  KINGS_LYNN_MAGISTRATES_COURT("Kings Lynn Magistrates Court"),
  KINGSTON_UPON_HULL_MAGISTRATES_COURT("Kingston upon Hull Magistrates Court"),
  KINGSTON_UPON_THAMES_MAGISTRATES_COURT("Kingston upon Thames Magistrates Court"),
  KIRKLEES_HUDDERSFIELD_MAGISTRATES_COURT("Kirklees (Huddersfield) Magistrates Court"),
  KNOWSLEY_MAGISTRATES_COURT("Knowsley Magistrates Court"),
  LANCASTER_MAGISTRATES_COURT("Lancaster Magistrates Court"),
  LAUNCESTON_MAGISTRATES_COURT("Launceston Magistrates Court"),
  LAVENDER_HILL_MAGISTRATES_COURT("Lavender Hill Magistrates Court"),
  LEAMINGTON_SPA_MAGISTRATES_COURT("Leamington Spa Magistrates Court"),
  LEEDS_MAGISTRATES_COURT("Leeds Magistrates Court"),
  LEICESTER_MAGISTRATES_COURT("Leicester Magistrates Court"),
  LEWES_MAGISTRATES_COURT("Lewes Magistrates Court"),
  LEYLAND_MAGISTRATES_COURT("Leyland Magistrates Court"),
  LINCOLN_MAGISTRATES_COURT("Lincoln Magistrates Court"),
  LISKEARD_MAGISTRATES_COURT("Liskeard Magistrates Court"),
  LIVERPOOL_AND_KNOWSLEY_MAGISTRATES_COURT("Liverpool & Knowsley Magistrates Court"),
  LLANDOVERY_MAGISTRATES_COURT("Llandovery Magistrates Court"),
  LLANDRINDOD_WELLS_MAGISTRATES_COURT("Llandrindod Wells Magistrates Court"),
  LLANDUDNO_MAGISTRATES_COURT("Llandudno Magistrates Court"),
  LLANELLI_MAGISTRATES_COURT("Llanelli Magistrates Court"),
  LLANGEFNI_MAGISTRATES_COURT("Llangefni Magistrates Court"),
  LLANTRISANT_MAGISTRATES_COURT("Llantrisant Magistrates Court"),
  LLWYNYPIA_MAGISTRATES_COURT("Llwynypia Magistrates Court"),
  LONG_SUTTON_MAGISTRATES_COURT("Long Sutton Magistrates Court"),
  LOUGHBOROUGH_MAGISTRATES_COURT("Loughborough Magistrates Court"),
  LOUTH_MAGISTRATES_COURT("Louth Magistrates Court"),
  LOWESTOFT_MAGISTRATES_COURT("Lowestoft Magistrates Court"),
  LUDLOW_MAGISTRATES_COURT("Ludlow Magistrates Court"),
  LUTON_AND_SOUTH_BEDFORDSHIRE_MAGISTRATES_COURT("Luton and South Bedfordshire Magistrates Court"),
  LUTON_MAGISTRATES_COURT("Luton Magistrates Court"),
  LYNDHURST_MAGISTRATES_COURT("Lyndhurst Magistrates Court"),
  MACHYNLLETH_MAGISTRATES_COURT("Machynlleth Magistrates Court"),
  MAIDENHEAD_MAGISTRATES_COURT("Maidenhead Magistrates Court"),
  MAIDSTONE_MAGISTRATES_COURT("Maidstone Magistrates Court"),
  MANCHESTER_CROWN_SQUARE_MAGISTRATES_COURT("Manchester (Crown Square) Magistrates Court"),
  MANCHESTER_CIVIL_JUSTICE_CENTRE_MAGISTRATES_COURT("Manchester Civil Justice Centre Magistrates Court"),
  MANCHESTER_MAGISTRATES_COURT("Manchester Magistrates Court"),
  MANSFIELD_ROSEMARY_ST_MAGISTRATES_COURT("Mansfield (Rosemary St) Magistrates Court"),
  MARGATE_MAGISTRATES_COURT("Margate Magistrates Court"),
  MARKET_DRAYTON_MAGISTRATES_COURT("Market Drayton Magistrates Court"),
  MARKET_HARBOROUGH_MAGISTRATES_COURT("Market Harborough Magistrates Court"),
  MEDWAY_MAGISTRATES_COURT("Medway Magistrates Court"),
  MELTON_MOWBRAY_MAGISTRATES_COURT("Melton Mowbray Magistrates Court"),
  MERTHYR_TYDFIL_MAGISTRATES_COURT("Merthyr Tydfil Magistrates Court"),
  MIDDLESBROUGH_TEESSIDE_MAGISTRATES_COURT("Middlesbrough (Teesside) Magistrates Court"),
  MILDENHALL_MAGISTRATES_COURT("Mildenhall Magistrates Court"),
  MILTON_KEYNES_MAGISTRATES_COURT("Milton Keynes Magistrates Court"),
  MINEHEAD_MAGISTRATES_COURT("Minehead Magistrates Court"),
  MOLD_MAGISTRATES_COURT("Mold Magistrates Court"),
  NEATH_MAGISTRATES_COURT("Neath Magistrates Court"),
  NEWARK_MAGISTRATES_COURT("Newark Magistrates Court"),
  NEWBURY_MAGISTRATES_COURT("Newbury Magistrates Court"),
  NEWCASTLE_MAGISTRATES_COURT("Newcastle Magistrates Court"),
  NEWCASTLE_UPON_TYNE_MAGISTRATES_COURT("Newcastle Upon Tyne Magistrates Court"),
  NEWPORT_SOUTH_WALES_MAGISTRATES_COURT("Newport (South Wales) Magistrates Court"),
  NEWPORT_MAGISTRATES_COURT("Newport Magistrates Court"),
  NEWTON_ABBOT_MAGISTRATES_COURT("Newton Abbot Magistrates Court"),
  NEWTON_AYCLIFFE_MAGISTRATES_COURT("Newton Aycliffe Magistrates Court"),
  NEWTON_MAGISTRATES_COURT("Newton Magistrates Court"),
  NEWTOWN_MAGISTRATES_COURT("Newtown Magistrates Court"),
  NORTH_SHIELDS_MAGISTRATES_COURT("North Shields Magistrates Court"),
  NORTH_SOMERSET_MAGISTRATES_COURT("North Somerset Magistrates Court"),
  NORTH_STAFFORDSHIRE_JUSTICE_CENTRE_MAGISTRATES_COURT("North Staffordshire Justice Centre Magistrates Court"),
  NORTH_TYNESIDE_MAGISTRATES_COURT("North Tyneside Magistrates Court"),
  NORTHALLERTON_MAGISTRATES_COURT("Northallerton Magistrates Court"),
  NORTHAMPTON_MAGISTRATES_COURT("Northampton Magistrates Court"),
  NORTHWICH_MAGISTRATES_COURT("Northwich Magistrates Court"),
  NORWICH_MAGISTRATES_COURT("Norwich Magistrates Court"),
  NOTTINGHAM_MAGISTRATES_COURT("Nottingham Magistrates Court"),
  NUNEATON_MAGISTRATES_COURT("Nuneaton Magistrates Court"),
  NUNEATON_VICARAGE_ST_MAGISTRATES_COURT("Nuneaton, Vicarage St Magistrates Court"),
  OAKHAM_MAGISTRATES_COURT("Oakham Magistrates Court"),
  OKEHAMPTON_MAGISTRATES_COURT("Okehampton Magistrates Court"),
  OLDHAM_MAGISTRATES_COURT("Oldham Magistrates Court"),
  ORMSKIRK_MAGISTRATES_COURT("Ormskirk Magistrates Court"),
  OSWESTRY_MAGISTRATES_COURT("Oswestry Magistrates Court"),
  OXFORD_MAGISTRATES_COURT("Oxford Magistrates Court"),
  PENRITH_MAGISTRATES_COURT("Penrith Magistrates Court"),
  PENZANCE_MAGISTRATES_COURT("Penzance Magistrates Court"),
  PETERBOROUGH_MAGISTRATES_COURT("Peterborough Magistrates Court"),
  PETERLEE_MAGISTRATES_COURT("Peterlee Magistrates Court"),
  PICKERING_MAGISTRATES_COURT("Pickering Magistrates Court"),
  PLYMOUTH_MAGISTRATES_COURT("Plymouth Magistrates Court"),
  PONTEFRACT_MAGISTRATES_COURT("Pontefract Magistrates Court"),
  PONTYPRIDD_MAGISTRATES_COURT("Pontypridd Magistrates Court"),
  POOLE_MAGISTRATES_COURT("Poole Magistrates Court"),
  PORT_TALBOT_MAGISTRATES_COURT("Port Talbot Magistrates Court"),
  PORTSMOUTH_MAGISTRATES_COURT("Portsmouth Magistrates Court"),
  PRESTATYN_MAGISTRATES_COURT("Prestatyn Magistrates Court"),
  PRESTON_MAGISTRATES_COURT("Preston Magistrates Court"),
  PWLLHELI_MAGISTRATES_COURT("Pwllheli Magistrates Court"),
  RAWTENSTALL_MAGISTRATES_COURT("Rawtenstall Magistrates Court"),
  READING_MAGISTRATES_COURT("Reading Magistrates Court"),
  REDBRIDGE_MAGISTRATES_COURT("Redbridge Magistrates Court"),
  REDDITCH_MAGISTRATES_COURT("Redditch Magistrates Court"),
  REDHILL_MAGISTRATES_COURT("Redhill Magistrates Court"),
  REEDLEY_MAGISTRATES_COURT("Reedley Magistrates Court"),
  RETFORD_MAGISTRATES_COURT("Retford Magistrates Court"),
  RHONDDA_MAGISTRATES_COURT("Rhondda Magistrates Court"),
  RICHMOND_MAGISTRATES_COURT("Richmond Magistrates Court"),
  ROCHDALE_MAGISTRATES_COURT("Rochdale Magistrates Court"),
  ROMFORD_MAGISTRATES_COURT("Romford Magistrates Court"),
  ROSSENDALE_MAGISTRATES_COURT("Rossendale Magistrates Court"),
  ROTHERHAM_MAGISTRATES_COURT("Rotherham Magistrates Court"),
  RUGBY_MAGISTRATES_COURT("Rugby Magistrates Court"),
  RUGELEY_MAGISTRATES_COURT("Rugeley Magistrates Court"),
  RUNCORN_MAGISTRATES_COURT("Runcorn Magistrates Court"),
  RUTLAND_MAGISTRATES_COURT("Rutland Magistrates Court"),
  SALE_MAGISTRATES_COURT("Sale Magistrates Court"),
  SALFORD_MAGISTRATES_COURT("Salford Magistrates Court"),
  SALISBURY_MAGISTRATES_COURT("Salisbury Magistrates Court"),
  SCARBOROUGH_MAGISTRATES_COURT("Scarborough Magistrates Court"),
  SCUNTHORPE_MAGISTRATES_COURT("Scunthorpe Magistrates Court"),
  SEFTON_MAGISTRATES_COURT("Sefton Magistrates Court"),
  SELBY_MAGISTRATES_COURT("Selby Magistrates Court"),
  SEVENOAKS_MAGISTRATES_COURT("Sevenoaks Magistrates Court"),
  SHEFFIELD_MAGISTRATES_COURT("Sheffield Magistrates Court"),
  SHERBORNE_MAGISTRATES_COURT("Sherborne Magistrates Court"),
  SHREWSBURY_MAGISTRATES_COURT("Shrewsbury Magistrates Court"),
  SITTINGBOURNE_MAGISTRATES_COURT("Sittingbourne Magistrates Court"),
  SKEGNESS_MAGISTRATES_COURT("Skegness Magistrates Court"),
  SKIPTON_MAGISTRATES_COURT("Skipton Magistrates Court"),
  SLEAFORD_MAGISTRATES_COURT("Sleaford Magistrates Court"),
  SLOUGH_MAGISTRATES_COURT("Slough Magistrates Court"),
  SOLIHULL_MAGISTRATES_COURT("Solihull Magistrates Court"),
  SOUTH_SEFTON_MAGISTRATES_COURT("South Sefton Magistrates Court"),
  SOUTH_TYNESIDE_MAGISTRATES_COURT("South Tyneside Magistrates Court"),
  SOUTH_WESTERN_MAGISTRATES_COURT("South Western Magistrates Court"),
  SOUTHAMPTON_THE_AVENUE_MAGISTRATES_COURT("Southampton (The Avenue) Magistrates Court"),
  SOUTHEND_MAGISTRATES_COURT("Southend Magistrates Court"),
  SOUTHEND_ON_SEA_MAGISTRATES_COURT("Southend on Sea Magistrates Court"),
  SOUTHPORT_MAGISTRATES_COURT("Southport Magistrates Court"),
  SPALDING_MAGISTRATES_COURT("Spalding Magistrates Court"),
  ST_ALBANS_MAGISTRATES_COURT("St Albans Magistrates Court"),
  ST_GEORGES_HALL_MAGISTRATES_COURT("St Georges Hall Magistrates Court"),
  ST_HELENS_MAGISTRATES_COURT("St Helens Magistrates Court"),
  STAFFORD_MAGISTRATES_COURT("Stafford Magistrates Court"),
  STAINES_MAGISTRATES_COURT("Staines Magistrates Court"),
  STAMFORD_MAGISTRATES_COURT("Stamford Magistrates Court"),
  STEVENAGE_MAGISTRATES_COURT("Stevenage Magistrates Court"),
  STOCKPORT_MAGISTRATES_COURT("Stockport Magistrates Court"),
  STOKE_ON_TRENT_MAGISTRATES_COURT("Stoke on Trent Magistrates Court"),
  STOURBRIDGE_MAGISTRATES_COURT("Stourbridge Magistrates Court"),
  STRATFORD_MAGISTRATES_COURT("Stratford Magistrates Court"),
  STRATFORD_UPON_AVON_MAGISTRATES_COURT("Stratford upon Avon Magistrates Court"),
  STROUD_MAGISTRATES_COURT("Stroud Magistrates Court"),
  SUDBURY_MAGISTRATES_COURT("Sudbury Magistrates Court"),
  SUNDERLAND_MAGISTRATES_COURT("Sunderland Magistrates Court"),
  SUTTON_COLDFIELD_MAGISTRATES_COURT("Sutton Coldfield Magistrates Court"),
  SUTTON_MAGISTRATES_COURT("Sutton Magistrates Court"),
  SWAFFHAM_MAGISTRATES_COURT("Swaffham Magistrates Court"),
  SWANSEA_MAGISTRATES_COURT("Swansea Magistrates Court"),
  SWINDON_MAGISTRATES_COURT("Swindon Magistrates Court"),
  TAMESIDE_MAGISTRATES_COURT("Tameside Magistrates Court"),
  TAMWORTH_MAGISTRATES_COURT("Tamworth Magistrates Court"),
  TAUNTON_MAGISTRATES_COURT("Taunton Magistrates Court"),
  TEESSIDE_MAGISTRATES_COURT("Teesside Magistrates Court"),
  TELFORD_MAGISTRATES_COURT("Telford Magistrates Court"),
  TENBY_MAGISTRATES_COURT("Tenby Magistrates Court"),
  TEWKESBURY_MAGISTRATES_COURT("Tewkesbury Magistrates Court"),
  THAME_MAGISTRATES_COURT("Thame Magistrates Court"),
  THAMES_MAGISTRATES_COURT("Thames Magistrates Court"),
  THETFORD_MAGISTRATES_COURT("Thetford Magistrates Court"),
  TORQUAY_MAGISTRATES_COURT("Torquay Magistrates Court"),
  TOTNES_MAGISTRATES_COURT("Totnes Magistrates Court"),
  TOTTENHAM_MAGISTRATES_COURT("Tottenham Magistrates Court"),
  TOWCESTER_MAGISTRATES_COURT("Towcester Magistrates Court"),
  TOWER_BRIDGE_MAGISTRATES_COURT("Tower Bridge Magistrates Court"),
  TREDEGAR_MAGISTRATES_COURT("Tredegar Magistrates Court"),
  TROWBRIDGE_MAGISTRATES_COURT("Trowbridge Magistrates Court"),
  TRURO_MAGISTRATES_COURT("Truro Magistrates Court"),
  UXBRIDGE_MAGISTRATES_COURT("Uxbridge Magistrates Court"),
  WAKEFIELD_MAGISTRATES_COURT("Wakefield Magistrates Court"),
  WALLASEY_MAGISTRATES_COURT("Wallasey Magistrates Court"),
  WALSALL_MAGISTRATES_COURT("Walsall Magistrates Court"),
  WALTHAM_FOREST_MAGISTRATES_COURT("Waltham Forest Magistrates Court"),
  WANTAGE_MAGISTRATES_COURT("Wantage Magistrates Court"),
  WAREHAM_MAGISTRATES_COURT("Wareham Magistrates Court"),
  WARLEY_MAGISTRATES_COURT("Warley Magistrates Court"),
  WARRINGTON_MAGISTRATES_COURT("Warrington Magistrates Court"),
  WATFORD_MAGISTRATES_COURT("Watford Magistrates Court"),
  WELLINGBOROUGH_MAGISTRATES_COURT("Wellingborough Magistrates Court"),
  WELLS_MAGISTRATES_COURT("Wells Magistrates Court"),
  WELSHPOOL_MAGISTRATES_COURT("Welshpool Magistrates Court"),
  WEST_BROMWICH_MAGISTRATES_COURT("West Bromwich Magistrates Court"),
  WEST_HAMPSHIRE_MAGISTRATES_COURT("West Hampshire Magistrates Court"),
  WEST_LONDON_MAGISTRATES_COURT("West London Magistrates Court"),
  WESTMINSTER_MAGISTRATES_COURT("Westminster Magistrates Court"),
  WESTMINSTER_MAGISTRATES_COURT_INTERNATIONAL_DIVISION("Westminster Magistrates Court - International Division"),
  WESTON_SUPER_MARE_MAGISTRATES_COURT("Weston Super Mare Magistrates Court"),
  WETHERBY_MAGISTRATES_COURT("Wetherby Magistrates Court"),
  WEYMOUTH_MAGISTRATES_COURT("Weymouth Magistrates Court"),
  WHITBY_MAGISTRATES_COURT("Whitby Magistrates Court"),
  WHITCHURCH_MAGISTRATES_COURT("Whitchurch Magistrates Court"),
  WHITEHAVEN_MAGISTRATES_COURT("Whitehaven Magistrates Court"),
  WIDNES_MAGISTRATES_COURT("Widnes Magistrates Court"),
  WIGAN_AND_LEIGH_MAGISTRATES_COURT("Wigan and Leigh Magistrates Court"),
  WIGAN_MAGISTRATES_COURT("Wigan Magistrates Court"),
  WILLESDEN_MAGISTRATES_COURT("Willesden Magistrates Court"),
  WIMBLEDON_MAGISTRATES_COURT("Wimbledon Magistrates Court"),
  WIMBORNE_MAGISTRATES_COURT("Wimborne Magistrates Court"),
  WINCHESTER_COMBINED_COURT_CENTRE_MAGISTRATES_COURT("Winchester Combined Court Centre Magistrates Court"),
  WIRRAL_MAGISTRATES_COURT("Wirral Magistrates Court"),
  WISBECH_MAGISTRATES_COURT("Wisbech Magistrates Court"),
  WITHAM_MAGISTRATES_COURT("Witham Magistrates Court"),
  WITNEY_MAGISTRATES_COURT("Witney Magistrates Court"),
  WOKING_MAGISTRATES_COURT("Woking Magistrates Court"),
  WOLVERHAMPTON_MAGISTRATES_COURT("Wolverhampton Magistrates Court"),
  WOOLWICH_MAGISTRATES_COURT("Woolwich Magistrates Court"),
  WORCESTER_CASTLE_ST_MAGISTRATES_COURT("Worcester (Castle St) Magistrates Court"),
  WORKINGTON_MAGISTRATES_COURT("Workington Magistrates Court"),
  WORKSOP_MAGISTRATES_COURT("Worksop Magistrates Court"),
  WORTHING_MAGISTRATES_COURT("Worthing Magistrates Court"),
  WREXHAM_MAGISTRATES_COURT("Wrexham Magistrates Court"),
  WYCOMBE_MAGISTRATES_COURT("Wycombe Magistrates Court"),
  YATE_MAGISTRATES_COURT("Yate Magistrates Court"),
  YEOVIL_COUNTY_MAGISTRATES_COURT("Yeovil County, Magistrates Court"),
  YEOVIL_MAGISTRATES_COURT("Yeovil Magistrates Court"),
  YORK_MAGISTRATES_COURT("York Magistrates Court"),
  YSTRADGYNLAIS_MAGISTRATES_COURT("Ystradgynlais Magistrates Court"),
  ;

  companion object {
    fun from(value: String?): MagistrateCourtDDv5? = entries.firstOrNull {
      it.name == value
    }
  }
}
